
QUESTIONS += [

    # ── NO.9 (115F-40) ★ 97% ans=e ─────────────────────────────
    Q('115F-40', 97, [('bs', '★')],
      '74 歳の男性。<span class="kw">1 週前に大動脈弁狭窄症に対して'
      '大動脈弁置換術を施行した。</span>術後経過は良好で退院を目指し、'
      '一般病棟でリハビリテーションに励んでいた。'
      '<span class="kw">昨日から食欲不振があり、今朝から息切れと全身倦怠感を訴えている。</span>'
      '意識は清明。体温36.7℃。脈拍100/ 分、整。'
      '<span class="kw">血圧94/74mmHg</span>。呼吸数18/ 分。SpO<sub>2</sub> 98％（room air）。'
      '眼瞼結膜は軽度貧血様で、眼球結膜に黄染を認めない。'
      '<span class="kw">頸静脈怒張を認める。心音は減弱。呼吸音に異常を認めない。</span>'
      '腹部は平坦、軟で、胸部正中に手術痕を認める。'
      '血液所見：赤血球352 万、Hb 10.7g/dL、Ht 31％、白血球8,700、血小板10 万。'
      '血液生化学所見：アルブミン3.3g/dL、総ビリルビン1.2mg/dL、AST 31U/L、ALT 52U/L、'
      'LD 331U/L（基準120 ～245）、CK 50U/L（基準30 ～140）、尿素窒素30mg/dL、'
      'クレアチニン1.1mg/dL、Na 136mEq/L、K 5.1mEq/L、Cl 99mEq/L。CRP 1.2mg/dL。'
      '胸部エックス線写真（A）及び胸部単純CT（B）を示す。<br>'
      '<strong>症状に最も関連している病態はどれか。</strong>',
      [('a', '気　胸', False,
        '<span class="kw4">気胸なら患側の呼吸音減弱と'
        '胸部エックス線写真での虚脱した肺・肺紋理を欠く'
        '透亮域がみられるはず</span>だが、'
        '<span class="kw4">本例は「呼吸音に異常を認めない」うえ'
        'SpO<sub>2</sub> 98%と酸素化も保たれている</span>。'
        '<span class="kw">緊張性気胸なら頸静脈怒張と血圧低下は出るが、'
        '呼吸音は必ず左右差を生じる</span>。'),
       ('b', '貧　血', False,
        '<span class="kw4">Hb 10.7g/dL は術後としてはよくある程度の'
        '軽度貧血で、息切れと全身倦怠感の主因とするには軽すぎる</span>。'
        '<span class="kw4">何より貧血では頸静脈怒張も心音減弱も説明できない</span>。'
        '<span class="kw">貧血が原因なら循環血液量が減って'
        '頸静脈はむしろ虚脱する</span>。'),
       ('c', '縦隔炎', False,
        '<span class="kw4">胸骨正中切開後の縦隔炎は重篤な合併症だが、'
        '発熱・創部の発赤や排膿・強い炎症反応を伴う</span>。'
        '<span class="kw4">本例は体温36.7℃、白血球8,700、CRP 1.2mg/dLと'
        '炎症所見に乏しい</span>。'),
       ('d', '胸水貯留', False,
        '<span class="kw4">胸水があれば患側の呼吸音減弱・打診での濁音・'
        'エックス線写真での肋骨横隔膜角の鈍化がみられる</span>。'
        '<span class="kw4">本例は呼吸音正常で、'
        'しかも胸水では頸静脈怒張と心音減弱は説明できない</span>。'
        '<span class="kw">心囊液貯留に伴って少量の胸水を認めることはあるが、'
        '「最も関連している病態」ではない</span>。'),
       ('e', '心囊液貯留', True,
        '<span class="kw3">◯ 心臓手術後の心タンポナーデ</span>。'
        '<span class="kw3">Beckの三徴＝①血圧低下 ②頸静脈怒張 ③心音減弱</span>が'
        'そのまま並んでいる。'
        '<span class="kw3">加えて脈圧の狭小化（94/74mmHg＝脈圧20mmHg）</span>も'
        '典型的で、<span class="kw3">心囊内圧の上昇で拡張期の充満が妨げられ、'
        '1回拍出量が落ちて代償性頻脈（100/分）になっている</span>。'
        '<span class="kw3">心臓手術後1週というのは'
        '亜急性〜遅発性心タンポナーデの好発時期</span>で、'
        '<span class="kw3">徐々に貯留するため急性のような'
        'ショックにならず、「食欲不振・全身倦怠感・息切れ」という'
        '非特異的な訴えで始まる</span>のが臨床的な落とし穴である。'
        '<span class="kw3">診断は心エコー（右房・右室の拡張期虚脱）が最速で、'
        '治療は心囊穿刺／ドレナージ</span>。')],
      'Beckの三徴（血圧低下・頸静脈怒張・心音減弱）＋術後1週＝心タンポナーデ。',
      imgs=[IMG + '115F-40_1.jpeg', IMG + '115F-40_2.jpeg'],
      patho=('🔎 画像所見——胸部エックス線写真の心陰影拡大と、CTの心囊液',
             '<span class="kw3">A（胸部エックス線写真）では心陰影が'
             '左右へ大きく張り出し、いわゆる「フラスコ状」の輪郭を呈する</span>。'
             '<span class="kw3">肺野は清明で肺うっ血を伴わない</span>のが要点——'
             '<span class="kw3">心不全なら肺うっ血・Kerley B線・胸水を伴うが、'
             '心タンポナーデでは「心陰影だけが大きく、肺野は綺麗」</span>になる。<br>'
             '<span class="kw3">B（胸部単純CT）では、心臓の全周を取り囲む'
             '三日月〜輪状の低吸収域＝心囊液貯留</span>が確認できる。'
             '<span class="kw3">単純CTでも液体（水に近いCT値）と'
             '心筋（軟部組織）のコントラストで判別できる</span>。'
             '<table class="tb"><tr><th></th><th>心タンポナーデ</th>'
             '<th>心不全（うっ血）</th><th>緊張性気胸</th></tr>'
             '<tr><td>頸静脈怒張</td>'
             '<td><span class="kw3">あり</span></td>'
             '<td><span class="kw">あり</span></td>'
             '<td><span class="kw">あり</span></td></tr>'
             '<tr><td>心　音</td>'
             '<td><span class="kw3">減弱</span></td>'
             '<td>Ⅲ音・Ⅳ音</td><td>減弱（偏位）</td></tr>'
             '<tr><td>呼吸音</td>'
             '<td><span class="kw3">正常</span></td>'
             '<td><span class="kw">湿性ラ音</span></td>'
             '<td><span class="kw4">患側で消失</span></td></tr>'
             '<tr><td>胸部エックス線</td>'
             '<td><span class="kw3">心陰影拡大・肺野は清明</span></td>'
             '<td><span class="kw">心拡大＋肺うっ血・胸水</span></td>'
             '<td><span class="kw4">患側の透亮・縦隔偏位</span></td></tr>'
             '<tr><td>脈　圧</td>'
             '<td><span class="kw3">狭小（本例20mmHg）・奇脈</span></td>'
             '<td>—</td><td>—</td></tr>'
             '<tr><td>対応</td>'
             '<td><span class="kw3">心囊穿刺・ドレナージ</span></td>'
             '<td>利尿薬・血管拡張薬</td>'
             '<td><span class="kw4">緊急脱気</span></td></tr></table>'),
      deep=('💡 CTで液体をどう見分けるか——CT値という物差し',
            '<span class="kw3">CTの画素値（CT値、単位HU）は'
            '「水を0、空気を−1000」と決めた相対的な吸収値</span>で、'
            '<span class="kw3">これを覚えておくと単純CTでも'
            '中身をかなり推定できる</span>。'
            '<table class="tb"><tr><th>組織・物質</th><th>CT値（HU）</th>'
            '<th>臨床での使いどころ</th></tr>'
            '<tr><td><span class="kw3">骨・石灰化</span></td>'
            '<td><span class="kw3">＞100（骨皮質は1000前後）</span></td>'
            '<td><span class="kw3">結石・血管の石灰化・骨折</span></td></tr>'
            '<tr><td><span class="kw3">急性期の血腫</span></td>'
            '<td><span class="kw3">＞50（50〜80）</span></td>'
            '<td><span class="kw3">頭蓋内出血・血性心囊液／胸腹水</span>'
            '——<span class="kw3">単純CTで「白い」のが出血</span></td></tr>'
            '<tr><td>軟部組織・筋</td><td>約50（40〜60）</td>'
            '<td>基準になる</td></tr>'
            '<tr><td><span class="kw3">水・漿液</span></td>'
            '<td><span class="kw3">0前後</span></td>'
            '<td><span class="kw3">囊胞・漿液性の胸腹水・心囊液</span></td></tr>'
            '<tr><td><span class="kw">脂　肪</span></td>'
            '<td><span class="kw">−100前後</span></td>'
            '<td><span class="kw">脂肪腫・奇形腫・脂肪肝</span></td></tr>'
            '<tr><td><span class="kw">空　気</span></td>'
            '<td><span class="kw">−1000</span></td>'
            '<td><span class="kw">気胸・遊離ガス・消化管ガス</span></td></tr>'
            '<tr><td colspan="3"><span class="kw3">表示の設定も重要</span>——'
            '<span class="kw3">ウインドウレベル＝表示する濃度の中心'
            '（写真の明るさ）、ウインドウ幅＝表示する濃度の幅'
            '（コントラスト）</span>。'
            '<span class="kw">肺野条件・縦隔条件・骨条件は'
            'この2つを変えているだけで、元のデータは同じ</span>。</td></tr></table>'
            '<span class="kw3">心囊液が血性（術後出血）か漿液性かは'
            'CT値でおおよそ推定でき、治療の緊急度に関わる</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">心タンポナーデのBeckの三徴＝'
             '血圧低下・頸静脈怒張・心音減弱</span>。'
             '<span class="kw3">＋脈圧狭小・奇脈・頻脈</span>。<br>'
             '② <span class="kw3">胸部エックス線では「心陰影拡大＋肺野は清明」</span>。<br>'
             '③ <span class="kw3">診断は心エコー（右房・右室の拡張期虚脱）、'
             '治療は心囊穿刺・ドレナージ</span>。<br>'
             '④ <span class="kw">心臓手術後1〜2週は遅発性心タンポナーデの好発時期</span>——'
             '<span class="kw">非特異的な倦怠感・食欲不振で始まる</span>。<br>'
             '⑤ <span class="kw3">CT値＝骨100超／出血50超／軟部50／水0／'
             '脂肪−100／空気−1000</span>。')),

    # ── NO.10 (113D-50) ★ 80% ans=a ────────────────────────────
    Q('113D-50', 80, [('bs', '★')],
      '72 歳の男性。6 か月前からの頻尿を主訴に来院した。'
      '1 日に何度もトイレに行きたくなることがあるが、'
      '咳やくしゃみをしたときに尿が漏れることはない。'
      '1 か月前から排尿時の違和感を感じるようになり、軽快しないため受診した。'
      '既往歴と家族歴とに特記すべきことはない。腹部は平坦、軟で、肝・脾を触知しない。'
      '尿所見：蛋白（－）、糖（－）、潜血1 ＋、沈渣は赤血球5 ～9/HPF、白血球5 ～9/HPF。'
      '血液所見：赤血球442 万、Hb 14.0g/dL、Ht 40％、白血球7,400、血小板24 万。'
      '血液生化学所見：総蛋白6.9g/dL、アルブミン4.3g/dL、総ビリルビン1.2mg/dL、'
      'AST 21U/L、ALT 15U/L、尿素窒素22mg/dL、クレアチニン1.0mg/dL、'
      '<span class="kw">尿酸8.6mg/dL</span>、血糖94mg/dL、総コレステロール192mg/dL、'
      'Na 142mEq/L、K 4.6mEq/L、Cl 106mEq/L。腹部超音波検査で水腎症を認めない。'
      '腹部エックス線写真（A）及び腹部単純CT（B）を示す。'
      '<span class="kw">砕石術を行ったところ、赤レンガ色の結石を排出した。</span><br>'
      '<strong>再発予防に有効な薬剤はどれか。</strong>',
      [('a', 'アロプリノール', True,
        '<span class="kw3">◯ 尿酸結石の再発予防</span>。'
        '<span class="kw3">アロプリノールはキサンチンオキシダーゼ阻害薬で、'
        '尿酸の産生そのものを抑える</span>——'
        '<span class="kw3">血中・尿中の尿酸量を減らすので結石の材料が減る</span>。'
        '<span class="kw3">尿酸結石の予防で最も重要なのは'
        '「尿のアルカリ化（クエン酸製剤で尿pH 6.2〜6.8へ）」と'
        '「十分な飲水（1日尿量2L以上）」で、'
        '高尿酸血症を伴う例ではこれに尿酸生成抑制薬を加える</span>。'
        '<span class="kw3">本例は尿酸8.6mg/dLと高値なのでよい適応</span>。'),
       ('b', 'サイアザイド系利尿薬', False,
        '<span class="kw4">サイアザイドが再発予防に有効なのは'
        '「高カルシウム尿症を伴うカルシウム結石」</span>である'
        '（<span class="kw">遠位尿細管でのCa再吸収を促進して尿中Caを減らす</span>）。'
        '<span class="kw4">しかもサイアザイドは尿酸の排泄を抑制して'
        '血清尿酸値を上げる</span>ので、'
        '<span class="kw4">尿酸結石にはむしろ不利</span>である。'),
       ('c', 'チオプロニン', False,
        '<span class="kw4">チオプロニン（およびD-ペニシラミン）は'
        'シスチン結石に用いる薬剤</span>。'
        '<span class="kw">シスチンとジスルフィド結合を作って'
        '溶解度の高い複合体にする</span>。'
        '<span class="kw4">シスチン結石は常染色体潜性遺伝の'
        'シスチン尿症による小児〜若年発症の結石</span>で、'
        '<span class="kw4">72歳の初発例では考えにくい</span>。'),
       ('d', 'ビタミンD 製剤', False,
        '<span class="kw4">活性型ビタミンDは腸管からのカルシウム吸収を促進し、'
        '尿中カルシウム排泄を増やす</span>ので、'
        '<span class="kw4">むしろ結石のリスクを上げる</span>。'
        '<span class="kw4">予防薬として真逆</span>である。'),
       ('e', 'ベンズブロマロン', False,
        '<span class="kw4">ベンズブロマロンは尿酸<u>排泄促進</u>薬</span>——'
        '<span class="kw4">尿中への尿酸排泄を増やすので、'
        '尿酸結石の患者には禁忌に近い</span>。'
        '<span class="kw3">同じ「高尿酸血症の薬」でも、'
        '尿路結石があるときは<u>産生抑制薬（アロプリノール・'
        'フェブキソスタット）</u>を選び、'
        '<u>排泄促進薬は避ける</u></span>——'
        '<span class="kw3">この使い分けが本問の核心</span>である。')],
      '赤レンガ色＋Ｘ線陰性＝尿酸結石。産生抑制薬（アロプリノール）で、排泄促進薬は禁。',
      imgs=[IMG + '113D-50_1.jpeg', IMG + '113D-50_2.jpeg'],
      patho=('🔎 画像所見——「単純エックス線で写らないのにCTでは写る」',
             '<span class="kw3">A（腹部エックス線写真・仰臥位）では'
             '尿路に一致する明らかな石灰化陰影を指摘できない</span>'
             '＝<span class="kw3">Ｘ線陰性結石</span>。'
             '<span class="kw3">一方 B（腹部単純CT）では高吸収の結石が描出される</span>。'
             '<span class="kw3">この「単純撮影で写らないのにCTでは写る」という'
             '組合せが、尿酸結石を強く示唆する</span>。'
             '<table class="tb"><tr><th>結石の種類</th><th>頻度</th>'
             '<th>単純エックス線</th><th>CT</th><th>背景・予防</th></tr>'
             '<tr><td><span class="kw3">シュウ酸カルシウム／'
             'リン酸カルシウム</span></td>'
             '<td><span class="kw3">約80%（最多）</span></td>'
             '<td><span class="kw3">陽性（写る）</span></td>'
             '<td>高吸収</td>'
             '<td><span class="kw">飲水・クエン酸。'
             '高Ca尿症にはサイアザイド</span>。'
             '<span class="kw4">カルシウム制限は逆効果</span></td></tr>'
             '<tr><td><span class="kw3">尿酸結石</span></td>'
             '<td><span class="kw3">約5〜10%</span></td>'
             '<td><span class="kw3">陰性（写らない）</span></td>'
             '<td><span class="kw3">写る</span></td>'
             '<td><span class="kw3">赤レンガ色。高尿酸血症・酸性尿・'
             '痛風・脱水・肥満。予防は尿アルカリ化＋飲水'
             '＋アロプリノール</span></td></tr>'
             '<tr><td><span class="kw">リン酸マグネシウム'
             'アンモニウム（ストルバイト）</span></td>'
             '<td>数%</td><td><span class="kw">陽性</span></td><td>写る</td>'
             '<td><span class="kw">ウレアーゼ産生菌（Proteus）による'
             '感染結石。サンゴ状結石を作る</span></td></tr>'
             '<tr><td><span class="kw">シスチン結石</span></td>'
             '<td>1%未満</td>'
             '<td><span class="kw">やや写りにくい</span></td><td>写る</td>'
             '<td><span class="kw">シスチン尿症（遺伝性）。'
             '小児〜若年。チオプロニン</span></td></tr>'
             '<tr><td colspan="5"><span class="kw3">尿路結石を疑ったときの'
             '第一選択の画像検査は「単純CT」</span>——'
             '<span class="kw3">造影しなくても、ほぼすべての結石が'
             '高吸収に描出されるから</span>'
             '（<span class="kw4">例外はインジナビルなど一部の薬剤性結石</span>）。</td></tr>'
             '</table>'),
      deep=('💡 「Ｘ線陰性結石」を疑わせる文の型',
            '<span class="kw3">国試では尿酸結石を'
            '3通りの書き方で示してくる</span>。'
            '<table class="tb"><tr><th>本文の記載</th><th>意味</th></tr>'
            '<tr><td><span class="kw3">腹部エックス線写真で結石を指摘できない'
            '／Ｘ線陰性</span></td>'
            '<td><span class="kw3">尿酸結石（またはシスチン・薬剤性）</span></td></tr>'
            '<tr><td><span class="kw3">赤レンガ色・黄褐色の結石を排出した</span></td>'
            '<td><span class="kw3">尿酸結石の肉眼所見</span></td></tr>'
            '<tr><td><span class="kw3">痛風・高尿酸血症・'
            '尿酸排泄促進薬の内服・肥満・酸性尿</span></td>'
            '<td><span class="kw3">尿酸結石の背景因子</span></td></tr>'
            '<tr><td colspan="2"><span class="kw3">この3つのどれかが出たら'
            '「単純CTで確認 → 尿アルカリ化＋飲水＋'
            '（高尿酸血症があれば）アロプリノール」</span>という筋になる。<br>'
            '<span class="kw3">尿酸結石は尿をアルカリ化すると'
            '<u>溶解する</u>のが特徴</span>——'
            '<span class="kw3">他の結石と違い、薬で溶かせる唯一の結石</span>である。</td></tr>'
            '</table>'
            '<span class="kw4">⚠️ 高尿酸血症の薬の使い分けは'
            '尿路結石の有無で決まる</span>——'
            '<span class="kw3">結石がある／尿酸排泄が多い → 産生抑制薬'
            '（アロプリノール・フェブキソスタット）／'
            '尿酸排泄が少ない → 排泄促進薬（ベンズブロマロン）</span>。'
            '<span class="kw4">結石患者に排泄促進薬を使うと'
            '結石を作りに行くことになる</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">Ｘ線陰性＋赤レンガ色＝尿酸結石</span>。'
             '<span class="kw3">単純CTでは写る</span>。<br>'
             '② <span class="kw3">尿酸結石の予防＝尿のアルカリ化'
             '（クエン酸製剤）＋飲水＋アロプリノール</span>。<br>'
             '③ <span class="kw4">ベンズブロマロン（排泄促進薬）は尿酸結石に不適</span>。<br>'
             '④ <span class="kw">サイアザイド＝高Ca尿症のカルシウム結石／'
             'チオプロニン＝シスチン結石</span>。<br>'
             '⑤ <span class="kw3">尿路結石を疑ったらまず単純CT</span>'
             '（造影不要でほぼ全部写る）。')),

    # ── NO.11 (オリジナル) ★ rate=None ans=e ────────────────────
    Q('オリジナル', None, [('bs', '★')],
      '頭部CT を示す。<br><strong>診断はどれか。</strong>',
      [('a', '脳腫瘍', False,
        '<span class="kw4">脳腫瘍なら腫瘤性病変・周囲の浮腫（低吸収域）・'
        '正中偏位や脳室の変形といった占拠性病変の所見がみられる</span>。'
        '<span class="kw4">本例の単純CTにはそうした所見がない</span>。'),
       ('b', '水頭症', False,
        '<span class="kw4">水頭症では脳室が拡大する</span>'
        '（<span class="kw">側脳室前角の開大、Evans indexの上昇、'
        '第三脳室・側頭角の拡大</span>）。'
        '<span class="kw4">本例では脳室系の拡大を認めない</span>。'),
       ('c', '脳動脈瘤', False,
        '<span class="kw4">未破裂脳動脈瘤は単純CTではほとんど描出できない</span>——'
        '<span class="kw4">血管と同じ吸収値だから</span>。'
        '<span class="kw">診断にはCTA・MRA・脳血管造影が要る</span>。'
        '<span class="kw4">「単純CTで動脈瘤を診断する」という設定が'
        'そもそも成り立たない</span>。'),
       ('d', 'くも膜下出血', False,
        '<span class="kw4">くも膜下出血なら、'
        '本来は黒く見えるはずの脳底槽・シルビウス裂・'
        '迂回槽といったくも膜下腔が'
        '血液（CT値50〜80HU）で白く埋まる</span>——'
        '<span class="kw4">いわゆる「ヒトデ型（star sign）」</span>。'
        '<span class="kw4">本例では脳底部の脳槽は黒く保たれており、'
        '高吸収域を認めない</span>。'
        '<span class="kw3">単純CTはくも膜下出血の検出には'
        '極めて優れた検査で、発症直後の感度は90%以上</span>である。'),
       ('e', '超急性期脳梗塞', True,
        '<span class="kw3">◯ 「単純CTがほぼ正常に見える」ことこそが、'
        '超急性期脳梗塞を示唆する所見である</span>。'
        '<span class="kw3">脳梗塞では細胞性浮腫によって'
        '組織の含水量が増えCT値が下がるが、'
        'それが視認できる低吸収域として現れるまでには'
        '数時間〜24時間かかる</span>——'
        '<span class="kw3">つまり発症直後のCTは「写らない」のが正常な振る舞い</span>。'
        '<span class="kw3">したがってCTの役割は'
        '「脳梗塞を見つけること」ではなく'
        '「まず出血を否定すること」</span>にある'
        '（<span class="kw3">出血があればt-PAは投与できない</span>）。<br>'
        '<span class="kw3">なお注意深く見れば'
        '早期虚血サイン〈early CT sign〉が拾えることがある</span>——'
        '<span class="kw3">①皮髄境界の不明瞭化 ②レンズ核の不明瞭化 '
        '③島皮質の不明瞭化 ④脳溝・シルビウス裂の狭小化 '
        '⑤hyperdense MCA sign（閉塞した中大脳動脈が白く見える）</span>。')],
      '超急性期の脳梗塞は単純CTに写らない。CTの役割は「出血の否定」。',
      imgs=[IMG + 'orig11_1.jpeg'],
      ans_label='ｅ　超急性期脳梗塞',
      patho=('🔎 画像所見——脳底槽は黒く、明らかな低吸収域も腫瘤もない',
             '<span class="kw3">示された頭部単純CTは中脳〜橋の高さの水平断で、'
             '一見して「正常」である</span>。'
             '<span class="kw3">この「異常が指摘できない」という事実そのものが'
             '選択肢を絞る</span>。'
             '<table class="tb"><tr><th>疾患</th>'
             '<th>単純CTで期待される所見</th><th>本例</th></tr>'
             '<tr><td><span class="kw">脳腫瘍</span></td>'
             '<td>腫瘤・周囲の浮腫・占拠効果（正中偏位・脳室の変形）</td>'
             '<td><span class="kw4">なし</span></td></tr>'
             '<tr><td><span class="kw">水頭症</span></td>'
             '<td>脳室の拡大</td><td><span class="kw4">なし</span></td></tr>'
             '<tr><td><span class="kw">脳動脈瘤（未破裂）</span></td>'
             '<td><span class="kw4">そもそも単純CTでは写らない</span></td>'
             '<td>—</td></tr>'
             '<tr><td><span class="kw3">くも膜下出血</span></td>'
             '<td><span class="kw3">脳底槽・シルビウス裂が高吸収に'
             '（白く）埋まる</span></td>'
             '<td><span class="kw3">脳槽は黒く保たれている＝否定的</span></td></tr>'
             '<tr><td><span class="kw3">超急性期脳梗塞</span></td>'
             '<td><span class="kw3">ほぼ正常（写らないのが普通）</span></td>'
             '<td><span class="kw3">合致する</span></td></tr></table>'
             '<span class="kw3">MECのオリジナル問題で、'
             '「CTで写らないことに意味がある」という'
             '放射線科ならではの発想を問うている</span>。'
             '<span class="kw3">この症例はNO.16（MRIの3シーケンス）へ続く</span>——'
             '<span class="kw3">CTで異常が無いからこそ次にMRIを撮る</span>、'
             'という臨床の流れが2問で表現されている。'),
      deep=('💡 脳梗塞の時間経過と画像——「CTで写るころには手遅れ」',
            '<table class="tb"><tr><th>発症からの時間</th>'
            '<th><span class="kw3">単純CT</span></th>'
            '<th><span class="kw3">MRI 拡散強調像〈DWI〉</span></th>'
            '<th><span class="kw3">FLAIR像</span></th></tr>'
            '<tr><td><span class="kw3">〜数十分</span></td>'
            '<td><span class="kw4">正常</span></td>'
            '<td><span class="kw3">すでに高信号</span></td>'
            '<td><span class="kw3">まだ正常</span></td></tr>'
            '<tr><td><span class="kw3">〜4.5時間</span></td>'
            '<td><span class="kw4">正常〜早期虚血サイン</span></td>'
            '<td><span class="kw3">高信号</span></td>'
            '<td><span class="kw3">まだ正常（DWI-FLAIRミスマッチ）</span></td></tr>'
            '<tr><td>6〜24時間</td>'
            '<td><span class="kw">境界不明瞭な低吸収域</span></td>'
            '<td>高信号</td>'
            '<td><span class="kw">高信号になってくる</span></td></tr>'
            '<tr><td>数日〜</td>'
            '<td><span class="kw">明瞭な低吸収域・腫脹</span></td>'
            '<td>高信号（ADCは次第に上昇）</td><td>高信号</td></tr>'
            '<tr><td colspan="4"><span class="kw3">DWIで高信号なのに'
            'FLAIRではまだ高信号でない＝DWI-FLAILミスマッチ</span>'
            'は<span class="kw3">発症4.5時間以内を示唆</span>し、'
            '<span class="kw3">発症時刻が不明な症例'
            '（起床時発症・wake-up stroke）でも'
            't-PA療法の適応を判断する材料になる</span>。</td></tr></table>'
            '<span class="kw3">急性期脳卒中でまず単純CTを撮るのは'
            '「脳梗塞を見るため」ではなく'
            '「出血を否定してt-PAへ進めるかを決めるため」</span>——'
            '<span class="kw3">CTは出血に強く（発症直後から白く写る）、'
            '梗塞に弱い（数時間写らない）</span>という'
            '得意・不得意がそのまま診療手順になっている。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">超急性期脳梗塞は単純CTでは写らない</span>——'
             '<span class="kw3">「正常に見える」ことが所見</span>。<br>'
             '② <span class="kw3">急性期脳卒中でCTを撮る目的は'
             '「出血の否定」</span>。<br>'
             '③ <span class="kw3">早期虚血サイン＝皮髄境界／レンズ核／'
             '島皮質の不明瞭化・脳溝の狭小化・hyperdense MCA sign</span>。<br>'
             '④ <span class="kw3">発症直後から検出できるのはMRIの拡散強調像</span>。<br>'
             '⑤ <span class="kw4">くも膜下出血は単純CTで脳底槽が白くなる'
             '（感度90%以上）</span>。')),

    # ── NO.12 (118D-66) ★ 79% ans=b ────────────────────────────
    Q('118D-66', 79, [('bs', '★')],
      '<span class="kw">9 歳の男児。</span>腹痛のため救急車で搬入された。'
      '2 日前から嘔吐が出現し、徐々に嘔吐が頻回となり間欠的腹痛が出現した。'
      '体温36.8℃。心拍数120/ 分、整。血圧116/66mmHg。呼吸数24/ 分。'
      'SpO<sub>2</sub> 98％（room air）。腹部は軽度膨満し、軟で腸雑音は減弱していた。'
      '右側腹部に腫瘤を触知し、右上腹部に圧痛を認めた。'
      '<span class="kw">腹部超音波検査で腹部正中にtarget sign を認めた。'
      '空気による非観血的整復術にて還納した。</span>'
      'その後行った<span class="kw"><sup>99m</sup>TcO<sub>4</sub><sup>－</sup>'
      'シンチグラム</span>を示す。<br>'
      '<strong>診断はどれか。</strong>',
      [('a', 'Crohn 病', False,
        '<span class="kw4">Crohn病は全消化管に非連続性（skip lesion）の'
        '縦走潰瘍・敷石像を作る炎症性腸疾患</span>で、'
        '<span class="kw4">慢性の下痢・腹痛・体重減少・'
        '肛門病変（痔瘻）を伴う</span>。'
        '<span class="kw4"><sup>99m</sup>TcO<sub>4</sub><sup>－</sup>は'
        '異所性胃粘膜に集まる薬剤で、Crohn病の診断には用いない</span>。'),
       ('b', 'Meckel 憩室', True,
        '<span class="kw3">◯ <sup>99m</sup>TcO<sub>4</sub><sup>－</sup>'
        '（過テクネチウム酸イオン）は胃粘膜と唾液腺に集積する</span>。'
        '<span class="kw3">したがって「胃以外の場所に'
        '限局した集積があれば異所性胃粘膜がある」ことになり、'
        'それはすなわちMeckel憩室である</span>。'
        '<span class="kw3">Meckel憩室は卵黄腸管（臍腸管）の遺残による'
        '真性憩室で、回腸末端の腸間膜対側にできる</span>。'
        '<span class="kw3">「2の法則」——人口の約2%、'
        '回盲弁から約2フィート（60cm）、長さ約2インチ（5cm）、'
        '症状が出るのは2歳までが多く、'
        '異所性組織は胃粘膜と膵組織の2種類</span>。'
        '<span class="kw3">異所性胃粘膜が酸を分泌して隣接する'
        '回腸粘膜に潰瘍を作れば無痛性の下血、'
        '憩室が先進部になれば腸重積を起こす</span>——'
        '<span class="kw3">本例はまさに腸重積（target sign）で発症し、'
        '整復後に原因を探してシンチを撮ったという流れ</span>である。'),
       ('c', '悪性リンパ腫', False,
        '<span class="kw4">小児の腸重積の器質的原因としては'
        'Burkittリンパ腫などがありうる</span>が、'
        '<span class="kw4"><sup>99m</sup>TcO<sub>4</sub><sup>－</sup>には'
        '集積しない</span>。'
        '<span class="kw">リンパ腫の検索に用いるのはFDG-PETやCT</span>。'),
       ('d', '腸回転異常症', False,
        '<span class="kw4">腸回転異常症は胎生期の中腸の回転・固定の異常</span>で、'
        '<span class="kw4">多くは新生児期に中腸軸捻転による'
        '胆汁性嘔吐で発症する</span>。'
        '<span class="kw">診断は上部消化管造影（Treitz靱帯の位置異常）や'
        '超音波（SMA/SMVのwhirlpool sign）</span>で、'
        '<span class="kw4">シンチグラムで診断する疾患ではない</span>。'),
       ('e', '大腸ポリポーシス', False,
        '<span class="kw4">Peutz-Jeghers症候群のような'
        '過誤腫性ポリポーシスは小児の腸重積の原因になりうる</span>が、'
        '<span class="kw4">やはり<sup>99m</sup>TcO<sub>4</sub><sup>－</sup>には'
        '集積しない</span>。'
        '<span class="kw">診断は内視鏡と口唇・口腔粘膜の色素斑</span>。')],
      '99mTcO4-は胃粘膜に集積する。異所性の集積＝Meckel憩室。',
      imgs=[IMG + '118D-66_1.jpeg'],
      ans_label='ｂ　Meckel 憩室',
      patho=('🔎 画像所見——上腹部（胃）の強い集積のほかに、下腹部にもう1つの集積',
             '<span class="kw3">シンチグラムでは、上腹部に'
             '<sup>99m</sup>TcO<sub>4</sub><sup>－</sup>の'
             '強い集積（＝胃、生理的集積）を認める</span>。'
             '<span class="kw3">それとは別に、下腹部（骨盤に近い高さ）に'
             '限局した異常集積がもう1か所ある</span>——'
             '<span class="kw3">これが異所性胃粘膜＝Meckel憩室である</span>。'
             '<table class="tb"><tr><th>集積部位</th><th>意味</th></tr>'
             '<tr><td><span class="kw3">胃</span></td>'
             '<td><span class="kw3">生理的集積（胃粘膜の壁細胞に取り込まれる）</span></td></tr>'
             '<tr><td><span class="kw">唾液腺・甲状腺</span></td>'
             '<td><span class="kw">生理的集積'
             '（<sup>99m</sup>TcO<sub>4</sub><sup>－</sup>はヨードと同様に'
             'Na/I symporterで取り込まれる）</span></td></tr>'
             '<tr><td><span class="kw">膀　胱</span></td>'
             '<td><span class="kw">排泄による集積</span></td></tr>'
             '<tr><td><span class="kw3">上記以外の腹部の限局集積</span></td>'
             '<td><span class="kw3">異所性胃粘膜＝Meckel憩室</span></td></tr>'
             '<tr><td colspan="2"><span class="kw3">読影の要点は'
             '「生理的集積の場所を知っていること」</span>——'
             '<span class="kw3">核医学では'
             '「正常でも光る場所」を覚えておかないと'
             '異常が拾えない</span>。'
             '<span class="kw">FDG-PETで脳と尿路が光るのと同じ理屈'
             '（NO.7e）</span>。</td></tr></table>'),
      deep=('💡 小児の腸重積——年齢で「特発性か、器質的原因があるか」が変わる',
            '<span class="kw3">本例の要点は'
            '「9歳の腸重積」という年齢である</span>。'
            '<table class="tb"><tr><th></th>'
            '<th><span class="kw3">乳幼児（生後3か月〜2歳）</span></th>'
            '<th><span class="kw3">年長児・成人</span></th></tr>'
            '<tr><td>原因</td>'
            '<td><span class="kw3">特発性が大半</span>'
            '（<span class="kw">Peyer板のリンパ組織が'
            'ウイルス感染で腫れて先進部になる</span>）</td>'
            '<td><span class="kw3">器質的な先進部〈lead point〉を'
            '疑う</span>——'
            '<span class="kw3">Meckel憩室・ポリープ・'
            'リンパ腫・重複腸管・IgA血管炎の腸管壁血腫</span></td></tr>'
            '<tr><td>診断</td>'
            '<td colspan="2"><span class="kw3">腹部超音波で'
            'target sign（同心円状の層構造）・'
            'pseudokidney sign</span></td></tr>'
            '<tr><td>治療</td>'
            '<td colspan="2"><span class="kw3">まず非観血的整復'
            '（空気／造影剤による注腸整復）</span>。'
            '<span class="kw4">腹膜炎・穿孔・ショックがあれば'
            '整復せず手術</span></td></tr>'
            '<tr><td>整復後</td>'
            '<td>経過観察</td>'
            '<td><span class="kw3">先進部の検索'
            '（<sup>99m</sup>TcO<sub>4</sub><sup>－</sup>シンチ・'
            'CT・内視鏡）</span></td></tr></table>'
            '<span class="kw3">「9歳＝特発性では説明しにくい年齢だから'
            '整復後に原因を探した」</span>という文脈が読めれば、'
            '<span class="kw3">シンチを撮った意図＝Meckel憩室を探している、'
            'と分かる</span>。'
            '<span class="kw">なお三主徴（間欠的腹痛・嘔吐・血便）が'
            'そろうのは半数以下</span>で、'
            '<span class="kw">本例も血便の記載はない</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3"><sup>99m</sup>TcO<sub>4</sub><sup>－</sup>'
             'シンチ＝異所性胃粘膜＝Meckel憩室の検索</span>。<br>'
             '② <span class="kw3">生理的集積は胃・唾液腺・甲状腺・膀胱</span>。<br>'
             '③ <span class="kw3">Meckel憩室の2の法則＝人口の2%・'
             '回盲弁から2フィート・長さ2インチ・2歳までに発症・'
             '異所性組織は胃粘膜と膵組織の2種</span>。<br>'
             '④ <span class="kw3">年長児の腸重積は器質的な先進部を疑う</span>'
             '（Meckel憩室・ポリープ・リンパ腫）。<br>'
             '⑤ <span class="kw">腸重積は超音波のtarget sign → '
             '非観血的整復（腹膜炎があれば手術）</span>。')),

]
