
QUESTIONS += [

    # ── NO.13 (120A-16) ★ 90% ans=b ────────────────────────────
    Q('120A-16', 90, [('bs', '★')],
      '69 歳の男性。転びやすいことを主訴に来院した。'
      '10 年前から糖尿病でインスリン療法を行っている。'
      '<span class="kw">3 年前から歩行時に前のめりになり転倒することが頻回になり、'
      '5 か月前に左上腕骨を骨折した。</span>診察時、表情は乏しく、やや小声であった。'
      '<span class="kw">眼球運動は上下方向に制限があり、'
      '筋強剛は頸部に強く認めたが四肢では軽かった。</span>'
      '四肢の腱反射は正常で、Babinski 徴候を認めない。便秘もない。'
      '<span class="kw">レボドパ〈L-dopa〉の内服による治療効果は認められなかった。</span>'
      '頭部単純MRI のT<sub>1</sub>強調像（A）と'
      'ドパミントランスポーターSPECT（B）とを示す。<br>'
      '<strong>最も考えられる疾患はどれか。</strong>',
      [('a', 'Parkinson 病', False,
        '<span class="kw4">Parkinson病なら①L-dopaがよく効く '
        '②症状が左右非対称に始まる ③安静時振戦が目立つ '
        '④筋強剛は四肢優位 ⑤便秘などの自律神経症状を伴う</span>のが典型。'
        '<span class="kw4">本例はいずれとも合わない</span>——'
        '<span class="kw4">とくに「L-dopa無効」「頸部優位の筋強剛」'
        '「便秘もない」は積極的に否定する記載</span>である。'
        '<span class="kw">Parkinson病では転倒（姿勢反射障害）が'
        '出るのも病期が進んでから</span>で、'
        '<span class="kw">発症早期からの易転倒は非典型</span>。'),
       ('b', '進行性核上性麻痺', True,
        '<span class="kw3">◯ 進行性核上性麻痺〈PSP〉</span>。'
        '<span class="kw3">診断の柱は4つで、本例はすべて満たす</span>——'
        '<span class="kw3">①発症早期からの易転倒（後方への転倒が典型）'
        '②垂直性核上性眼球運動障害（とくに下方視の制限）'
        '③体軸（頸部・体幹）優位の筋強剛＝四肢より頸部が硬い'
        '④L-dopaが無効</span>。'
        '<span class="kw3">「核上性」とは、眼球運動の障害が'
        '眼筋や動眼神経ではなく、その上位の中枢（中脳の垂直注視中枢）に'
        'あることを意味する</span>——'
        '<span class="kw">だから人形の目現象（頭位変換眼球反射）では'
        '眼球が動く</span>。'
        '<span class="kw3">画像では中脳被蓋の萎縮</span>'
        '（<span class="kw3">正中矢状断のhummingbird sign、'
        '水平断のmorning glory sign</span>）。'),
       ('c', '筋萎縮性側索硬化症', False,
        '<span class="kw4">ALSは上位・下位運動ニューロンがともに障害される疾患</span>で、'
        '<span class="kw4">筋萎縮・線維束性収縮・腱反射亢進・'
        'Babinski徴候陽性・球麻痺</span>がみられる。'
        '<span class="kw4">本例は腱反射正常・Babinski徴候陰性で、'
        '筋萎縮の記載もない</span>。'
        '<span class="kw">また眼球運動はALSでは末期まで保たれる</span>。'),
       ('d', '特発性正常圧水頭症', False,
        '<span class="kw4">iNPHの三徴は歩行障害・認知機能障害・尿失禁</span>で、'
        '<span class="kw4">歩行は「小刻み・すり足・開脚性（磁性歩行）」</span>。'
        '<span class="kw4">眼球運動障害は来さない</span>。'
        '<span class="kw">画像では脳室拡大とDESH'
        '（高位円蓋部・正中部の脳溝狭小化＋Sylvius裂の開大）</span>が特徴で、'
        '<span class="kw4">本例のT<sub>1</sub>強調像には脳室拡大がない</span>。'),
       ('e', '血管性Parkinson 症候群', False,
        '<span class="kw4">血管性パーキンソニズムは'
        '基底核・白質の多発性ラクナ梗塞によるもの</span>で、'
        '<span class="kw4">下半身優位のパーキンソニズム（lower body parkinsonism）・'
        '錐体路徴候（腱反射亢進・Babinski徴候陽性）・'
        '階段状の経過</span>を伴う。'
        '<span class="kw4">本例は腱反射正常・Babinski徴候陰性</span>で、'
        '<span class="kw4">画像にも多発梗塞の所見がない</span>。'
        '<span class="kw">糖尿病の既往が10年あるので'
        'これを疑わせる作りにはなっているが、所見が伴わない</span>。')],
      '易転倒・垂直性眼球運動障害・頸部優位の筋強剛・L-dopa無効＝進行性核上性麻痺。',
      imgs=[IMG + '120A-16_1.jpeg', IMG + '120A-16_2.jpeg'],
      patho=('🔎 画像所見——中脳被蓋の萎縮と、線条体DATの両側性低下',
             '<span class="kw3">A（頭部単純MRI T<sub>1</sub>強調像・水平断）は'
             '中脳の高さのスライスで、中脳被蓋が萎縮して'
             '外側縁が凹み、いわゆるmorning glory sign'
             '（朝顔の花のような輪郭）を呈する</span>。'
             '<span class="kw3">正中矢状断で撮れば'
             '中脳被蓋の上縁が凹んだhummingbird sign（ハチドリ徴候）'
             'として見える所見と同じもの</span>である。<br>'
             '<span class="kw3">B（ドパミントランスポーターSPECT＝DaTスキャン）では'
             '両側線条体の集積を評価する</span>。'
             '<span class="kw3">PSPでは集積が低下するが、'
             'Parkinson病と違って<u>左右差に乏しい両側性の低下</u>を示す</span>のが特徴。'
             '<table class="tb"><tr><th>疾患</th>'
             '<th><span class="kw3">DaTスキャン<br>（線条体の集積）</span></th>'
             '<th><span class="kw3">MIBG心筋シンチ</span></th>'
             '<th>決め手になる臨床所見</th></tr>'
             '<tr><td><span class="kw3">Parkinson病</span></td>'
             '<td><span class="kw3">低下（左右差あり・被殻後部から）</span></td>'
             '<td><span class="kw3">低下</span></td>'
             '<td><span class="kw">安静時振戦・左右差・L-dopa著効・便秘</span></td></tr>'
             '<tr><td><span class="kw3">Lewy小体型認知症</span></td>'
             '<td><span class="kw3">低下</span></td>'
             '<td><span class="kw3">低下</span></td>'
             '<td><span class="kw">具体的な幻視・認知の変動・REM睡眠行動障害</span></td></tr>'
             '<tr><td><span class="kw3">進行性核上性麻痺</span></td>'
             '<td><span class="kw3">低下（左右差に乏しい）</span></td>'
             '<td><span class="kw3">正常〜軽度低下</span></td>'
             '<td><span class="kw3">垂直性眼球運動障害・易転倒・'
             '頸部優位の筋強剛・L-dopa無効</span></td></tr>'
             '<tr><td><span class="kw">多系統萎縮症</span></td>'
             '<td><span class="kw">低下（左右差に乏しい）</span></td>'
             '<td><span class="kw">正常〜軽度低下</span></td>'
             '<td><span class="kw">起立性低血圧・排尿障害・小脳失調・'
             '錐体路徴候</span></td></tr>'
             '<tr><td><span class="kw4">Alzheimer型認知症<br>'
             '本態性振戦<br>薬剤性パーキンソニズム</span></td>'
             '<td><span class="kw4">正常</span></td>'
             '<td><span class="kw">正常（Alzheimer型）</span></td>'
             '<td>—</td></tr>'
             '<tr><td colspan="4"><span class="kw3">DaTスキャンは'
             '「変性性パーキンソニズムか、そうでないか」を分けるが、'
             '変性性のなかの鑑別はできない</span>。'
             '<span class="kw3">MIBG心筋シンチを組み合わせると'
             '「Parkinson病／Lewy小体型（低下）」と'
             '「PSP／MSA（正常〜軽度低下）」が分かれる</span>。</td></tr></table>'),
      deep=('💡 パーキンソニズムの鑑別——「L-dopaが効かない」がまず入口',
            '<span class="kw3">パーキンソニズム（無動・筋強剛・振戦・'
            '姿勢反射障害）を見たら、まずParkinson病かどうかを'
            'L-dopaの反応で分ける</span>。'
            '<table class="tb"><tr><th></th><th>Parkinson病</th>'
            '<th><span class="kw3">Parkinson症候群（非定型）</span></th></tr>'
            '<tr><td><span class="kw3">L-dopaの効果</span></td>'
            '<td><span class="kw3">著効する</span></td>'
            '<td><span class="kw3">効かない／効果が乏しい</span></td></tr>'
            '<tr><td>左右差</td><td><span class="kw">あり（片側から始まる）</span></td>'
            '<td><span class="kw">乏しい</span></td></tr>'
            '<tr><td>安静時振戦</td><td><span class="kw">目立つ</span></td>'
            '<td>乏しい</td></tr>'
            '<tr><td>姿勢反射障害（転倒）</td>'
            '<td>病期が進んでから</td>'
            '<td><span class="kw3">早期から（とくにPSP）</span></td></tr>'
            '<tr><td>その他の徴候</td>'
            '<td><span class="kw">嗅覚低下・便秘・REM睡眠行動障害</span></td>'
            '<td><span class="kw3">PSP＝垂直性眼球運動障害／'
            'MSA＝自律神経障害・小脳失調／'
            'CBD＝著明な左右差・肢節運動失行・他人の手徴候</span></td></tr></table>'
            '<span class="kw3">本例が「レボドパの内服による治療効果は認められなかった」と'
            'わざわざ書いているのは、'
            'この最初の分岐を通させるため</span>である。'
            '<span class="kw4">PSPには根本的な治療がなく、'
            '転倒による外傷（本例は上腕骨骨折）と'
            '嚥下障害・誤嚥が予後を規定する</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">PSP＝早期からの易転倒・垂直性核上性眼球運動障害'
             '（下方視の制限）・頸部優位の筋強剛・L-dopa無効</span>。<br>'
             '② <span class="kw3">画像は中脳被蓋の萎縮'
             '（矢状断hummingbird sign／水平断morning glory sign）</span>。<br>'
             '③ <span class="kw3">DaTスキャン＝変性性パーキンソニズムで低下、'
             'Alzheimer型・本態性振戦・薬剤性では正常</span>。<br>'
             '④ <span class="kw3">MIBG心筋シンチ＝Parkinson病・'
             'Lewy小体型で低下、PSP・MSAでは保たれる</span>。<br>'
             '⑤ <span class="kw">L-dopaが効かないパーキンソニズムを見たら'
             'PSP・MSA・CBD・血管性・薬剤性を考える</span>。')),

    # ── NO.14 (オリジナル) ★ rate=None ans=a,e ──────────────────
    Q('オリジナル', None, [('bs', '★')],
      '<strong>子宮体癌の原発巣評価に適した検査はどれか。2つ選べ。</strong>',
      [('a', 'MRI', True,
        '<span class="kw3">◯ 子宮体癌の原発巣評価（局所進展の評価）の主役はMRI</span>。'
        '<span class="kw3">T<sub>2</sub>強調像で子宮内膜・接合帯〈junctional zone〉・'
        '筋層のコントラストが明瞭につくため、'
        '<u>筋層浸潤が1/2を超えるか</u>、頸部間質へ及ぶか、'
        '子宮外へ出ているかを高い精度で判定できる</span>。'
        '<span class="kw3">筋層浸潤の深さは子宮体癌の進行期分類と'
        'リンパ節転移のリスクを直接決める</span>ので、'
        '<span class="kw3">術式（リンパ節郭清を行うか）の決定に直結する</span>。'
        '<span class="kw">拡散強調像と造影を組み合わせるとさらに精度が上がる</span>。'),
       ('b', 'CT', False,
        '<span class="kw4">CTは子宮内のコントラストがつきにくい</span>——'
        '<span class="kw4">子宮内膜も筋層も腫瘍も、'
        'CT値がほとんど同じ軟部組織だから</span>。'
        '<span class="kw3">CTが担うのは原発巣ではなく'
        '「遠隔転移とリンパ節転移の検索」</span>で、'
        '<span class="kw3">広い範囲を短時間に死角なく撮れる点で'
        'MRIより優れる</span>。'
        '<span class="kw3">「局所はMRI、全身はCT」という役割分担</span>。'),
       ('c', 'FDG-PET', False,
        '<span class="kw4">FDG-PETは遠隔転移・再発の検索には有用だが、'
        '原発巣の局所進展評価には向かない</span>。'
        '<span class="kw4">空間分解能が低く、筋層浸潤が1/2を超えるか'
        'といったミリ単位の判定はできない</span>。'
        '<span class="kw4">加えて尿路への生理的集積が骨盤内の読影を妨げる</span>し、'
        '<span class="kw">正常子宮内膜も月経周期に応じて生理的に集積する</span>。'),
       ('d', 'エックス線', False,
        '<span class="kw4">単純エックス線写真は軟部組織のコントラストがつかず、'
        '骨盤内臓器の評価にはまったく使えない</span>。'
        '<span class="kw">骨転移の評価に用いることはあるが、'
        '原発巣の評価とは無関係</span>。'),
       ('e', '経腟超音波', True,
        '<span class="kw3">◯ 経腟超音波は子宮体癌の入口の検査</span>。'
        '<span class="kw3">高周波プローブを腟から子宮のすぐ近くに'
        '当てられるので分解能が高く、'
        '子宮内膜の厚さ（閉経後で5mmを超えれば精査）と'
        '内腔の性状、筋層浸潤の有無を評価できる</span>。'
        '<span class="kw3">被ばくがなく、外来でその場で行え、'
        '安価で繰り返せる</span>——'
        '<span class="kw3">不正性器出血を主訴とする患者への'
        '最初のスクリーニングとして必須</span>である。'
        '<span class="kw">（確定診断は子宮内膜組織診）</span>')],
      '局所（筋層浸潤）はMRIと経腟超音波、全身検索はCT。CT・PETは子宮内が見えない。',
      ans_label='ａ・ｅ',
      patho=('🔎 「原発巣の評価」と「転移の検索」でモダリティが分かれる',
             '<span class="kw3">悪性腫瘍の画像検査は、'
             '「①原発巣がどこまで広がっているか（局所進展）」と'
             '「②遠くへ飛んでいないか（転移）」の2つに分かれる</span>。'
             '<span class="kw3">求められる性能が違うので、使う装置も違う</span>。'
             '<table class="tb"><tr><th></th>'
             '<th><span class="kw3">原発巣の局所進展</span></th>'
             '<th><span class="kw3">転移の検索</span></th></tr>'
             '<tr><td>求められる性能</td>'
             '<td><span class="kw3">軟部組織のコントラストと空間分解能'
             '（数mmの浸潤を見分ける）</span></td>'
             '<td><span class="kw3">広い範囲を死角なく短時間で</span></td></tr>'
             '<tr><td>骨盤内臓器<br>（子宮・前立腺・直腸）</td>'
             '<td><span class="kw3">MRI</span>'
             '（＋<span class="kw3">経腟／経直腸超音波</span>）</td>'
             '<td><span class="kw3">造影CT</span>（＋PET-CT）</td></tr>'
             '<tr><td>理由</td>'
             '<td><span class="kw3">CTでは子宮筋層と内膜と腫瘍の'
             'CT値がほぼ同じで区別できない</span>。'
             '<span class="kw3">MRIのT<sub>2</sub>強調像なら層構造が見える</span></td>'
             '<td><span class="kw3">MRIは撮像に時間がかかり'
             '全身を撮るのに向かない</span></td></tr></table>'
             '<span class="kw3">この「局所はMRI、全身はCT」という原則は'
             '前立腺癌・直腸癌・子宮頸癌でも同じ</span>。'),
      deep=('💡 MRIが骨盤内で強いのはなぜか——T2強調像の層構造',
            '<span class="kw3">MRIのT<sub>2</sub>強調像では'
            '「水を多く含むほど白い」ため、'
            '子宮が3層に描き分けられる</span>。'
            '<table class="tb"><tr><th>層</th><th>T<sub>2</sub>強調像</th>'
            '<th>意味</th></tr>'
            '<tr><td><span class="kw3">子宮内膜</span></td>'
            '<td><span class="kw3">高信号（白）</span></td>'
            '<td>腺と分泌液に富む</td></tr>'
            '<tr><td><span class="kw3">接合帯〈junctional zone〉</span></td>'
            '<td><span class="kw3">低信号（黒い帯）</span></td>'
            '<td><span class="kw3">筋層の内側1/3。'
            '<u>この帯が保たれていれば筋層浸潤なし</u></span></td></tr>'
            '<tr><td><span class="kw3">子宮筋層</span></td>'
            '<td><span class="kw">中等度信号</span></td>'
            '<td>—</td></tr>'
            '<tr><td colspan="3"><span class="kw3">子宮体癌は'
            'T<sub>2</sub>強調像で内膜より低〜中等度の信号を示す腫瘤として現れ、'
            '接合帯の断裂・消失で筋層浸潤を判定する</span>。<br>'
            '<span class="kw3">筋層浸潤が1/2以上（深部浸潤）だと'
            'リンパ節転移のリスクが跳ね上がる</span>ので、'
            'この一点が術式を決める。</td></tr></table>'
            '<span class="kw">同じ原理で、MRIは子宮筋腫・子宮腺筋症・'
            '卵巣腫瘍（脂肪抑制で成熟囊胞性奇形腫の脂肪を証明する）にも強い</span>。'
            '<span class="kw">前立腺癌でも同様に'
            'T<sub>2</sub>強調像＋拡散強調像で辺縁領域の癌を拾う</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">子宮体癌の原発巣（筋層浸潤）評価＝'
             'MRIと経腟超音波</span>。<br>'
             '② <span class="kw3">CT・FDG-PETは遠隔転移とリンパ節転移の検索</span>——'
             '<span class="kw4">子宮内のコントラストがつかない</span>。<br>'
             '③ <span class="kw3">MRIのT<sub>2</sub>強調像で'
             '内膜（高信号）・接合帯（低信号）・筋層が描き分けられる</span>。<br>'
             '④ <span class="kw">閉経後で子宮内膜厚5mm超なら精査</span>。'
             '<span class="kw">確定診断は子宮内膜組織診</span>。<br>'
             '⑤ <span class="kw3">「局所はMRI、全身はCT」</span>。')),

    # ── NO.15 (117D-48) ★ 27% ans=a,c ──────────────────────────
    Q('117D-48', 27, [('bs', '★')],
      '80 歳の女性。左上下肢の脱力を主訴に救急車で搬入された。'
      '<span class="kw">本日午前6 時に起床したときから、'
      '左上下肢の脱力としゃべりにくさを自覚していたが、様子をみていた。'
      '夕方、左上下肢の麻痺が増悪したため救急車を要請した。</span>'
      '高血圧症と糖尿病で治療中である。日常生活動作は自立しており、'
      '<span class="kw">脳血管障害の既往や不整脈の指摘はない。</span>'
      '意識は清明。心拍数82/ 分、整。血圧154/82mmHg。'
      '復唱は可能だが構音障害を認める。左顔面を含む左上下肢の不全片麻痺を認めた。'
      '来院時の頭部MRI の拡散強調像（A）、FLAIR 像（B）及びMRA（C）を示す。<br>'
      '<strong>直ちに行うべき治療で適切なのはどれか。2つ選べ。</strong>',
      [('a', '抗血小板薬内服', True,
        '<span class="kw3">◯ 非心原性（アテローム血栓性・ラクナ）の'
        '急性期脳梗塞に対する標準治療</span>。'
        '<span class="kw3">発症48時間以内であれば'
        'アスピリン160〜300mg／日の投与が推奨され、'
        '死亡・再発を減らすことが示されている</span>。'
        '<span class="kw3">本例は不整脈の指摘がなく心拍数82/分・整、'
        'MRAに主幹動脈の閉塞がなく、'
        '拡散強調像の病変も穿通枝領域に限局している</span>——'
        '<span class="kw3">＝非心原性脳梗塞として矛盾しない</span>ので'
        '抗血小板薬が適応になる。'),
       ('b', '機械的血栓回収療法', False,
        '<span class="kw4">機械的血栓回収療法の適応は'
        '「主幹動脈（内頸動脈・中大脳動脈M1など）の閉塞」があること</span>。'
        '<span class="kw4">本例のMRA（C）では内頸動脈・中大脳動脈・'
        '前大脳動脈がいずれも良好に描出されており、'
        '取り除くべき血栓が存在しない</span>。'
        '<span class="kw4">加えて最終健常時刻が不明で'
        '発症から時間が経っている</span>。'
        '<span class="kw3">「病巣が穿通枝領域＝細い枝の梗塞」であることも'
        'カテーテルが届かない理由になる</span>。'),
       ('c', 'グリセオール静注療法', True,
        '<span class="kw3">◯ 高張グリセロール（グリセオール）は'
        '浸透圧利尿により脳浮腫を軽減する薬剤</span>で、'
        '<span class="kw3">急性期脳梗塞で脳浮腫による症状悪化が'
        '懸念される場合に投与される</span>。'
        '<span class="kw3">本例は「夕方に麻痺が増悪した」＝'
        '進行性の経過をたどっており、'
        '虚血周囲の浮腫が症状を悪化させている状況</span>と考えられる。'
        '<span class="kw">脳浮腫は発症後3〜5日でピークを迎える</span>ので、'
        '<span class="kw">急性期に抗浮腫療法を行う意義がある</span>。'),
       ('d', 't-PA〈tissue plasminogen activator〉静注療法', False,
        '<span class="kw4">t-PA静注療法の適応は'
        '「<u>発症（最終健常確認時刻）から4.5時間以内</u>」</span>。'
        '<span class="kw4">本例は午前6時に起床した時点ですでに症状があり、'
        '＝最終健常時刻は「前夜に眠った時刻」で不明</span>——'
        '<span class="kw4">いわゆるwake-up strokeで、'
        '発症時刻が特定できない</span>。'
        '<span class="kw4">しかも症状に気づいてから受診まで'
        '「様子をみて」夕方まで経過しており、'
        'どう見積もっても4.5時間を大きく超えている</span>。'
        '<span class="kw3">この設問の最大の分岐点で、正答率27%の主因</span>——'
        '<span class="kw3">「起床時に気づいた」という一文を'
        '「起床時に発症した」と読み替えてしまうと'
        'd を選んでしまう</span>。'
        '<span class="kw">（なお発症時刻不明例でも'
        'DWI-FLAILミスマッチがあればt-PAを考慮できるが、'
        '本例のFLAIR像にはすでに病変に対応する高信号があり'
        'ミスマッチとはいえない）</span>'),
       ('e', '直接経口抗凝固薬［direct oral anti coagulant〈DOAC〉］内服', False,
        '<span class="kw4">DOACの適応は心原性脳塞栓症'
        '（非弁膜症性心房細動を伴う）</span>だが、'
        '<span class="kw4">本例は「不整脈の指摘はない」「脈拍整」で'
        '心房細動を示唆する所見がない</span>。'
        '<span class="kw4">さらに急性期の梗塞巣に抗凝固薬を'
        '早期から入れると出血性梗塞のリスクがある</span>ため、'
        '<span class="kw4">心原性であっても梗塞巣の大きさに応じて'
        '開始時期を選ぶ（大きい梗塞ほど遅らせる）</span>。'
        '<span class="kw4">「直ちに行うべき治療」ではない</span>。')],
      '起床時に症状に気づいた＝最終健常時刻が不明でt-PA適応外。主幹動脈閉塞もない。',
      imgs=[IMG + '117D-48_1.jpeg', IMG + '117D-48_2.jpeg', IMG + '117D-48_3.jpeg'],
      patho=('🔎 画像所見——右穿通枝領域の新鮮梗塞、主幹動脈は開存',
             '<span class="kw3">A（拡散強調像）では、'
             '画像の左側＝患者の右側の大脳基底核〜放線冠にかけて'
             '斑状の高信号を認める</span>。'
             '<span class="kw3">左片麻痺という症候と一致する（右半球の病変）</span>。'
             '<span class="kw3">病変は皮質を広く含む楔状ではなく'
             '深部の穿通枝領域に限局している</span>——'
             '<span class="kw3">＝主幹動脈の閉塞による広範な梗塞ではない</span>。<br>'
             '<span class="kw3">B（FLAIR像）では脳室周囲に'
             '陳旧性の白質病変（慢性虚血性変化）が広がり、'
             '新鮮病巣に対応する部位にも高信号がみられる</span>。'
             '<span class="kw3">＝DWI-FLAILミスマッチは明らかでなく、'
             '発症から相当の時間が経過していることを支持する</span>。<br>'
             '<span class="kw3">C（MRA）では両側の内頸動脈・中大脳動脈・'
             '前大脳動脈がいずれも良好に描出され、'
             '主幹動脈の閉塞や高度狭窄を認めない</span>——'
             '<span class="kw3">＝機械的血栓回収療法の対象になる病変がない</span>。'
             '<table class="tb"><tr><th>画像</th><th>読み</th>'
             '<th>治療方針への意味</th></tr>'
             '<tr><td><span class="kw3">DWI（A）</span></td>'
             '<td><span class="kw3">右穿通枝領域の新鮮梗塞</span></td>'
             '<td><span class="kw3">脳梗塞であることの確定</span></td></tr>'
             '<tr><td><span class="kw3">FLAIR（B）</span></td>'
             '<td><span class="kw3">同部位にも高信号＋陳旧性白質病変</span></td>'
             '<td><span class="kw3">超急性期ではない'
             '＝t-PAの時間枠を外れている</span></td></tr>'
             '<tr><td><span class="kw3">MRA（C）</span></td>'
             '<td><span class="kw3">主幹動脈は開存</span></td>'
             '<td><span class="kw3">血栓回収の適応なし</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">3つの画像が'
             '「再開通療法は使えない」と'
             '3方向から示している</span>——'
             '<span class="kw3">残るのは抗血小板薬と抗浮腫療法</span>。</td></tr></table>'),
      deep=('💡 急性期脳梗塞の治療は「時間枠」と「閉塞部位」の2軸で決まる',
            '<table class="tb"><tr><th>治療</th><th>時間枠</th>'
            '<th>対象</th><th>本例</th></tr>'
            '<tr><td><span class="kw3">t-PA静注療法</span></td>'
            '<td><span class="kw3">発症4.5時間以内</span></td>'
            '<td>主幹動脈・末梢を問わない</td>'
            '<td><span class="kw4">×（最終健常時刻不明・時間超過）</span></td></tr>'
            '<tr><td><span class="kw3">機械的血栓回収療法</span></td>'
            '<td><span class="kw3">発症6時間以内（画像で'
            'ミスマッチがあれば最大24時間まで）</span></td>'
            '<td><span class="kw3">主幹動脈閉塞（ICA・MCA M1など）</span></td>'
            '<td><span class="kw4">×（主幹動脈が開存）</span></td></tr>'
            '<tr><td><span class="kw3">抗血小板薬</span></td>'
            '<td><span class="kw3">発症48時間以内</span></td>'
            '<td><span class="kw3">非心原性（アテローム血栓性・ラクナ）</span></td>'
            '<td><span class="kw3">◯</span></td></tr>'
            '<tr><td><span class="kw">抗凝固薬</span></td>'
            '<td><span class="kw">梗塞巣の大きさに応じて</span></td>'
            '<td><span class="kw">心原性脳塞栓症（心房細動）</span></td>'
            '<td><span class="kw4">×（心房細動なし）</span></td></tr>'
            '<tr><td><span class="kw3">抗浮腫療法'
            '（グリセロール・D-マンニトール）</span></td>'
            '<td><span class="kw3">脳浮腫による悪化が懸念されるとき</span></td>'
            '<td>—</td><td><span class="kw3">◯（夕方に麻痺が増悪）</span></td></tr>'
            '<tr><td><span class="kw">エダラボン</span></td>'
            '<td><span class="kw">発症24時間以内</span></td>'
            '<td>脳保護（フリーラジカル消去）</td><td>◯</td></tr></table>'
            '<span class="kw3">⚠️ 起床時に症状を自覚した脳卒中'
            '〈wake-up stroke〉では、'
            '最終健常時刻は「就寝時刻」になる</span>——'
            '<span class="kw3">「起きたときに気づいた」は'
            '「起きたときに発症した」ではない</span>。'
            '<span class="kw3">脳梗塞全体の1〜2割を占め、'
            '本来は再開通療法の恩恵を受けられたはずの患者が'
            '時間枠から漏れる大きな原因になっている</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">t-PA静注療法は発症（最終健常時刻）から'
             '4.5時間以内</span>。'
             '<span class="kw3">起床時に気づいた場合の起点は就寝時刻</span>。<br>'
             '② <span class="kw3">機械的血栓回収療法は主幹動脈閉塞が'
             'あることが前提</span>。<br>'
             '③ <span class="kw3">非心原性の急性期脳梗塞には抗血小板薬'
             '（発症48時間以内のアスピリン）</span>。<br>'
             '④ <span class="kw3">DWI-FLAIRミスマッチ＝発症4.5時間以内を示唆</span>'
             '——発症時刻不明例の判断材料。<br>'
             '⑤ <span class="kw4">心房細動がなければDOACの適応ではない</span>。'
             '<span class="kw">急性期の抗凝固は出血性梗塞に注意</span>。')),

    # ── NO.16 (オリジナル) ★ rate=None ans=c ────────────────────
    Q('オリジナル', None, [('bs', '★')],
      'MRI の拡散強調像（A）、FLAIR 像（B）、MRA（C）を示す。<br>'
      '<strong><u>誤っている</u>のはどれか。</strong>',
      [('a', '拡散強調像で両側小脳半球に異常を認める。', False,
        '<span class="kw3">正しい。</span>'
        '<span class="kw3">A（拡散強調像）では、'
        'スライス下方の両側小脳半球に一致して高信号を認める</span>。'
        '<span class="kw3">拡散強調像は細胞性浮腫で水分子の拡散が'
        '制限された部位を高信号として描出する</span>ので、'
        '<span class="kw3">これは新鮮な虚血病巣を意味する</span>。'
        '<span class="kw">CTでは後頭蓋窩は骨によるアーチファクトで'
        '極めて見にくい（＝CTの苦手分野）</span>ため、'
        '<span class="kw">小脳・脳幹の病変はMRIでこそ拾える</span>。'),
       ('b', 'FLAIR 像は正常である。', False,
        '<span class="kw3">正しい。</span>'
        '<span class="kw3">B（FLAIR像）では、拡散強調像で高信号を示した'
        '小脳に対応する高信号を認めない</span>。'
        '<span class="kw3">＝DWI陽性・FLAIR陰性の「DWI-FLAIRミスマッチ」</span>で、'
        '<span class="kw3">発症からおよそ4.5時間以内の'
        '超急性期であることを示唆する</span>。'
        '<span class="kw3">この所見こそが d・e の根拠になっている</span>。'),
       ('c', 'MRA は正常である。', True,
        '<span class="kw3">◯ これが誤り。C（MRA）では'
        '両側内頸動脈と中大脳動脈は良好に描出されているが、'
        '<u>正中を上行するはずの椎骨脳底動脈系が描出されていない</u></span>。'
        '<span class="kw3">後大脳動脈も追えず、'
        '＝椎骨脳底動脈系の閉塞を示す所見である</span>。'
        '<span class="kw3">両側小脳半球という左右にまたがる梗塞は、'
        '正中を1本で上行する脳底動脈が詰まったと考えれば'
        '一元的に説明できる</span>——'
        '<span class="kw3">「両側性の後方循環の梗塞をみたら脳底動脈を疑う」</span>。'
        '<span class="kw4">脳底動脈閉塞症は致死率の高い病態</span>で、'
        '<span class="kw3">再開通療法（t-PA・機械的血栓回収）の'
        '緊急適応になる</span>。'),
       ('d', '超急性期脳梗塞を疑う。', False,
        '<span class="kw3">正しい。</span>'
        '<span class="kw3">DWIで高信号なのにFLAIRではまだ変化がない'
        '＝DWI-FLAIRミスマッチ</span>は、'
        '<span class="kw3">発症から4.5時間以内の超急性期を示唆する</span>。'
        '<span class="kw">FLAIRで高信号になるのは血管性浮腫が生じてからで、'
        '通常は発症数時間を要する</span>。'),
       ('e', 't-PA 療法を考慮する。', False,
        '<span class="kw3">正しい。</span>'
        '<span class="kw3">超急性期であり、かつMRAで'
        '脳底動脈系の閉塞が示されている</span>ので、'
        '<span class="kw3">禁忌がなければt-PA静注療法'
        '（および機械的血栓回収療法）の適応を検討する</span>。'
        '<span class="kw3">脳底動脈閉塞は無治療なら予後がきわめて不良</span>なので、'
        '<span class="kw3">積極的に再開通を目指す</span>。')],
      'DWI陽性＋FLAIR陰性＝超急性期。MRAで椎骨脳底動脈系が描出されず＝閉塞。',
      imgs=[IMG + 'orig16_1.jpeg', IMG + 'orig16_2.jpeg', IMG + 'orig16_3.jpeg'],
      ans_label='ｃ　MRA は正常である。',
      patho=('🔎 3つのシーケンスを「順に読む」——何が写り、何が写らないか',
             '<span class="kw3">同じ患者を3通りの撮り方で見ると、'
             'それぞれ別の情報が得られる</span>。'
             '<span class="kw3">本問はその読み分けそのものを問うている</span>。'
             '<table class="tb"><tr><th>画像</th><th>本例の所見</th>'
             '<th>そこから言えること</th></tr>'
             '<tr><td><span class="kw3">A：拡散強調像〈DWI〉</span></td>'
             '<td><span class="kw3">両側小脳半球に高信号</span></td>'
             '<td><span class="kw3">新鮮な虚血病巣がある（発症直後から陽性）</span></td></tr>'
             '<tr><td><span class="kw3">B：FLAIR像</span></td>'
             '<td><span class="kw3">対応する高信号なし（正常）</span></td>'
             '<td><span class="kw3">まだ血管性浮腫に至っていない'
             '＝発症4.5時間以内の超急性期</span></td></tr>'
             '<tr><td><span class="kw3">C：MRA</span></td>'
             '<td><span class="kw3">内頸動脈系は良好だが、'
             '正中の椎骨脳底動脈系が描出されない</span></td>'
             '<td><span class="kw3">脳底動脈系の閉塞'
             '＝両側小脳梗塞の原因</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">「病巣はどこか（DWI）」'
             '「いつからか（FLAIRとの対比）」'
             '「なぜか（MRA）」の3つが1組で揃う</span>のが'
             'MRIの強みで、<span class="kw3">この3点が揃えば'
             '治療方針（再開通療法をやるか）が決まる</span>。</td></tr></table>'
             + TBL_MRI),
      deep=('💡 後方循環（椎骨脳底動脈系）の梗塞——「両側性」がサイン',
            '<span class="kw3">脳梗塞は原則として片側の症状を出すが、'
            '後方循環では両側性の所見が出ることがある</span>——'
            '<span class="kw3">正中を1本で上行する脳底動脈が'
            '左右の小脳・脳幹・後頭葉を養っているから</span>である。'
            '<table class="tb"><tr><th></th>'
            '<th>前方循環（内頸動脈系）</th>'
            '<th><span class="kw3">後方循環（椎骨脳底動脈系）</span></th></tr>'
            '<tr><td>灌流域</td><td>大脳半球の大部分</td>'
            '<td><span class="kw3">脳幹・小脳・後頭葉・視床</span></td></tr>'
            '<tr><td>症状</td>'
            '<td><span class="kw">片麻痺・失語・半側空間無視</span></td>'
            '<td><span class="kw3">めまい・複視・構音障害・嚥下障害・'
            '失調・視野障害・意識障害</span>。'
            '<span class="kw3">交代性片麻痺（同側の脳神経麻痺＋'
            '対側の片麻痺）</span></td></tr>'
            '<tr><td>両側性</td><td>まれ</td>'
            '<td><span class="kw3">起こりうる（脳底動脈は1本）</span></td></tr>'
            '<tr><td><span class="kw4">CTでの見え方</span></td>'
            '<td>比較的見やすい</td>'
            '<td><span class="kw4">後頭蓋窩は骨のアーチファクトで'
            '極めて見にくい＝CTの苦手分野</span></td></tr>'
            '<tr><td><span class="kw3">検査</span></td>'
            '<td>CT／MRI</td>'
            '<td><span class="kw3">MRI（DWI）が必須</span></td></tr>'
            '<tr><td><span class="kw4">脳底動脈閉塞</span></td><td>—</td>'
            '<td><span class="kw4">意識障害・四肢麻痺・'
            '閉じ込め症候群。無治療なら死亡率が高い</span>——'
            '<span class="kw3">再開通療法の緊急適応</span></td></tr></table>'
            '<span class="kw3">「めまい・ふらつきで来た患者に'
            'CTだけ撮って異常なしと帰す」のが'
            '後方循環梗塞の典型的な見逃し方</span>で、'
            '<span class="kw3">CTが苦手な領域を知っていることが'
            'そのまま安全につながる</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">DWI陽性＋FLAIR陰性＝DWI-FLAIRミスマッチ'
             '＝発症4.5時間以内の超急性期</span>。<br>'
             '② <span class="kw3">両側小脳・脳幹の梗塞をみたら脳底動脈閉塞を疑う</span>。<br>'
             '③ <span class="kw3">MRAは造影剤なしで血管を描出できる</span>'
             '（flow voidを逆手に取る）。<br>'
             '④ <span class="kw4">後頭蓋窩はCTの苦手分野</span>——'
             '<span class="kw3">めまい・失調ではMRIを撮る</span>。<br>'
             '⑤ <span class="kw3">脳底動脈閉塞は予後不良で'
             '再開通療法（t-PA・血栓回収）の緊急適応</span>。')),

    # ── NO.17 (118B-7) ★CBT必修 92% ans=c ──────────────────────
    Q('118B-7', 92, [('bs', '★'), ('bc', 'CBT'), ('bh', '必修')],
      '<strong>膝関節MRI のT<sub>2</sub>強調像で筋肉より高信号になるのはどれか。</strong>',
      [('a', '腱', False,
        '<span class="kw4">腱は水分に乏しい緻密な膠原線維の束</span>で、'
        '<span class="kw4">T<sub>1</sub>強調像でもT<sub>2</sub>強調像でも低信号（黒）</span>。'
        '<span class="kw">膝でいえば膝蓋腱・大腿四頭筋腱</span>。'
        '<span class="kw3">断裂・炎症があると内部に水（浮腫）が入り込んで'
        'T<sub>2</sub>で高信号になる</span>ので、'
        '<span class="kw3">「本来黒いものが白くなっていたら病的」</span>という'
        '読み方をする。'),
       ('b', '靱　帯', False,
        '<span class="kw4">靱帯も腱と同じ膠原線維主体で、'
        'T<sub>2</sub>強調像で低信号</span>。'
        '<span class="kw">前十字靱帯・後十字靱帯・内側／外側側副靱帯</span>。'
        '<span class="kw3">前十字靱帯損傷では靱帯が'
        '腫大して内部がT<sub>2</sub>高信号になり、'
        '連続性が絶たれる</span>——'
        '<span class="kw3">これも「黒いはずのものが白い」の応用</span>。'),
       ('c', '関節液', True,
        '<span class="kw3">◯ 関節液は水そのもので、'
        'T<sub>2</sub>強調像で高信号（白）になる</span>。'
        '<span class="kw3">T<sub>2</sub>強調像は'
        '「水を白く写す」撮り方</span>だから、'
        '<span class="kw3">関節液・脳脊髄液・囊胞・浮腫・膿はすべて白い</span>。'
        '<span class="kw3">逆にT<sub>1</sub>強調像では水は黒い</span>。'
        '<span class="kw3">整形外科領域でMRIが多用されるのは、'
        'まさにこの「水の分布」＝'
        '関節液貯留・骨挫傷（骨髄浮腫）・腱／靱帯の損傷・半月板の変性が'
        '一目で分かるから</span>である。'),
       ('d', '骨皮質', False,
        '<span class="kw4">骨皮質は緻密で可動性の水素原子がほとんどなく、'
        'どのシーケンスでも無信号（真っ黒）</span>。'
        '<span class="kw3">「どのシーケンスでも黒いもの＝'
        '骨皮質・空気・flow void（血管内の流れる血液）・'
        '石灰化・金属」</span>と覚える。'
        '<span class="kw4">骨折線そのものはMRIで直接見えにくい</span>が、'
        '<span class="kw3">周囲の骨髄浮腫がT<sub>2</sub>・脂肪抑制像で'
        '高信号になるので、単純撮影で写らない不顕性骨折を拾える</span>。'),
       ('e', '半月板', False,
        '<span class="kw4">半月板は線維軟骨で、正常ならT<sub>2</sub>強調像で'
        '低信号の三角形（矢状断では蝶ネクタイ状）に見える</span>。'
        '<span class="kw3">内部に高信号が現れ、それが関節面に達していれば'
        '半月板断裂</span>——'
        '<span class="kw3">「低信号の中の高信号が関節面に届くか」で'
        '変性と断裂を分ける</span>のが読影の要点である。')],
      'T2強調像は「水が白い」撮り方。関節液・浮腫・囊胞が高信号。腱・靱帯・骨皮質は黒。',
      patho=('🔎 MRIの信号——「何が白いか」だけ覚えれば読める',
             '<span class="kw3">MRIの読影は、まず'
             '「そのシーケンスで何が白くなるか」を'
             '押さえるところから始まる</span>。' + TBL_MRI),
      deep=('💡 整形外科でMRIが強い理由——「水の分布」が病変そのもの',
            '<span class="kw3">骨と関節の病変の多くは'
            '「水がたまる」という形で現れる</span>——'
            '<span class="kw3">だからT<sub>2</sub>強調像（＋脂肪抑制）で'
            'ほとんどが可視化できる</span>。'
            '<table class="tb"><tr><th>組織</th>'
            '<th>T<sub>1</sub>強調像</th><th>T<sub>2</sub>強調像</th>'
            '<th>病変での変化</th></tr>'
            '<tr><td><span class="kw3">関節液・囊胞</span></td>'
            '<td><span class="kw4">低（黒）</span></td>'
            '<td><span class="kw3">高（白）</span></td>'
            '<td><span class="kw3">量が増えれば関節液貯留</span></td></tr>'
            '<tr><td>腱・靱帯</td><td>低</td><td>低</td>'
            '<td><span class="kw3">断裂・炎症でT<sub>2</sub>高信号'
            '＋腫大・連続性の途絶</span></td></tr>'
            '<tr><td>半月板・線維軟骨</td><td>低</td><td>低</td>'
            '<td><span class="kw3">内部の高信号が関節面に達すれば断裂</span></td></tr>'
            '<tr><td>硝子（関節）軟骨</td><td>中等度</td><td>中等度</td>'
            '<td>菲薄化・欠損</td></tr>'
            '<tr><td><span class="kw">骨　髄</span></td>'
            '<td><span class="kw">高（脂肪髄のため）</span></td>'
            '<td>中等度</td>'
            '<td><span class="kw3">骨挫傷・不顕性骨折・骨壊死・腫瘍で'
            'T<sub>1</sub>低信号＋脂肪抑制T<sub>2</sub>高信号</span></td></tr>'
            '<tr><td><span class="kw4">骨皮質</span></td>'
            '<td><span class="kw4">無信号</span></td>'
            '<td><span class="kw4">無信号</span></td>'
            '<td><span class="kw4">骨皮質の評価はCT・単純撮影が優る</span></td></tr>'
            '</table>'
            '<span class="kw3">脂肪抑制を併用するのは、'
            '骨髄の脂肪が明るくて病変（水）が埋もれるのを防ぐため</span>——'
            '<span class="kw3">「脂肪を消せば水だけが光る」</span>。'
            '<span class="kw3">婦人科領域（成熟囊胞性奇形腫の脂肪の証明）でも'
            '同じ手法を使う</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">T<sub>2</sub>強調像で白い＝水'
             '（関節液・脳脊髄液・浮腫・囊胞・膿）</span>。<br>'
             '② <span class="kw3">T<sub>1</sub>強調像で白い＝脂肪・'
             '亜急性期の出血・造影剤</span>。<br>'
             '③ <span class="kw3">どのシーケンスでも黒い＝骨皮質・空気・'
             'flow void・石灰化・金属</span>。<br>'
             '④ <span class="kw3">腱・靱帯・半月板は本来低信号</span>——'
             '<span class="kw3">そこに高信号が出れば損傷</span>。<br>'
             '⑤ <span class="kw">脂肪抑制＝脂肪を消して水だけを光らせる</span>'
             '（骨髄浮腫・奇形腫の脂肪証明）。')),

    # ── NO.18 (120E-41) ★必修 99% ans=b ────────────────────────
    Q('120E-41', 99, [('bs', '★'), ('bh', '必修')],
      '<span class="kw">次の文を読み、Q.18〜Q.19 の問いに答えよ。</span><br>'
      '75 歳の男性。尿量の減少を主訴に来院した。<br>'
      '<b>現病歴：</b><span class="kw">約1 年前から排尿困難感を自覚していた</span>が'
      '医療機関を受診しなかった。'
      '<span class="kw">2 日前から感冒様症状があり、自宅近くの診療所から'
      '総合感冒薬とアセトアミノフェンが処方され内服していた。'
      '昨夜、飲酒をした後から排尿困難感が悪化し、'
      '尿が間欠的に少量しか出なくなった。下腹部の膨満感も強くなった</span>ため、'
      '救急外来を受診した。<br>'
      '<b>既往歴：</b>高血圧症、糖尿病。<br>'
      '<b>生活歴：</b>喫煙は70 歳まで10 本/ 日を50 年間。飲酒は機会飲酒。<br>'
      '<b>家族歴：</b>特記すべきことはない。<br>'
      '<b>現　症：</b>意識は清明。身長175cm、体重77kg。体温36.4℃。脈拍64/ 分、整。'
      '血圧140/92mmHg。呼吸数20/ 分。SpO<sub>2</sub> 97％（room air）。'
      '努力呼吸を認めない。<span class="kw">皮膚、口腔内の乾燥を認めない。'
      '腹部は下腹部が膨隆しており、やや硬い。軽度の圧痛がある。</span>'
      '腸雑音に異常を認めない。'
      '<span class="kw">直腸指診で径5cm、弾性硬の前立腺を触知し、圧痛を認めない。</span><br>'
      '<b>検査所見：</b>尿所見：蛋白（－）、糖1 ＋、潜血（－）、沈渣に異常を認めない。'
      '血液所見：赤血球489 万、Hb 15.0g/dL、Ht 44％、白血球5,200、血小板17 万。'
      '血液生化学所見：総蛋白7.7g/dL、アルブミン4.8g/dL、総ビリルビン0.8mg/dL、'
      'AST 26U/L、ALT 15U/L、LD 200U/L（基準124 ～222）、ALP 67U/L（基準38 ～113）、'
      'γ-GT 40U/L（基準13 ～64）、アミラーゼ108U/L（基準44 ～132）、'
      'CK 180U/L（基準59 ～248）、尿素窒素14mg/dL、'
      '<span class="kw">クレアチニン0.9mg/dL</span>、尿酸6.6mg/dL、血糖130mg/dL、'
      'HbA1c 6.5％（基準4.9 ～6.0）、Na 138mEq/L、K 4.1mEq/L、Cl 100mEq/L。'
      'CRP 0.1mg/dL。腹部超音波像を示す。<br>'
      '<strong>最も考えられる病態はどれか。</strong>',
      [('a', '脱　水', False,
        '<span class="kw4">脱水なら皮膚・口腔内の乾燥、'
        '頻脈、血液濃縮（Ht上昇・BUN/Cr比の上昇）を伴う</span>。'
        '<span class="kw4">本例は「皮膚、口腔内の乾燥を認めない」と明記され、'
        '脈拍64/分、BUN 14／Cr 0.9（比15）と正常</span>。'
        '<span class="kw4">積極的に否定されている</span>。'),
       ('b', '尿　閉', True,
        '<span class="kw3">◯ 尿閉（急性尿閉）</span>。'
        '<span class="kw3">「下腹部が膨隆してやや硬い」＝'
        '充満した膀胱を触れている</span>のが決定的で、'
        '<span class="kw3">超音波でも著明に拡張した膀胱が確認できる</span>。'
        '<span class="kw3">背景は前立腺肥大症（1年前からの排尿困難感、'
        '直腸指診で径5cm・弾性硬・表面平滑・圧痛なし）</span>で、'
        '<span class="kw3">そこに引き金が2つ重なった</span>——'
        '<span class="kw3">①総合感冒薬（抗ヒスタミン薬の抗コリン作用で'
        '排尿筋が緩み、α刺激薬で尿道が締まる）'
        '②飲酒（急激な尿量増加と、アルコールによる排尿反射の抑制）</span>。'
        '<span class="kw3">これはMECが繰り返し出す定番の症例パターン</span>である。'),
       ('c', '心不全', False,
        '<span class="kw4">心不全なら呼吸困難・起坐呼吸・湿性ラ音・'
        '頸静脈怒張・浮腫を伴う</span>。'
        '<span class="kw4">本例はSpO<sub>2</sub> 97%・努力呼吸なし・'
        '呼吸数20/分で、心不全を示唆する所見がない</span>。'
        '<span class="kw">下腹部の膨隆を腹水と読むのも無理がある'
        '（腹水なら側腹部が張り、波動を触れ、「やや硬い」局所の膨隆にはならない）</span>。'),
       ('d', '腸閉塞', False,
        '<span class="kw4">腸閉塞なら腹部全体の膨満・'
        '腸雑音の亢進（金属音）または消失・嘔吐・排ガス停止を伴う</span>。'
        '<span class="kw4">本例は「腸雑音に異常を認めない」と明記され、'
        '膨隆は下腹部に限局している</span>。'),
       ('e', '急性腎障害', False,
        '<span class="kw4">尿量減少という主訴から飛びつきやすい肢</span>だが、'
        '<span class="kw4">クレアチニン0.9mg/dL・尿素窒素14mg/dLと'
        '腎機能はまったく正常</span>。'
        '<span class="kw3">「尿が出ない」の原因が'
        '「腎が作れていない」のか'
        '「作れているのに出せていない」のかは別問題</span>で、'
        '<span class="kw3">本例は後者＝膀胱に尿は溜まっている</span>。'
        '<span class="kw4">ただし尿閉を放置すれば'
        '腎後性の急性腎障害へ進む</span>ので、'
        '<span class="kw3">「今は正常だが、放置すればこうなる」という関係</span>にある。')],
      '下腹部の膨隆＋充満した膀胱＝尿閉。腎機能は正常で腎前性・腎性ではない。',
      imgs=[IMG + '120E-41_1.jpeg', IMG + '120E-41_2.jpeg'],
      patho=('🔎 画像所見——著明に拡張した膀胱と、水腎症のない腎',
             '<span class="kw3">腹部超音波像の上段は膀胱で、'
             '内部が無エコー（黒）の巨大な空間として描出され、'
             '縦80mm×横100〜120mm と計測されている</span>——'
             '<span class="kw3">＝尿が大量に貯留した膀胱そのもの</span>。'
             '<span class="kw3">下段は右腎・左腎で、'
             '腎盂・腎杯の拡張（水腎症）は目立たない</span>。'
             '<table class="tb"><tr><th>所見</th><th>読み</th><th>意味</th></tr>'
             '<tr><td><span class="kw3">膀胱の著明な拡張</span></td>'
             '<td><span class="kw3">尿は作られているが排出できていない</span></td>'
             '<td><span class="kw3">閉塞は膀胱より下（膀胱頸部・尿道）</span></td></tr>'
             '<tr><td><span class="kw3">水腎症は目立たない</span></td>'
             '<td><span class="kw3">閉塞がまだ急性で上部尿路まで'
             '及んでいない</span></td>'
             '<td><span class="kw3">腎機能が保たれていること'
             '（Cr 0.9）と整合する</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">⚠️ 泌尿器科の基本的な考え方'
             '——「膀胱に尿があるかどうかで閉塞の高さが決まる」</span>。<br>'
             '<span class="kw3">膀胱が空なのに両側水腎症 → 閉塞は尿管の高さ'
             '（尿管ステント・腎瘻）</span>／'
             '<span class="kw3">膀胱が張っている → 閉塞は尿道の高さ'
             '（尿道カテーテル・膀胱瘻）</span>。<br>'
             '本例は後者で、<span class="kw3">次問（Q.19）の答えが'
             'ここで決まっている</span>。</td></tr></table>'),
      deep=('💡 「尿が出ない」の3つの原因を切り分ける',
            '<span class="kw3">尿量減少・無尿を見たら、'
            '腎前性・腎性・腎後性のどれかを決める</span>。'
            '<table class="tb"><tr><th></th><th>腎前性</th><th>腎　性</th>'
            '<th><span class="kw3">腎後性（本例）</span></th></tr>'
            '<tr><td>原因</td>'
            '<td><span class="kw">脱水・出血・心不全・敗血症</span>'
            '（腎への血流低下）</td>'
            '<td><span class="kw">急性尿細管壊死・糸球体腎炎・'
            '間質性腎炎・造影剤腎症</span></td>'
            '<td><span class="kw3">尿路の閉塞'
            '（前立腺肥大症・尿路結石・腫瘍・神経因性膀胱）</span></td></tr>'
            '<tr><td><span class="kw3">膀胱の尿</span></td>'
            '<td>少ない（濃縮尿）</td><td>少ない</td>'
            '<td><span class="kw3">尿道閉塞なら充満、'
            '尿管閉塞なら空</span></td></tr>'
            '<tr><td>身体所見</td>'
            '<td><span class="kw">皮膚・口腔の乾燥、'
            '頻脈、起立性低血圧</span></td>'
            '<td>—</td>'
            '<td><span class="kw3">下腹部の膨隆（膀胱を触知）</span></td></tr>'
            '<tr><td>BUN/Cr比</td>'
            '<td><span class="kw">上昇（20以上）</span></td>'
            '<td>正常</td><td>さまざま</td></tr>'
            '<tr><td>画　像</td><td>—</td><td>—</td>'
            '<td><span class="kw3">超音波で膀胱の充満／水腎症</span></td></tr>'
            '<tr><td>対応</td>'
            '<td><span class="kw">輸液（細胞外液）</span></td>'
            '<td>原因の除去・腎保護</td>'
            '<td><span class="kw3">閉塞の解除が最優先</span></td></tr></table>'
            '<span class="kw3">腎後性は「解除すれば治る」ので、'
            '見つけたらまず解除する</span>——'
            '<span class="kw3">超音波1本で診断でき、しかも'
            '放置すれば不可逆な腎障害に進む</span>ため、'
            '<span class="kw3">「尿が出ない」と言われたら'
            'まずベッドサイドで膀胱をエコーで見る</span>のが実践的である。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">下腹部の膨隆＋超音波で充満した膀胱＝尿閉</span>。<br>'
             '② <span class="kw3">膀胱に尿があるかどうかで閉塞の高さが決まる</span>'
             '（膀胱が空＋水腎症＝尿管／膀胱が張る＝尿道）。<br>'
             '③ <span class="kw3">BPHの尿閉の引き金＝総合感冒薬'
             '（抗ヒスタミン薬・α刺激薬）と飲酒</span>。<br>'
             '④ <span class="kw">BPHの直腸指診＝弾性硬・表面平滑・圧痛なし</span>'
             '（癌は石様硬・表面不整）。<br>'
             '⑤ <span class="kw4">放置すれば腎後性急性腎障害へ進む</span>。')),

    # ── NO.19 (120E-42) 必修 99% ans=e ─────────────────────────
    Q('120E-42', 99, [('bh', '必修')],
      '<span class="kw">次の文を読み、Q.18〜Q.19 の問いに答えよ。</span><br>'
      '75 歳の男性。尿量の減少を主訴に来院した。<br>'
      '<b>現病歴：</b><span class="kw">約1 年前から排尿困難感を自覚していた</span>が'
      '医療機関を受診しなかった。'
      '<span class="kw">2 日前から感冒様症状があり、自宅近くの診療所から'
      '総合感冒薬とアセトアミノフェンが処方され内服していた。'
      '昨夜、飲酒をした後から排尿困難感が悪化し、'
      '尿が間欠的に少量しか出なくなった。下腹部の膨満感も強くなった</span>ため、'
      '救急外来を受診した。<br>'
      '<b>既往歴：</b>高血圧症、糖尿病。<br>'
      '<b>生活歴：</b>喫煙は70 歳まで10 本/ 日を50 年間。飲酒は機会飲酒。<br>'
      '<b>家族歴：</b>特記すべきことはない。<br>'
      '<b>現　症：</b>意識は清明。身長175cm、体重77kg。体温36.4℃。脈拍64/ 分、整。'
      '血圧140/92mmHg。呼吸数20/ 分。SpO<sub>2</sub> 97％（room air）。'
      '努力呼吸を認めない。<span class="kw">皮膚、口腔内の乾燥を認めない。'
      '腹部は下腹部が膨隆しており、やや硬い。軽度の圧痛がある。</span>'
      '腸雑音に異常を認めない。'
      '<span class="kw">直腸指診で径5cm、弾性硬の前立腺を触知し、圧痛を認めない。</span><br>'
      '<b>検査所見：</b>尿所見：蛋白（－）、糖1 ＋、潜血（－）、沈渣に異常を認めない。'
      '血液所見：赤血球489 万、Hb 15.0g/dL、Ht 44％、白血球5,200、血小板17 万。'
      '血液生化学所見：総蛋白7.7g/dL、アルブミン4.8g/dL、総ビリルビン0.8mg/dL、'
      'AST 26U/L、ALT 15U/L、LD 200U/L（基準124 ～222）、ALP 67U/L（基準38 ～113）、'
      'γ-GT 40U/L（基準13 ～64）、アミラーゼ108U/L（基準44 ～132）、'
      'CK 180U/L（基準59 ～248）、尿素窒素14mg/dL、'
      '<span class="kw">クレアチニン0.9mg/dL</span>、尿酸6.6mg/dL、血糖130mg/dL、'
      'HbA1c 6.5％（基準4.9 ～6.0）、Na 138mEq/L、K 4.1mEq/L、Cl 100mEq/L。'
      'CRP 0.1mg/dL。腹部超音波像を示す。<br>'
      '<strong>適切な対応はどれか。</strong>',
      [('a', '絶飲食', False,
        '<span class="kw4">絶飲食は消化管の閉塞・穿孔・'
        '緊急手術を前提とする対応</span>。'
        '<span class="kw4">本例は消化管に問題がなく（腸雑音正常）、'
        '絶飲食にしても尿は出るようにならない</span>。'
        '<span class="kw4">むしろ脱水を招くだけで有害</span>。'),
       ('b', '血液透析', False,
        '<span class="kw4">クレアチニン0.9mg/dL・K 4.1mEq/L・'
        'アシドーシスも溢水も無く、透析の適応がまったくない</span>。'
        '<span class="kw3">仮に腎後性腎障害でCrが上昇していたとしても、'
        'まず行うべきは閉塞の解除であって透析ではない</span>——'
        '<span class="kw3">閉塞を解除すれば腎機能は回復する</span>。'
        '<span class="kw3">「透析より先にカテーテル」は泌尿器科で'
        '繰り返し問われる原則</span>である。'),
       ('c', 'β遮断薬投与', False,
        '<span class="kw4">β遮断薬は排尿に無関係</span>。'
        '<span class="kw3">前立腺肥大症で使うのはα<sub>1</sub>遮断薬'
        '（タムスロシン・シロドシンなど）</span>で、'
        '<span class="kw3">前立腺と膀胱頸部の平滑筋のα<sub>1</sub>受容体を'
        '遮断して尿道抵抗を下げる</span>。'
        '<span class="kw4">「α」と「β」を取り違えさせる肢</span>で、'
        '<span class="kw4">しかも急性尿閉の「いま」の対応としては'
        '薬では間に合わない</span>。'),
       ('d', 'フロセミド投与', False,
        '<span class="kw4">出口が詰まっているところに'
        '利尿薬で尿を増やしても、膀胱がさらに膨れるだけで有害</span>。'
        '<span class="kw4">膀胱破裂や強い苦痛につながりうる</span>。'
        '<span class="kw3">「尿量減少＝利尿薬」という条件反射が'
        '最も危険な誤り</span>で、'
        '<span class="kw3">利尿薬が意味を持つのは'
        '「腎は働けるのに体液がうっ滞している」場合（心不全など）だけ</span>である。'),
       ('e', '尿道カテーテル留置', True,
        '<span class="kw3">◯ 急性尿閉に対する第一の処置は導尿'
        '（尿道カテーテルの留置）</span>である。'
        '<span class="kw3">診断的にも治療的にも即効性があり、'
        '苦痛が直ちに取れ、腎後性腎障害への進行も防げる</span>。'
        '<span class="kw3">「尿閉をみたら、理屈より先に導尿」</span>——'
        '<span class="kw3">Crが高くても透析より先、'
        '両側水腎症があっても腎瘻より先にまずカテーテル</span>。'
        '<span class="kw">尿道からの挿入が困難なら'
        '（尿道狭窄・偽尿道形成・尿道損傷）膀胱瘻を考える</span>。<br>'
        '<span class="kw4">⚠️ 留置後の注意——長時間の閉塞後に'
        '一気に排出すると膀胱内圧の急減で'
        '膀胱粘膜からの出血（減圧性血尿）や'
        '閉塞解除後利尿〈post-obstructive diuresis〉、'
        '一過性の低血圧を起こしうる</span>ので、'
        '<span class="kw3">排出後は尿量・バイタル・電解質を監視する</span>。')],
      '急性尿閉は理屈より先に導尿。透析・腎瘻・利尿薬はすべてその後（または不要）。',
      imgs=[IMG + '120E-42_1.jpeg', IMG + '120E-42_2.jpeg'],
      patho=('🔎 閉塞の高さ別——何を入れるかは「どこで詰まっているか」で決まる',
             '<span class="kw3">尿路閉塞の解除は、'
             '閉塞部位より上流に「出口」を作ること</span>。'
             '<table class="tb"><tr><th>閉塞の高さ</th><th>代表的な原因</th>'
             '<th>超音波の所見</th><th>解除の方法</th></tr>'
             '<tr><td><span class="kw3">尿道・膀胱頸部</span></td>'
             '<td><span class="kw3">前立腺肥大症・前立腺癌・'
             '尿道狭窄・神経因性膀胱・薬剤性</span></td>'
             '<td><span class="kw3">膀胱が充満</span></td>'
             '<td><span class="kw3">尿道カテーテル</span>'
             '（困難なら<span class="kw3">膀胱瘻</span>）</td></tr>'
             '<tr><td><span class="kw3">尿　管</span></td>'
             '<td><span class="kw3">結石・腫瘍（尿路上皮癌・'
             '骨盤内腫瘍による圧排）・後腹膜線維症</span></td>'
             '<td><span class="kw3">膀胱は空で水腎症</span></td>'
             '<td><span class="kw3">尿管ステント</span>'
             '（困難なら<span class="kw3">経皮的腎瘻</span>）</td></tr>'
             '<tr><td colspan="4"><span class="kw3">⚠️ 発熱を伴う閉塞'
             '（閉塞性腎盂腎炎）は緊急ドレナージの適応</span>——'
             '<span class="kw3">抗菌薬だけでは治らず、'
             '砕石などの根本治療は感染が鎮まってから</span>。</td></tr></table>'),
      deep=('💡 前立腺肥大症による尿閉——引き金と、その後の治療',
            '<span class="kw3">急性尿閉は「前立腺が急に大きくなった」のではなく、'
            '「もともと狭かったところに引き金が加わった」</span>ために起こる。'
            '<table class="tb"><tr><th>引き金</th><th>機序</th></tr>'
            '<tr><td><span class="kw3">総合感冒薬・抗ヒスタミン薬</span></td>'
            '<td><span class="kw3">抗コリン作用で排尿筋（膀胱の収縮）が緩む</span></td></tr>'
            '<tr><td><span class="kw3">α刺激薬（点鼻薬・感冒薬に含まれる）</span></td>'
            '<td><span class="kw3">前立腺・膀胱頸部の平滑筋が収縮して'
            '尿道抵抗が上がる</span></td></tr>'
            '<tr><td><span class="kw3">飲　酒</span></td>'
            '<td><span class="kw3">利尿で急に尿量が増え、'
            'かつ中枢性に排尿反射が抑制される</span></td></tr>'
            '<tr><td><span class="kw">三環系抗うつ薬・抗パーキンソン病薬・'
            '一部の抗精神病薬</span></td>'
            '<td><span class="kw">抗コリン作用</span></td></tr>'
            '<tr><td><span class="kw">長時間の座位・便秘・寒冷</span></td>'
            '<td>骨盤内のうっ血・交感神経緊張</td></tr></table>'
            '<span class="kw3">導尿で急場をしのいだあとは、'
            'α<sub>1</sub>遮断薬（＋5α還元酵素阻害薬）を開始し、'
            'カテーテルを抜いて自排尿できるか試す</span>。'
            '<span class="kw4">再燃を繰り返す・腎機能障害を伴う・'
            '膀胱結石や反復する尿路感染がある場合は'
            '経尿道的前立腺切除術〈TURP〉などの手術</span>を考える。<br>'
            '<span class="kw4">⚠️ 前立腺肥大症に抗コリン薬（過活動膀胱の薬）を'
            '安易に使うと尿閉を招く</span>——'
            '<span class="kw4">国試で「不適切な処方」として頻出</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">急性尿閉の第一の処置は尿道カテーテル留置（導尿）</span>。<br>'
             '② <span class="kw3">Crが高くても透析より先、'
             '水腎症があっても腎瘻より先にまずカテーテル</span>。<br>'
             '③ <span class="kw4">出口が詰まっているのに利尿薬は禁</span>。<br>'
             '④ <span class="kw3">BPHの薬はα<sub>1</sub>遮断薬</span>'
             '（β遮断薬ではない）。'
             '<span class="kw4">抗コリン薬は尿閉を招く</span>。<br>'
             '⑤ <span class="kw">長時間閉塞後の急な減圧では'
             '血尿・閉塞解除後利尿・低血圧に注意</span>。')),

]
