
# ------------------------------------------------------------------
# 連問 NO.27〜29（114C-69/70/71）の共通ステム。
# ⚠️ 試験モードはカードを1枚ずつ独立に出すので、3問すべての qt に連結すること。
# ------------------------------------------------------------------
_STEM_27 = (
    '<span class="kw">次の文を読み、Q.27〜Q.29 の問いに答えよ。</span><br>'
    '66 歳の男性。胸背部痛と左上下肢の筋力低下のため救急車で搬入された。<br>'
    '<b>現病歴：</b><span class="kw">本日午前11 時、デスクワーク中に'
    '本棚上段から書類を取ろうと手を伸ばしたところ、'
    '激烈な胸背部痛が突然出現した。その後すぐに左片麻痺が出現し、'
    'さらに重苦しい胸痛と冷汗が出現した</span>ため、'
    '発症から30 分後に救急車を要請した。<br>'
    '<b>既往歴：</b><span class="kw">2 年前から高血圧症で通院治療中。</span><br>'
    '<b>生活歴：</b>妻と2 人暮らし。喫煙歴はない。飲酒は機会飲酒。<br>'
    '<b>家族歴：</b>父親は脳出血のため86 歳で死亡。母は胃癌のため88 歳で死亡。<br>'
    '<b>現　症：</b>意識は清明。身長162cm、体重80kg。'
    '<span class="kw">血圧78/62mmHg で明らかな左右差を認めない。'
    '脈拍108/ 分（微弱）、整。</span>呼吸数18/ 分。SpO<sub>2</sub> 99％（room air）。'
    '<span class="kw">頸静脈の怒張を認める。</span>眼瞼結膜に貧血を認めない。'
    '<span class="kw">心音はⅠ音Ⅱ音とも減弱しており、'
    '胸骨左縁第3 肋間を最強とするⅡ/Ⅵの拡張期灌水様雑音を認める。</span>'
    '呼吸音に異常を認めない。腹部は平坦、軟で、肝・脾を触知しない。'
    '<span class="kw">左上下肢に不全片麻痺を認め、Babinski 徴候は陽性である。</span><br>'
    '<b>検査所見：</b><span class="kw">心電図は、心拍数108/ 分の洞調律で、'
    '肢誘導および胸部誘導ともに低電位で、Ⅱ、Ⅲ、aV<sub>F</sub> にST 上昇を認めた。</span><br>'
    '<span class="kw">ポータブル撮影機による仰臥位の胸部エックス線写真（A）及び'
    '6 か月前に撮影された立位の胸部エックス線写真（B）</span>を示す。'
    '胸部エックス線写真を見比べながら、研修医が指導医に所見や解釈を報告した。<br>')

QUESTIONS += [

    # ── NO.27 (114C-69) 20% ans=d ← 本科目の最難 ────────────────
    Q('114C-69', 20, [],
      _STEM_27 + '<strong>適切なのはどれか。</strong>',
      [('a', '「6 か月前と比較して胃泡が多くなっています」', False,
        '<span class="kw4">胃泡（胃の中の空気）の見え方は体位で大きく変わる</span>。'
        '<span class="kw4">立位では空気が胃底部に集まって'
        '横隔膜下の明瞭なガス像として写るが、'
        '仰臥位では空気が広がって不明瞭になる</span>。'
        '<span class="kw4">体位の違う2枚で胃泡の「量」を比較することはできない</span>。'
        '<span class="kw">そもそも本例の病態と胃泡は無関係</span>。'),
       ('b', '「本日の写真では下行大動脈が認められません」', False,
        '<span class="kw4">下行大動脈は椎体の左縁に沿う線として'
        '通常は追える</span>。'
        '<span class="kw4">本例の写真でも認められないわけではない</span>。'
        '<span class="kw">むしろ大動脈解離では上縦隔の拡大・'
        '大動脈陰影の拡大がみられることがあるが、'
        '<span class="kw3">仰臥位AP像では縦隔がもともと広く写る</span>ので'
        'これも単純には比較できない</span>。'),
       ('c', '「本日の写真では著しい気管の偏位が認められます」', False,
        '<span class="kw4">著しい気管偏位をきたすのは'
        '緊張性気胸・大量胸水・広範な無気肺・巨大な縦隔腫瘤</span>など。'
        '<span class="kw4">本例にそれらの所見はなく、'
        '呼吸音も正常でSpO<sub>2</sub> 99%</span>。'
        '<span class="kw">「著しい」と断定する根拠がない</span>。'),
       ('d', '「6 か月前と心拡大の程度を比較するのは困難です」', True,
        '<span class="kw3">◯ これが正しい。'
        '本日はポータブル撮影機による<u>仰臥位のAP（前後）像</u>、'
        '6か月前は<u>立位のPA（後前）像</u>で、'
        '撮影体位も方向も違う</span>。'
        '<span class="kw3">AP像では、心臓がフィルム（検出器）から遠く'
        'エックス線管に近い位置にあるため、'
        '幾何学的に拡大して写る</span>——'
        '<span class="kw3">つまりAP像の心陰影は'
        '実際より大きく見えるのが当たり前</span>である。'
        '<span class="kw3">さらに仰臥位では静脈還流が増えて'
        '心陰影・縦隔が実際に広がるうえ、'
        'ポータブル撮影では撮影距離が短く（100cm程度）、'
        '深吸気を保てないことも多い</span>。'
        '<span class="kw3">したがって心胸郭比〈CTR〉を'
        '2枚で比較して「心拡大が進んだ」と述べることはできない</span>。<br>'
        '<span class="kw4">⚠️ 正答率20%＝本科目で最も低い</span>。'
        '<span class="kw4">画像そのものを読むのではなく'
        '「その画像で何が言えて、何が言えないか」を問う設問</span>で、'
        '<span class="kw3">まさに放射線科らしい一問である</span>。'),
       ('e', '「いずれの写真でもCP アングル〈肋骨横隔膜角〉は鋭なので'
        '胸水貯留はありません」', False,
        '<span class="kw4">仰臥位では胸水は背側に薄く広がるため、'
        'CPアングルの鈍化として現れない</span>——'
        '<span class="kw4">「仰臥位でCPアングルが鋭い」ことは'
        '胸水がないことの証明にならない</span>。'
        '<span class="kw3">仰臥位で胸水を示唆するのは'
        '「患側肺野全体のびまん性の淡い濃度上昇」</span>である。'
        '<span class="kw">（なお立位でCPアングルが鈍化するには'
        '200〜250mL以上の胸水が必要で、'
        '立位でも少量胸水は見逃されうる）</span>')],
      '仰臥位AP像と立位PA像では心陰影の拡大率が違う。心拡大の比較はできない。',
      imgs=[IMG + '114C-69_1.jpeg', IMG + '114C-69_2.jpeg'],
      patho=('🔎 胸部エックス線写真は「どう撮ったか」で見え方が変わる',
             '<span class="kw3">胸部単純写真を読む前に、'
             '必ず撮影条件を確認する</span>——'
             '<span class="kw3">体位（立位／仰臥位）、方向（PA／AP）、'
             '吸気の程度、回旋の有無</span>。'
             '<span class="kw3">これを無視すると、'
             '正常を異常と読み、異常を正常と読む</span>。'
             '<table class="tb"><tr><th></th>'
             '<th><span class="kw3">立位 PA像（標準）</span></th>'
             '<th><span class="kw3">仰臥位 AP像（ポータブル）</span></th></tr>'
             '<tr><td>エックス線の向き</td>'
             '<td><span class="kw3">背中から前へ（心臓が検出器に近い）</span></td>'
             '<td><span class="kw3">前から背中へ（心臓が検出器から遠い）</span></td></tr>'
             '<tr><td><span class="kw3">心陰影</span></td>'
             '<td><span class="kw3">実物大に近い</span></td>'
             '<td><span class="kw3">拡大して写る（＋仰臥位で静脈還流が増え'
             '実際にも広がる）</span>'
             '——<span class="kw4">CTRを過大評価する</span></td></tr>'
             '<tr><td><span class="kw3">縦　隔</span></td>'
             '<td>細く写る</td>'
             '<td><span class="kw4">広く写る</span>'
             '——<span class="kw4">縦隔拡大と誤読しやすい</span></td></tr>'
             '<tr><td><span class="kw3">胸　水</span></td>'
             '<td><span class="kw3">CPアングルの鈍化</span>'
             '（200〜250mL以上で）</td>'
             '<td><span class="kw3">背側に広がり、'
             '肺野全体の淡い濃度上昇として写る</span>'
             '——<span class="kw4">CPアングルは鋭いまま</span></td></tr>'
             '<tr><td><span class="kw">気　胸</span></td>'
             '<td><span class="kw">肺尖部に虚脱線</span></td>'
             '<td><span class="kw4">空気が前方（腹側）へ移動するので'
             '見えにくい（deep sulcus sign を探す）</span></td></tr>'
             '<tr><td><span class="kw">遊離ガス（穿孔）</span></td>'
             '<td><span class="kw">横隔膜下の free air</span></td>'
             '<td><span class="kw4">写らない</span></td></tr>'
             '<tr><td>撮影距離</td><td>約180cm</td>'
             '<td><span class="kw">約100cm（拡大率がさらに上がる）</span></td></tr>'
             '<tr><td>吸　気</td><td>深吸気で保持</td>'
             '<td><span class="kw4">不十分になりやすい'
             '（＝肺野の濃度が上がり心陰影も大きく見える）</span></td></tr></table>'),
      deep=('💡 この症例の全体像——急性大動脈解離のStanford A型',
             '<span class="kw3">本例は「突然の激烈な胸背部痛」で始まり、'
             '複数の臓器の症状が同時に出ている</span>——'
             '<span class="kw3">1つの病気で説明するなら急性大動脈解離</span>である。'
             '<table class="tb"><tr><th>所見</th><th>解離のどの合併症か</th></tr>'
             '<tr><td><span class="kw3">突然の激烈な胸背部痛</span></td>'
             '<td><span class="kw3">解離そのもの（引き裂かれるような痛み）</span></td></tr>'
             '<tr><td><span class="kw3">左片麻痺・Babinski徴候陽性</span></td>'
             '<td><span class="kw3">右腕頭動脈／総頸動脈への解離進展'
             '＝脳虚血</span></td></tr>'
             '<tr><td><span class="kw3">Ⅱ、Ⅲ、aV<sub>F</sub>のST上昇</span></td>'
             '<td><span class="kw3">右冠動脈入口部への解離進展'
             '＝下壁の急性心筋梗塞</span></td></tr>'
             '<tr><td><span class="kw3">拡張期灌水様雑音'
             '（胸骨左縁第3肋間）</span></td>'
             '<td><span class="kw3">大動脈弁輪の拡大'
             '＝急性大動脈弁閉鎖不全症</span></td></tr>'
             '<tr><td><span class="kw3">血圧78/62mmHg・脈拍微弱・'
             '頸静脈怒張・心音減弱・心電図の低電位</span></td>'
             '<td><span class="kw3">上行大動脈からの出血が心囊へ'
             '＝心タンポナーデ</span></td></tr>'
             '<tr><td colspan="2"><span class="kw3">上行大動脈に及ぶ'
             '＝Stanford A型で、緊急手術の適応</span>。<br>'
             '<span class="kw4">「胸痛＋神経症状」「胸痛＋左右差／血圧低下」'
             '「胸痛＋大動脈弁逆流」の組合せをみたら'
             '大動脈解離を最優先で疑う</span>。</td></tr></table>'
             '<span class="kw3">この全体像が見えていると、'
             'Q.28（可能性が低い疾患）とQ.29（優先する検査）が'
             'そのまま解ける</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">仰臥位AP像は心陰影が拡大して写る</span>'
             '——<span class="kw3">立位PA像と心拡大を比較できない</span>。<br>'
             '② <span class="kw3">仰臥位では胸水がCPアングルの鈍化として'
             '現れない</span>（肺野全体の淡い濃度上昇になる）。<br>'
             '③ <span class="kw">仰臥位では気胸・遊離ガスも見えにくい</span>。<br>'
             '④ <span class="kw3">読影の前に体位・方向・吸気・回旋を確認する</span>。<br>'
             '⑤ <span class="kw3">突然の胸背部痛＋神経症状＋大動脈弁逆流＋'
             'ショック＝Stanford A型急性大動脈解離</span>。')),

    # ── NO.28 (114C-70) 91% ans=d ──────────────────────────────
    Q('114C-70', 91, [],
      _STEM_27 + '<strong>この時点で可能性が低い疾患はどれか。</strong>',
      [('a', '脳梗塞', False,
        '<span class="kw4">「左上下肢の不全片麻痺・Babinski徴候陽性」＝'
        '右大脳半球の障害があり、脳梗塞は否定できない</span>。'
        '<span class="kw3">大動脈解離が右腕頭動脈・総頸動脈へ進展して'
        '脳虚血を起こしたと考えるのが本例の筋</span>だが、'
        '<span class="kw3">いずれにせよ「脳梗塞という病態が起きている」'
        'ことに変わりはない</span>。'),
       ('b', '大動脈解離', False,
        '<span class="kw4">むしろ本例の本態</span>。'
        '<span class="kw3">突然の激烈な胸背部痛・'
        '拡張期灌水様雑音（大動脈弁閉鎖不全）・'
        '脳虚血・下壁のST上昇・心タンポナーデという'
        '多臓器の所見を1つで説明できるのは解離だけ</span>である。'),
       ('c', '急性冠症候群', False,
        '<span class="kw4">Ⅱ、Ⅲ、aV<sub>F</sub>のST上昇＝'
        '下壁の急性心筋梗塞の所見があり、可能性は高い</span>。'
        '<span class="kw3">ただし本例では「解離が右冠動脈入口部へ及んだ結果」'
        'である可能性が高く、'
        'ここを見落として抗血栓療法を始めると'
        '解離を悪化させ致命的になる</span>——'
        '<span class="kw3">「下壁梗塞＋胸背部痛＋血圧低下」では'
        '必ず解離を否定してからPCIへ進む</span>。'),
       ('d', '肺血栓塞栓症', True,
        '<span class="kw3">◯ 可能性が低い。'
        '肺血栓塞栓症であれば低酸素血症を伴うのが原則</span>だが、'
        '<span class="kw3">本例はSpO<sub>2</sub> 99％（room air）・'
        '呼吸数18/分・呼吸音正常</span>。'
        '<span class="kw3">肺塞栓は肺動脈が詰まって'
        '換気血流不均衡と死腔換気が生じるので、'
        '呼吸困難・頻呼吸・低酸素血症が前面に出る</span>。'
        '<span class="kw3">また心電図所見も合わない</span>——'
        '<span class="kw3">肺塞栓では右心負荷所見'
        '（S<sub>1</sub>Q<sub>3</sub>T<sub>3</sub>パターン・'
        'V<sub>1-3</sub>の陰性T波・右脚ブロック・洞性頻脈）が出るのであって、'
        'Ⅱ・Ⅲ・aV<sub>F</sub>のST上昇にはならない</span>。'
        '<span class="kw3">さらに拡張期灌水様雑音（大動脈弁逆流）や'
        '片麻痺も説明できない</span>。'),
       ('e', '心タンポナーデ', False,
        '<span class="kw4">むしろ強く疑う所見が揃っている</span>——'
        '<span class="kw3">血圧低下（78/62mmHg）・頸静脈怒張・心音減弱'
        '＝Beckの三徴</span>に加えて'
        '<span class="kw3">脈拍微弱・脈圧の狭小化・'
        '心電図の低電位（心囊液が電気を減衰させる）</span>。'
        '<span class="kw3">上行大動脈解離からの出血が心囊内へ及んだもの</span>で、'
        '<span class="kw4">解離に伴う心タンポナーデは'
        '最も多い死因の1つ</span>である。')],
      '肺塞栓なら低酸素になるはず。SpO2 99%・右心負荷所見なしで否定的。',
      imgs=[IMG + '114C-70_1.jpeg', IMG + '114C-70_2.jpeg'],
      patho=('🔎 急性胸痛の鑑別——「命に関わる5つ」を先に潰す',
             '<span class="kw3">急性胸痛では、まず致死的な5疾患'
             '（killer chest pain）を否定する</span>。'
             '<table class="tb"><tr><th>疾患</th><th>特徴的な所見</th>'
             '<th>本例での評価</th></tr>'
             '<tr><td><span class="kw3">急性大動脈解離</span></td>'
             '<td><span class="kw3">突然の激烈な胸背部痛・'
             '血圧の左右差／上下肢差・大動脈弁逆流の雑音・'
             '分枝閉塞による多彩な症状（脳・冠動脈・腎・腸間膜・下肢）</span></td>'
             '<td><span class="kw3">最も合致（本態）</span></td></tr>'
             '<tr><td><span class="kw3">急性冠症候群</span></td>'
             '<td><span class="kw3">ST変化・トロポニン上昇・冷汗</span></td>'
             '<td><span class="kw3">Ⅱ・Ⅲ・aV<sub>F</sub>のST上昇あり'
             '（解離の合併として）</span></td></tr>'
             '<tr><td><span class="kw3">肺血栓塞栓症</span></td>'
             '<td><span class="kw3">呼吸困難・頻呼吸・<u>低酸素血症</u>・'
             'D-ダイマー上昇・右心負荷所見'
             '（S<sub>1</sub>Q<sub>3</sub>T<sub>3</sub>）・'
             '長期臥床や術後などの誘因</span></td>'
             '<td><span class="kw4">SpO<sub>2</sub> 99%で否定的</span></td></tr>'
             '<tr><td><span class="kw">緊張性気胸</span></td>'
             '<td><span class="kw">患側呼吸音の消失・'
             '頸静脈怒張・気管偏位・皮下気腫</span></td>'
             '<td><span class="kw4">呼吸音正常</span></td></tr>'
             '<tr><td><span class="kw">食道破裂'
             '（Boerhaave症候群）</span></td>'
             '<td><span class="kw">嘔吐に続く胸痛・皮下気腫・'
             '縦隔気腫</span></td>'
             '<td><span class="kw4">嘔吐の記載なし</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">＋心タンポナーデ'
             '（Beckの三徴）も忘れない</span>。<br>'
             '<span class="kw3">本例は「解離が原因で、'
             '心筋梗塞・脳梗塞・心タンポナーデを二次的に起こしている」</span>'
             'という構造になっている。</td></tr></table>'),
      deep=('💡 「1つの病気で全部説明できるか」を考える',
            '<span class="kw3">複数の臓器の症状が同時に出たとき、'
            '偶然の合併を考えるより'
            '「1つの病態が広がった」と考えるほうが自然</span>である。'
            '<span class="kw3">大動脈解離はまさにそれを起こす疾患</span>——'
            '<span class="kw3">大動脈から分岐するあらゆる血管が'
            '巻き込まれうるので、症状が多彩になる</span>。'
            '<table class="tb"><tr><th>巻き込まれる分枝</th>'
            '<th>起こること</th><th>紛らわしい診断</th></tr>'
            '<tr><td><span class="kw3">冠動脈（とくに右）</span></td>'
            '<td><span class="kw3">急性心筋梗塞（下壁が多い）</span></td>'
            '<td><span class="kw4">急性冠症候群</span>'
            '——<span class="kw4">抗血栓療法を始めると致命的</span></td></tr>'
            '<tr><td><span class="kw3">腕頭動脈・総頸動脈</span></td>'
            '<td><span class="kw3">脳梗塞・意識障害・片麻痺</span></td>'
            '<td><span class="kw4">脳梗塞</span>'
            '——<span class="kw4">t-PAを投与すると致命的</span></td></tr>'
            '<tr><td><span class="kw">鎖骨下動脈</span></td>'
            '<td><span class="kw">上肢の血圧左右差・脈拍消失</span></td>'
            '<td>—</td></tr>'
            '<tr><td><span class="kw">腹腔／上腸間膜動脈</span></td>'
            '<td><span class="kw">腹痛・腸管虚血</span></td>'
            '<td>急性腹症</td></tr>'
            '<tr><td><span class="kw">腎動脈</span></td>'
            '<td><span class="kw">急性腎障害・高血圧</span></td>'
            '<td>—</td></tr>'
            '<tr><td><span class="kw">腸骨・大腿動脈</span></td>'
            '<td><span class="kw">下肢虚血・対麻痺（脊髄動脈）</span></td>'
            '<td>—</td></tr>'
            '<tr><td><span class="kw3">大動脈弁輪・心囊</span></td>'
            '<td><span class="kw3">急性大動脈弁閉鎖不全・'
            '心タンポナーデ</span></td>'
            '<td><span class="kw">心不全・ショック</span></td></tr></table>'
            '<span class="kw4">⚠️ 大動脈解離を「急性冠症候群」や'
            '「脳梗塞」と誤診して抗血栓薬・t-PAを投与することが'
            '最も避けたい事故</span>——'
            '<span class="kw3">だからQ.29で「まず造影CTで解離を確認する」に'
            'つながる</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">肺血栓塞栓症は低酸素血症を伴う</span>'
             '——SpO<sub>2</sub>正常なら可能性は低い。<br>'
             '② <span class="kw">肺塞栓の心電図＝'
             'S<sub>1</sub>Q<sub>3</sub>T<sub>3</sub>・'
             'V<sub>1-3</sub>陰性T・右脚ブロック・洞性頻脈</span>。<br>'
             '③ <span class="kw3">大動脈解離は分枝の巻き込みで'
             '心筋梗塞・脳梗塞・腸管虚血・下肢虚血を二次的に起こす</span>。<br>'
             '④ <span class="kw4">解離を見落として抗血栓療法・t-PAを行うと致命的</span>。<br>'
             '⑤ <span class="kw">急性胸痛では致死的5疾患'
             '（解離・ACS・肺塞栓・緊張性気胸・食道破裂）を先に潰す</span>。')),

    # ── NO.29 (114C-71) 89% ans=b ──────────────────────────────
    Q('114C-71', 89, [],
      _STEM_27 + '<strong>治療方針決定のために優先される検査はどれか。</strong>',
      [('a', '心臓MRI', False,
        '<span class="kw4">MRIは撮像に時間がかかり、'
        '検査中は患者に近づけない</span>。'
        '<span class="kw4">ショック状態（血圧78/62mmHg）で'
        '刻一刻と状態が変わる患者を'
        'MRIの筒の中に入れるのは危険</span>。'
        '<span class="kw4">「状態が不安定な患者はMRIの禁忌」</span>という'
        '原則がここで効く。'),
       ('b', '胸部造影CT', True,
        '<span class="kw3">◯ 急性大動脈解離が疑われる患者で'
        '最優先されるのは造影CT</span>。'
        '<span class="kw3">数分で撮れて、'
        '①解離腔（フラップ）の有無 '
        '②解離の範囲（上行大動脈に及ぶか＝Stanford分類）'
        '③分枝の巻き込み ④心囊液・胸腔内／縦隔血腫の有無 '
        '⑤破裂の切迫を一度に評価できる</span>。'
        '<span class="kw3">この情報がそのまま治療方針を決める</span>——'
        '<span class="kw3">上行大動脈に及ぶStanford A型なら緊急手術、'
        'B型なら降圧を中心とした保存的治療</span>。'
        '<span class="kw">撮影範囲は頸部〜骨盤まで広くとる</span>。'),
       ('c', '冠動脈造影CT', False,
        '<span class="kw4">心電図に下壁のST上昇があるので'
        '選びたくなる肢</span>だが、'
        '<span class="kw4">冠動脈造影CTは心電図同期で'
        '冠動脈だけを詳細に見る検査</span>であり、'
        '<span class="kw4">大動脈全体の解離の範囲を評価する目的には合わない</span>。'
        '<span class="kw3">そもそも本例のST上昇は'
        '「解離が右冠動脈入口部に及んだ結果」と考えられ、'
        '治療は冠動脈への介入ではなく解離そのものの手術</span>である。'
        '<span class="kw4">解離を確認せずに冠動脈造影・PCIへ進むと'
        '致命的になりうる</span>。'),
       ('d', 'D ダイマー測定', False,
        '<span class="kw4">D-ダイマーは大動脈解離でも上昇するが、'
        '特異度が低く（肺塞栓・DIC・悪性腫瘍・感染・術後でも上がる）、'
        '「治療方針を決める」情報にはならない</span>。'
        '<span class="kw3">陰性なら解離の可能性を下げる'
        '（除外に使える）という位置づけ</span>で、'
        '<span class="kw4">本例のように臨床的に強く疑われる状況では'
        '結果を待つ時間が無駄</span>。'),
       ('e', '心筋トロポニンT 測定', False,
        '<span class="kw4">トロポニンは心筋傷害のマーカーで、'
        '本例でも上昇しうる</span>。'
        '<span class="kw4">しかし「心筋が傷んでいる」ことが分かっても'
        '原因が解離か一次性のACSかは区別できず、'
        '治療方針は決まらない</span>。'
        '<span class="kw4">むしろ「心筋梗塞だ」と判断して'
        '抗血栓療法を始めると解離を悪化させる</span>。')],
      '解離を疑ったら造影CT。範囲（Stanford分類）が手術かどうかを直接決める。',
      imgs=[IMG + '114C-71_1.jpeg', IMG + '114C-71_2.jpeg'],
      patho=('🔎 急性大動脈解離——Stanford分類が治療を決める',
             '<span class="kw3">大動脈解離の治療方針は'
             '「上行大動脈に解離が及んでいるかどうか」の一点で決まる</span>。'
             '<table class="tb"><tr><th></th>'
             '<th><span class="kw3">Stanford A型</span></th>'
             '<th><span class="kw3">Stanford B型</span></th></tr>'
             '<tr><td>範　囲</td>'
             '<td><span class="kw3">上行大動脈に解離が及ぶ</span></td>'
             '<td><span class="kw3">上行大動脈に及ばない'
             '（左鎖骨下動脈より遠位）</span></td></tr>'
             '<tr><td><span class="kw3">治　療</span></td>'
             '<td><span class="kw3">緊急手術（人工血管置換術）</span></td>'
             '<td><span class="kw3">原則は保存的治療'
             '（降圧・心拍数の管理）</span>。'
             '<span class="kw">合併症例（破裂・臓器虚血・'
             '難治性疼痛）はステントグラフト内挿術／手術</span></td></tr>'
             '<tr><td>理　由</td>'
             '<td><span class="kw4">心タンポナーデ・大動脈弁閉鎖不全・'
             '冠動脈閉塞・破裂で急速に死亡する'
             '（無治療では発症48時間以内に約半数が死亡）</span></td>'
             '<td><span class="kw">上記の合併症が起こりにくい</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">薬物療法は'
             '「血圧」と「dP/dt（血圧の立ち上がりの勢い）」を'
             '同時に下げることが要点</span>——'
             '<span class="kw3">まずβ遮断薬で心拍数を60/分程度へ落とし、'
             'そのうえで血管拡張薬を加える</span>。'
             '<span class="kw4">血管拡張薬を先に使うと反射性頻脈で'
             'dP/dtが上がり解離を進展させる</span>。<br>'
             '<span class="kw4">⚠️ ただし本例のようにショック'
             '（心タンポナーデ）を伴う場合は降圧よりも'
             '緊急手術・心囊ドレナージが優先される</span>。</td></tr></table>'),
      deep=('💡 造影CTが「治療方針を決める検査」になる理由',
            '<span class="kw3">検査を選ぶ基準は'
            '「その結果で次の行動が変わるか」</span>である。'
            '<table class="tb"><tr><th>検査</th>'
            '<th>得られる情報</th><th>治療方針が変わるか</th></tr>'
            '<tr><td><span class="kw3">胸部造影CT</span></td>'
            '<td><span class="kw3">解離の有無・範囲（A型かB型か）・'
            '分枝の巻き込み・心囊液・破裂の切迫</span></td>'
            '<td><span class="kw3">◎ 緊急手術か保存的治療かが直接決まる</span></td></tr>'
            '<tr><td><span class="kw">経食道心エコー</span></td>'
            '<td><span class="kw">上行大動脈のフラップ・'
            '大動脈弁逆流・心囊液</span></td>'
            '<td><span class="kw">◯ ベッドサイドで可能で、'
            '搬送できないほど不安定な場合の代替になる</span></td></tr>'
            '<tr><td><span class="kw">経胸壁心エコー</span></td>'
            '<td><span class="kw3">心囊液・大動脈弁逆流・'
            '上行大動脈の拡大</span></td>'
            '<td><span class="kw3">◯ 数十秒でできるので'
            'CTの前に当てる（心タンポナーデの確認）</span></td></tr>'
            '<tr><td><span class="kw4">D-ダイマー</span></td>'
            '<td><span class="kw4">解離の可能性（特異度が低い）</span></td>'
            '<td><span class="kw4">△ 除外には使えるが確定できない</span></td></tr>'
            '<tr><td><span class="kw4">トロポニン</span></td>'
            '<td><span class="kw4">心筋傷害の有無</span></td>'
            '<td><span class="kw4">× 原因が特定できない</span></td></tr>'
            '<tr><td><span class="kw4">MRI</span></td>'
            '<td>解離の詳細（画質は良い）</td>'
            '<td><span class="kw4">× 時間がかかり不安定な患者に使えない</span></td></tr>'
            '</table>'
            '<span class="kw3">救急では「情報の精度」より'
            '「その情報が今すぐ手に入り、'
            '次の一手を決められるか」で検査を選ぶ</span>——'
            '<span class="kw3">造影CTが第一選択なのは、'
            '速くて、範囲が広くて、治療方針に直結するから</span>である。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">急性大動脈解離を疑ったら造影CT</span>'
             '（頸部〜骨盤まで）。<br>'
             '② <span class="kw3">Stanford A型（上行に及ぶ）＝緊急手術／'
             'B型＝原則保存的（降圧）</span>。<br>'
             '③ <span class="kw3">薬物療法はまずβ遮断薬で心拍数を落としてから'
             '血管拡張薬</span>（dP/dtを下げる）。<br>'
             '④ <span class="kw4">状態が不安定な患者にMRIは使えない</span>。<br>'
             '⑤ <span class="kw4">D-ダイマー・トロポニンは治療方針を決められない</span>。')),

    # ── NO.30 (114A-7) 84% ans=a ───────────────────────────────
    Q('114A-7', 84, [],
      '<strong>疾患と治療の組合せで正しいのはどれか。</strong>',
      [('a', '多発肝細胞癌 ――― 経カテーテル的動脈化学塞栓術〈TACE〉', True,
        '<span class="kw3">◯ 正しい組合せ</span>。'
        '<span class="kw3">肝細胞癌は肝動脈から栄養される（多血性腫瘍）</span>のに対し、'
        '<span class="kw3">正常肝は約7割を門脈から養われている</span>——'
        '<span class="kw3">この血流の違いを利用して'
        '肝動脈だけを塞栓すれば、'
        '腫瘍を選択的に壊死させて正常肝を残せる</span>。'
        '<span class="kw3">抗癌薬をリピオドール（油性ヨード造影剤）に懸濁して'
        '腫瘍血管に注入し、ゼラチンスポンジなどで塞栓する</span>。'
        '<span class="kw3">切除もラジオ波焼灼も難しい多発例が'
        'よい適応</span>である。'
        '<span class="kw4">門脈本幹が閉塞している例では'
        '肝動脈まで止めると肝梗塞になるので禁忌</span>。'),
       ('b', '胆石合併胆囊癌 ――― 腹腔鏡下胆囊摘出術', False,
        '<span class="kw4">胆囊癌に腹腔鏡下胆囊摘出術は不適</span>。'
        '<span class="kw4">術中に胆囊を破って腹腔内に播種させる危険があり、'
        'ポート部再発も知られている</span>。'
        '<span class="kw3">胆囊癌の標準術式は開腹による'
        '胆囊摘出＋肝床部切除＋リンパ節郭清（深達度に応じて拡大）</span>。'
        '<span class="kw">（胆石症に対する腹腔鏡下胆囊摘出術後に'
        '偶発的に癌が見つかることはあり、その場合は追加切除を検討する）</span>'),
       ('c', '特発性門脈圧亢進症 ――― 門脈内ステント留置', False,
        '<span class="kw4">特発性門脈圧亢進症〈IPH〉は'
        '肝内末梢門脈枝の閉塞・線維化による肝前性〜類洞前性の門脈圧亢進</span>で、'
        '<span class="kw4">門脈本幹に狭窄があるわけではない</span>ため'
        '<span class="kw4">ステントを置く場所がない</span>。'
        '<span class="kw3">治療は食道・胃静脈瘤の管理（内視鏡的治療）と'
        '脾機能亢進に対する脾摘・部分的脾動脈塞栓術〈PSE〉</span>。'
        '<span class="kw">肝機能は比較的保たれるので予後は肝硬変より良い</span>。'),
       ('d', '膵管内乳頭粘液性腫瘍 ――― 膵管ステント留置', False,
        '<span class="kw4">IPMNは膵管内に粘液を産生する腫瘍性病変で、'
        '主膵管型・分枝型・混合型に分かれる</span>。'
        '<span class="kw3">対応は「経過観察」か「切除」の二択</span>で、'
        '<span class="kw4">ステントを置いても粘液で詰まるだけで意味がない</span>。'
        '<span class="kw">主膵管の拡張（10mm以上）・造影される壁在結節・'
        '閉塞性黄疸などのhigh-risk stigmataがあれば切除</span>。'),
       ('e', '急性化膿性閉塞性胆管炎 ――― 胆管切除術', False,
        '<span class="kw4">急性閉塞性化膿性胆管炎〈AOSC〉は'
        '敗血症性ショックに至る緊急病態</span>で、'
        '<span class="kw3">やるべきことは「胆道ドレナージ」であって切除ではない</span>。'
        '<span class="kw3">抗菌薬と全身管理を行いながら、'
        '緊急でENBD／EBS（内視鏡的経鼻胆道ドレナージ／胆道ステント）'
        'またはPTBD（経皮経肝胆道ドレナージ）を行う</span>。'
        '<span class="kw4">原因（結石・腫瘍）の根治的治療は'
        '感染が鎮まってから</span>——'
        '<span class="kw3">「膿があるところは、まずドレナージ」</span>。')],
      '肝細胞癌は肝動脈支配・正常肝は門脈支配。この差を使うのがTACE。',
      patho=('🔎 IVRの5つの動作——「詰める・広げる・入れる・焼く・取る」',
             '<span class="kw3">インターベンショナルラジオロジー〈IVR〉は'
             '画像で体内を透視しながらカテーテルや針で治療する手技</span>。'
             '<span class="kw3">やっていることは5つの動作に整理できる</span>。'
             + TBL_IVR),
      deep=('💡 TACEが成立する理由——肝臓の「二重支配」',
            '<span class="kw3">肝臓は肝動脈と門脈という'
            '2本の血管から血流を受ける唯一の臓器</span>である。'
            '<table class="tb"><tr><th></th><th>正常肝</th>'
            '<th><span class="kw3">肝細胞癌</span></th></tr>'
            '<tr><td><span class="kw3">血流の由来</span></td>'
            '<td><span class="kw3">門脈 約70%＋肝動脈 約30%</span></td>'
            '<td><span class="kw3">ほぼ100%が肝動脈</span></td></tr>'
            '<tr><td>造影CTでの見え方</td>'
            '<td>門脈相で最も濃染</td>'
            '<td><span class="kw3">動脈相で強く濃染し、'
            '門脈相〜平衡相で周囲より低吸収になる〈washout〉</span></td></tr>'
            '<tr><td><span class="kw3">肝動脈を塞栓すると</span></td>'
            '<td><span class="kw3">門脈があるので壊死しない</span></td>'
            '<td><span class="kw3">血流が絶たれて壊死する</span></td></tr></table>'
            '<span class="kw3">この「腫瘍だけが肝動脈に依存している」という'
            '性質があるからTACEが成り立つ</span>。'
            '<span class="kw3">同じ理屈で、造影CTの'
            '「動脈相での濃染＋門脈相でのwashout」が'
            '肝細胞癌の診断根拠になる</span>——'
            '<span class="kw3">診断と治療が同じ血行動態の上に乗っている</span>。'
            '<table class="tb"><tr><th>肝細胞癌の治療</th><th>適応の目安</th></tr>'
            '<tr><td><span class="kw">肝切除</span></td>'
            '<td><span class="kw">肝機能が保たれ、腫瘍数が少ない</span></td></tr>'
            '<tr><td><span class="kw">ラジオ波焼灼療法〈RFA〉</span></td>'
            '<td><span class="kw">3cm以下・3個以下</span></td></tr>'
            '<tr><td><span class="kw3">TACE</span></td>'
            '<td><span class="kw3">多発（切除・焼灼の適応外）だが'
            '肝機能が保たれ、脈管侵襲・遠隔転移がない</span></td></tr>'
            '<tr><td><span class="kw">薬物療法（分子標的薬・'
            '免疫チェックポイント阻害薬）</span></td>'
            '<td><span class="kw">脈管侵襲・遠隔転移がある</span></td></tr>'
            '<tr><td><span class="kw">肝移植</span></td>'
            '<td><span class="kw">Milan基準内で肝機能不良</span></td></tr></table>'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">多発肝細胞癌＝TACE</span>。'
             '<span class="kw3">腫瘍は肝動脈支配、正常肝は門脈支配</span>。<br>'
             '② <span class="kw4">門脈本幹閉塞例へのTACEは禁忌（肝梗塞）</span>。<br>'
             '③ <span class="kw4">胆囊癌に腹腔鏡下胆囊摘出術は不適（播種）</span>。<br>'
             '④ <span class="kw3">急性閉塞性化膿性胆管炎は緊急胆道ドレナージ</span>'
             '（ENBD／EBS／PTBD）。<br>'
             '⑤ <span class="kw">IPMNは経過観察か切除。'
             '特発性門脈圧亢進症は静脈瘤治療と脾摘／PSE</span>。')),

    # ── NO.31 (112C-13) 67% ans=a ──────────────────────────────
    Q('112C-13', 67, [],
      '<strong>疾患と用いられる治療との組合せで<u>誤っている</u>のはどれか。</strong>',
      [('a', '洞性頻脈 ――― カテーテルアブレーション', True,
        '<span class="kw3">◯ これが誤り。洞性頻脈は「不整脈」ではなく'
        '<u>洞結節が正常に反応した結果</u></span>である。'
        '<span class="kw3">発熱・脱水・貧血・疼痛・不安・甲状腺機能亢進症・'
        '心不全・低酸素・出血といった原因があって'
        '心拍数が上がっているのだから、'
        '治療すべきは原因のほう</span>。'
        '<span class="kw4">洞結節を焼灼すれば'
        '必要なときに心拍数を上げられなくなり、'
        '洞不全症候群を作ってペースメーカが必要になる</span>——'
        '<span class="kw4">「体の正常な代償反応を壊す」ことになる</span>。<br>'
        '<span class="kw">カテーテルアブレーションの適応は'
        '発作性上室頻拍（WPW症候群・房室結節リエントリー）・'
        '心房粗動・心房細動・心室頻拍など、'
        '<u>異常な旋回路や異常自動能</u>をもつ不整脈</span>である。'),
       ('b', '急性冠症候群 ――― 経皮的冠動脈インターベンション', False,
        '<span class="kw3">正しい組合せ</span>。'
        '<span class="kw3">ST上昇型心筋梗塞〈STEMI〉では'
        '発症からできるだけ早く（door-to-balloon 90分以内を目標に）'
        '責任血管を再開通させる</span>。'
        '<span class="kw">バルーン拡張＋薬剤溶出性ステント留置が標準</span>。'
        '<span class="kw3">IVRの「広げる」動作の代表例</span>。'),
       ('c', '頸動脈狭窄症 ――― ステント留置術', False,
        '<span class="kw3">正しい組合せ</span>。'
        '<span class="kw">頸動脈狭窄症の血行再建には'
        '頸動脈内膜剝離術〈CEA〉と'
        '頸動脈ステント留置術〈CAS〉の2つ</span>があり、'
        '<span class="kw">高齢・心肺合併症・対側閉塞・'
        '頸部放射線照射後・手術到達が困難な高位病変では'
        'CASが選ばれる</span>。'
        '<span class="kw">遠位塞栓を防ぐプロテクションデバイスを併用する</span>。'),
       ('d', '腹部大動脈瘤 ――― ステントグラフト留置術', False,
        '<span class="kw3">正しい組合せ</span>。'
        '<span class="kw3">ステントグラフト内挿術〈EVAR〉は'
        '大腿動脈から人工血管を折りたたんで挿入し、'
        '瘤の内側で展開して血流を通す</span>。'
        '<span class="kw3">開腹による人工血管置換術に比べて低侵襲</span>で、'
        '<span class="kw">高齢・併存疾患の多い症例に適する</span>。'
        '<span class="kw4">エンドリーク（瘤内への血流の残存）の'
        '長期フォローが必要</span>。'),
       ('e', '閉塞性動脈硬化症 ――― ステント留置術', False,
        '<span class="kw3">正しい組合せ</span>。'
        '<span class="kw">間欠性跛行や重症下肢虚血に対して、'
        'バルーン拡張＋ステント留置（EVT／血管内治療）を行う</span>。'
        '<span class="kw">腸骨動脈・浅大腿動脈が代表的な治療部位'
        '（NO.32参照）</span>。'
        '<span class="kw">なお軽症では運動療法・薬物療法・'
        '危険因子の管理が基本</span>。')],
      '洞性頻脈は正常な代償反応。焼灼するのは異常な旋回路をもつ不整脈だけ。',
      patho=('🔎 カテーテルアブレーションの適応——「異常な回路があるか」',
             '<span class="kw3">アブレーションは'
             '「不整脈の原因となっている心筋の一部を焼いて'
             '電気的に切り離す」治療</span>。'
             '<span class="kw3">したがって適応があるのは'
             '「焼くべき異常な回路・異常な起源が存在する」不整脈だけ</span>である。'
             '<table class="tb"><tr><th>不整脈</th><th>機序</th>'
             '<th>アブレーション</th></tr>'
             '<tr><td><span class="kw3">WPW症候群'
             '（房室回帰頻拍）</span></td>'
             '<td><span class="kw3">副伝導路（Kent束）</span></td>'
             '<td><span class="kw3">◎ 副伝導路を焼灼＝根治的</span></td></tr>'
             '<tr><td><span class="kw3">房室結節リエントリー性頻拍</span></td>'
             '<td><span class="kw3">房室結節内の二重伝導路</span></td>'
             '<td><span class="kw3">◎ 遅伝導路を焼灼</span></td></tr>'
             '<tr><td><span class="kw3">心房粗動</span></td>'
             '<td><span class="kw3">三尖弁輪を旋回するリエントリー</span></td>'
             '<td><span class="kw3">◎ 三尖弁輪-下大静脈間峡部を焼灼</span></td></tr>'
             '<tr><td><span class="kw3">心房細動</span></td>'
             '<td><span class="kw3">肺静脈起源の異常興奮</span></td>'
             '<td><span class="kw3">◯ 肺静脈隔離術</span></td></tr>'
             '<tr><td><span class="kw">心室頻拍・期外収縮</span></td>'
             '<td><span class="kw">異常自動能・リエントリー</span></td>'
             '<td><span class="kw">◯ 起源を同定して焼灼</span></td></tr>'
             '<tr><td><span class="kw4">洞性頻脈</span></td>'
             '<td><span class="kw4">洞結節の<u>正常な</u>反応</span></td>'
             '<td><span class="kw4">× 適応なし——原因を治療する</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">「頻脈だから焼く」ではない</span>。'
             '<span class="kw3">洞性頻脈をみたら'
             '発熱・脱水・貧血・疼痛・低酸素・出血・'
             '甲状腺機能亢進症・心不全といった'
             '<u>背後の原因</u>を探す</span>のが正しい。</td></tr></table>'),
      deep=('💡 「ステント」と「ステントグラフト」は別物',
            '<span class="kw3">名前が似ているが、'
            'やっていることも適応もまったく違う</span>。'
            '<table class="tb"><tr><th></th>'
            '<th><span class="kw3">ステント</span></th>'
            '<th><span class="kw3">ステントグラフト</span></th></tr>'
            '<tr><td>構　造</td>'
            '<td><span class="kw3">金属メッシュの筒（網目が開いている）</span></td>'
            '<td><span class="kw3">金属の骨格に人工血管の膜を貼った筒'
            '（内腔が閉じている）</span></td></tr>'
            '<tr><td>目　的</td>'
            '<td><span class="kw3">狭くなった血管を内側から支えて広げる</span></td>'
            '<td><span class="kw3">瘤や解離の部分をバイパスして'
            '血流を内側の管に通し、瘤壁に圧をかけない</span></td></tr>'
            '<tr><td>適　応</td>'
            '<td><span class="kw3">冠動脈狭窄・頸動脈狭窄症・'
            '閉塞性動脈硬化症・腎動脈狭窄</span></td>'
            '<td><span class="kw3">胸部／腹部大動脈瘤・'
            'Stanford B型大動脈解離</span></td></tr>'
            '<tr><td>合併症</td>'
            '<td><span class="kw">再狭窄・ステント血栓症'
            '（抗血小板薬が要る）</span></td>'
            '<td><span class="kw4">エンドリーク（瘤内へ血流が残る）・'
            '脊髄虚血</span></td></tr></table>'
            '<span class="kw3">「狭いところを広げるのがステント、'
            '膨らんだところを内張りするのがステントグラフト」</span>と'
            '覚えると取り違えない。'
            '<span class="kw3">NO.34では「肺動静脈瘻にフィルター留置」という'
            '同種の取り違えが問われている</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw4">洞性頻脈はアブレーションの適応ではない</span>'
             '——<span class="kw3">原因（発熱・脱水・貧血・疼痛・'
             '甲状腺機能亢進症など）を治す</span>。<br>'
             '② <span class="kw3">アブレーションの適応＝WPW症候群・'
             '房室結節リエントリー性頻拍・心房粗動・心房細動・心室頻拍</span>。<br>'
             '③ <span class="kw3">ステント＝狭窄を広げる／'
             'ステントグラフト＝瘤を内張りする</span>。<br>'
             '④ <span class="kw">頸動脈狭窄症＝CEAまたはCAS</span>。<br>'
             '⑤ <span class="kw">STEMIはdoor-to-balloon 90分以内のPCI</span>。')),

]
