
QUESTIONS += [

    # ============================ 無印問題 ============================

    # ── NO.20 (117F-68) 89% ans=a ──────────────────────────────
    Q('117F-68', 89, [],
      '<span class="kw">次の文を読み、Q.20〜Q.22 の問いに答えよ。</span><br>'
      '76 歳の女性。歩行障害を主訴に来院した。<br>'
      '<b>現病歴：</b><span class="kw">6 年前から左上肢の動かしにくさが出現し、'
      '4 年前から歩くのが遅くなった。4 年前から自宅近くの診療所で'
      'レボドパ〈L-dopa〉を処方され症状は改善した。'
      '1 年前から内服薬の効果が持続しなくなり、歩行困難が進行した。'
      '半年前から、歩行中に足が止まってしまうことがあり、'
      '2 回転倒したため専門外来を受診した。</span><br>'
      '<b>既往歴：</b>脂質異常症でスタチンを内服している。<br>'
      '<b>生活歴：</b>喫煙歴、飲酒歴はない。転倒しないようにほとんど外出しない。'
      '室内のトイレ歩行などの日常生活動作は自立している。<br>'
      '<b>家族歴：</b>特記すべきことはない。<br>'
      '<b>現　症：</b>意識は清明。身長158cm、体重45kg。体温36.2℃。脈拍64/ 分、整。'
      '血圧110/60mmHg。胸腹部に異常を認めない。'
      '<span class="kw">神経診察では仮面様顔貌、小声および摂食時のむせこみを認める。'
      '四肢筋強剛、動作緩慢を認める。筋力低下、感覚低下は認めない。</span><br>'
      '<b>検査所見：</b>血液所見：赤血球340 万、Hb 11.2g/dL、白血球6,300、血小板13 万。'
      '血液生化学所見：総蛋白6.3g/dL、アルブミン4.5g/dL、総ビリルビン0.2mg/dL、'
      'AST 24U/L、ALT 18U/L、LD 160U/L（基準120 ～245）、γ-GT 41U/L（基準8 ～50）、'
      'CK 58U/L（基準30 ～140）、尿素窒素18mg/dL、クレアチニン0.6mg/dL、'
      '血糖98mg/dL、Na 138mEq/L、K 4.0mEq/L、Cl 97mEq/L。CRP 0.2mg/dL。<br>'
      '今回、撮像したドパミントランスポーターSPECT（A）と'
      '<sup>123</sup>I-MIBG 交感神経心筋シンチグラム（B）を示す。<br>'
      '<strong>診断はどれか。</strong>',
      [('a', 'Parkinson 病', True,
        '<span class="kw3">◯ Parkinson病の典型例</span>。'
        '<span class="kw3">①左上肢から始まった＝左右非対称の発症 '
        '②L-dopaが著効した ③仮面様顔貌・小声・筋強剛・動作緩慢という'
        '4徴のうち3つが揃う ④経過とともにwearing off（薬効の短縮）と'
        'すくみ足・姿勢反射障害が出てきた</span>——'
        '<span class="kw3">いずれもParkinson病の教科書的な経過</span>である。'
        '<span class="kw3">画像でもドパミントランスポーターの'
        '線条体集積が低下し、かつMIBG心筋シンチの集積も低下しており、'
        'この2つが揃うのはParkinson病とLewy小体型認知症だけ</span>。'
        '<span class="kw">認知症の記載がないので前者</span>。'),
       ('b', '多系統萎縮症', False,
        '<span class="kw4">MSAは自律神経障害（起立性低血圧・排尿障害）・'
        '小脳失調・錐体路徴候を伴い、L-dopaの効果は乏しい</span>。'
        '<span class="kw4">本例はL-dopaが著効しており（4年前から症状が改善）、'
        '自律神経症状・失調の記載もない</span>。'
        '<span class="kw3">またMSAではMIBG心筋シンチの集積が'
        '保たれる（正常〜軽度低下）</span>のが鑑別点。'),
       ('c', '進行性核上性麻痺', False,
        '<span class="kw4">PSPは①発症早期からの易転倒 '
        '②垂直性核上性眼球運動障害 ③頸部優位の筋強剛 '
        '④L-dopa無効</span>が特徴（NO.13参照）。'
        '<span class="kw4">本例はL-dopaが効き、'
        '転倒が出たのも発症6年後、眼球運動障害の記載もない</span>。'
        '<span class="kw3">MIBG心筋シンチも保たれるはず</span>。'),
       ('d', '大脳皮質基底核変性症', False,
        '<span class="kw4">CBDは著明な左右差に加えて'
        '肢節運動失行・観念運動失行・皮質性感覚障害・'
        '他人の手徴候といった大脳皮質症状を伴う</span>。'
        '<span class="kw4">L-dopaは無効で、本例の経過と合わない</span>。'),
       ('e', '薬剤性Parkinson 症候群', False,
        '<span class="kw4">薬剤性パーキンソニズムの原因は'
        '抗精神病薬・制吐薬（メトクロプラミド）・'
        'スルピリド・一部のカルシウム拮抗薬</span>で、'
        '<span class="kw4">本例の内服はスタチンのみ</span>。'
        '<span class="kw3">加えて薬剤性ではドパミントランスポーターの'
        '集積は正常</span>——'
        '<span class="kw3">シナプス前のドパミン神経は生きていて、'
        '受容体が遮断されているだけ</span>だからである。'
        '<span class="kw3">DaTスキャンはまさにこの鑑別のために使う</span>。')],
      '左右非対称の発症＋L-dopa著効＋DaT低下＋MIBG低下＝Parkinson病。',
      imgs=[IMG + '117F-68_1.jpeg', IMG + '117F-68_2.jpeg'],
      patho=('🔎 画像所見——線条体の集積低下と、心臓のMIBG集積低下',
             '<span class="kw3">A（ドパミントランスポーターSPECT）は'
             '線条体（被殻・尾状核）の集積を見る</span>。'
             '<span class="kw3">正常では左右対称の「コンマ（，）状」の'
             '強い集積として描出されるが、'
             'Parkinson病では被殻後部から集積が落ち、'
             'コンマが短く丸い「点状」に変形する</span>。'
             '<span class="kw3">しかも<u>左右差を伴う</u>のがParkinson病の特徴</span>'
             '（本例は左上肢から発症＝右半球側が強く障害される）。<br>'
             '<span class="kw3">B（<sup>123</sup>I-MIBG心筋シンチグラム）では'
             '早期相・遅延相ともに心臓への集積を評価する</span>。'
             '<span class="kw3">本患者では正常対照と比べて'
             '心臓の描出が乏しく＝心筋交感神経終末の変性を示す</span>。'
             '<span class="kw3">Parkinson病では中枢だけでなく'
             '末梢の自律神経系にもα-シヌクレインが蓄積する</span>ため、'
             '<span class="kw3">心臓のMIBG取り込みが低下する</span>。'
             '<table class="tb"><tr><th>疾患</th><th>DaTスキャン</th>'
             '<th>MIBG心筋シンチ</th><th>本例</th></tr>'
             '<tr><td><span class="kw3">Parkinson病</span></td>'
             '<td><span class="kw3">低下（左右差あり）</span></td>'
             '<td><span class="kw3">低下</span></td>'
             '<td><span class="kw3">合致</span></td></tr>'
             '<tr><td>Lewy小体型認知症</td><td>低下</td><td>低下</td>'
             '<td><span class="kw4">認知症・幻視の記載なし</span></td></tr>'
             '<tr><td>PSP／MSA／CBD</td>'
             '<td><span class="kw">低下（左右差に乏しい）</span></td>'
             '<td><span class="kw">正常〜軽度低下</span></td>'
             '<td><span class="kw4">MIBGが低下していて合わない</span></td></tr>'
             '<tr><td>薬剤性／本態性振戦／Alzheimer型</td>'
             '<td><span class="kw4">正常</span></td>'
             '<td>正常（Alzheimer型）</td>'
             '<td><span class="kw4">DaTが低下していて合わない</span></td></tr>'
             '<tr><td colspan="4"><span class="kw3">2つの核医学検査は'
             '「変性か否か」（DaT）と「自律神経を巻き込むか」（MIBG）を'
             '別々に測っている</span>——'
             '<span class="kw3">組み合わせて初めて鑑別できる</span>。</td></tr></table>'),
      deep=('💡 Parkinson病の経過——「効いていた薬が効かなくなる」まで',
            '<span class="kw3">本例の病歴は、Parkinson病の'
            '典型的な10年の経過をそのまま書いている</span>。'
            '<table class="tb"><tr><th>時期</th><th>本例の記載</th>'
            '<th>病態</th></tr>'
            '<tr><td><span class="kw3">6年前</span></td>'
            '<td><span class="kw3">左上肢の動かしにくさ</span></td>'
            '<td><span class="kw3">片側から発症（左右非対称）</span></td></tr>'
            '<tr><td>4年前</td>'
            '<td><span class="kw3">L-dopaで症状が改善</span></td>'
            '<td><span class="kw3">ハネムーン期——'
            '残存ニューロンがドパミンを貯蔵・放出できる</span></td></tr>'
            '<tr><td><span class="kw3">1年前</span></td>'
            '<td><span class="kw3">薬の効果が持続しなくなった</span></td>'
            '<td><span class="kw3">wearing off——'
            'ニューロンが減り貯蔵能が落ちて'
            '血中濃度に効果が直結するようになる</span></td></tr>'
            '<tr><td><span class="kw3">半年前</span></td>'
            '<td><span class="kw3">すくみ足・転倒</span></td>'
            '<td><span class="kw3">姿勢反射障害（Hoehn-Yahr Ⅲ度）</span>'
            '——<span class="kw4">L-dopaが効きにくい症状</span></td></tr>'
            '<tr><td>現在</td>'
            '<td><span class="kw">摂食時のむせこみ</span></td>'
            '<td><span class="kw4">嚥下障害</span>——'
            '<span class="kw4">誤嚥性肺炎が予後を規定する</span></td></tr></table>'
            '<span class="kw3">薬物療法で改善するのは'
            '無動・筋強剛・振戦（ドパミン系の症状）だけ</span>で、'
            '<span class="kw3">姿勢反射障害・すくみ足・嚥下障害・'
            '自律神経症状は薬では取れない</span>——'
            '<span class="kw3">だからリハビリテーションと環境調整が要る'
            '（Q.22へつながる）</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">Parkinson病＝左右非対称の発症＋L-dopa著効</span>。'
             '<span class="kw">4徴＝安静時振戦・筋強剛・無動／寡動・姿勢反射障害</span>。<br>'
             '② <span class="kw3">DaTスキャン低下＋MIBG心筋シンチ低下＝'
             'Parkinson病／Lewy小体型認知症</span>。<br>'
             '③ <span class="kw3">PSP・MSAではMIBGは保たれる</span>。'
             '<span class="kw3">薬剤性ではDaTが正常</span>。<br>'
             '④ <span class="kw">wearing off＝薬効時間の短縮（進行の指標）</span>。<br>'
             '⑤ <span class="kw4">姿勢反射障害・すくみ足・嚥下障害は'
             'L-dopaで改善しにくい</span>。')),

    # ── NO.21 (117F-69) CBT 86% ans=e ──────────────────────────
    Q('117F-69', 86, [('bc', 'CBT')],
      '<span class="kw">次の文を読み、Q.20〜Q.22 の問いに答えよ。</span><br>'
      '76 歳の女性。歩行障害を主訴に来院した。<br>'
      '<b>現病歴：</b><span class="kw">6 年前から左上肢の動かしにくさが出現し、'
      '4 年前から歩くのが遅くなった。4 年前から自宅近くの診療所で'
      'レボドパ〈L-dopa〉を処方され症状は改善した。'
      '1 年前から内服薬の効果が持続しなくなり、歩行困難が進行した。'
      '半年前から、歩行中に足が止まってしまうことがあり、'
      '2 回転倒したため専門外来を受診した。</span><br>'
      '<b>既往歴：</b>脂質異常症でスタチンを内服している。<br>'
      '<b>生活歴：</b>喫煙歴、飲酒歴はない。転倒しないようにほとんど外出しない。'
      '室内のトイレ歩行などの日常生活動作は自立している。<br>'
      '<b>家族歴：</b>特記すべきことはない。<br>'
      '<b>現　症：</b>意識は清明。身長158cm、体重45kg。体温36.2℃。脈拍64/ 分、整。'
      '血圧110/60mmHg。胸腹部に異常を認めない。'
      '<span class="kw">神経診察では仮面様顔貌、小声および摂食時のむせこみを認める。'
      '四肢筋強剛、動作緩慢を認める。筋力低下、感覚低下は認めない。</span><br>'
      '<b>検査所見：</b>血液・血液生化学所見に特記すべき異常を認めない。<br>'
      '<strong>この患者に認められる可能性が高い症候はどれか。</strong>',
      [('a', '下肢痙縮', False,
        '<span class="kw4">痙縮は上位運動ニューロン障害（錐体路障害）の徴候</span>で、'
        '<span class="kw4">腱反射亢進・Babinski徴候陽性を伴う</span>。'
        '<span class="kw3">Parkinson病の筋緊張亢進は「痙縮」ではなく'
        '「筋強剛〈固縮〉」</span>——'
        '<span class="kw3">痙縮は速度依存性で折りたたみナイフ現象を示すのに対し、'
        '筋強剛は速度に依存せず鉛管様・歯車様に'
        '全可動域で一様に抵抗する</span>。'
        '<span class="kw3">この2つの区別は錐体路障害と'
        '錐体外路障害を分ける基本</span>である。'),
       ('b', '測定障害', False,
        '<span class="kw4">測定障害〈dysmetria〉は小脳性運動失調の徴候</span>'
        '（<span class="kw">指鼻試験・踵膝試験で目標を行き過ぎる／届かない</span>）。'
        '<span class="kw4">Parkinson病は基底核の疾患であり小脳症状は出ない</span>。'
        '<span class="kw">小脳失調が前面に出るなら'
        '多系統萎縮症（MSA-C）や脊髄小脳変性症を考える</span>。'),
       ('c', '姿勢時振戦', False,
        '<span class="kw4">姿勢時振戦（手を前に伸ばして保持したときに出る振戦）は'
        '本態性振戦の特徴</span>。'
        '<span class="kw3">Parkinson病の振戦は「安静時振戦」</span>——'
        '<span class="kw3">力を抜いて膝の上に置いているときに'
        '4〜6Hzの丸薬まるめ様運動〈pill-rolling〉として出現し、'
        '動作を始めると軽減する</span>。'
        '<span class="kw3">「いつ出るか」で振戦の種類が決まる</span>'
        '（安静時＝Parkinson病／姿勢時・企図時＝本態性振戦・小脳）。'),
       ('d', '眼球運動障害', False,
        '<span class="kw4">垂直性核上性眼球運動障害は'
        '進行性核上性麻痺〈PSP〉の特徴</span>（NO.13参照）。'
        '<span class="kw4">Parkinson病でも上方視の軽度制限や'
        '輻輳不全がみられることはあるが、'
        '「認められる可能性が高い症候」として選ぶものではない</span>。'),
       ('e', '姿勢反射障害', True,
        '<span class="kw3">◯ 姿勢反射障害はParkinson病の4徴のひとつ</span>で、'
        '<span class="kw3">本例では「歩行中に足が止まる（すくみ足）」'
        '「2回転倒した」という形ですでに現れている</span>。'
        '<span class="kw3">診察では後方への引き試験〈pull test〉で確認する</span>'
        '（<span class="kw">背後から肩を引いて、'
        '2歩以上の後方突進または介助を要すれば陽性</span>）。'
        '<span class="kw3">姿勢反射障害が出現するとHoehn-Yahr重症度分類Ⅲ度</span>で、'
        '<span class="kw3">介護保険の対象（特定疾病）となり、'
        '難病医療費助成の対象にもなる（Ⅲ度以上かつ生活機能障害度Ⅱ度以上）</span>——'
        '<span class="kw3">臨床的にも制度的にも大きな区切り</span>である。'
        '<span class="kw4">しかもL-dopaで改善しにくい</span>ので、'
        '<span class="kw3">転倒予防（住宅改修・歩行訓練）が'
        '治療の中心になる（Q.22へ）</span>。')],
      'Parkinson病の4徴＝安静時振戦・筋強剛・無動／寡動・姿勢反射障害。',
      patho=('🔎 Parkinson病の4徴と、紛らわしい所見の切り分け',
             '<span class="kw3">Parkinson病の主症状は4つ（TRAP）</span>——'
             '<span class="kw3">Tremor（安静時振戦）・Rigidity（筋強剛）・'
             'Akinesia／bradykinesia（無動・動作緩慢）・'
             'Postural instability（姿勢反射障害）</span>。'
             '<table class="tb"><tr><th>Parkinson病の所見</th>'
             '<th>紛らわしい所見</th><th>それはどの疾患か</th></tr>'
             '<tr><td><span class="kw3">安静時振戦</span>'
             '（4〜6Hz・丸薬まるめ様・動作で軽減）</td>'
             '<td><span class="kw4">姿勢時振戦・企図振戦</span></td>'
             '<td><span class="kw4">本態性振戦／小脳疾患</span></td></tr>'
             '<tr><td><span class="kw3">筋強剛〈固縮〉</span>'
             '（速度非依存・鉛管様／歯車様）</td>'
             '<td><span class="kw4">痙縮</span>'
             '（速度依存・折りたたみナイフ）</td>'
             '<td><span class="kw4">錐体路障害（脳梗塞・脊髄症）</span></td></tr>'
             '<tr><td><span class="kw3">無動・動作緩慢</span>'
             '（仮面様顔貌・小声・小字症・小刻み歩行）</td>'
             '<td><span class="kw4">筋力低下</span></td>'
             '<td><span class="kw4">運動ニューロン疾患・筋疾患</span>'
             '（本例は「筋力低下なし」と明記）</td></tr>'
             '<tr><td><span class="kw3">姿勢反射障害</span>'
             '（前傾前屈姿勢・突進現象・すくみ足・転倒）</td>'
             '<td><span class="kw4">失調性歩行・測定障害</span></td>'
             '<td><span class="kw4">小脳疾患</span></td></tr>'
             '<tr><td colspan="3"><span class="kw3">加えて非運動症状も重要</span>——'
             '<span class="kw3">嗅覚低下・便秘・REM睡眠行動障害は'
             '運動症状に数年〜十数年先行しうる</span>。'
             '<span class="kw3">起立性低血圧・排尿障害・うつ・認知機能低下も</span>。</td></tr>'
             '</table>'),
      deep=('💡 Hoehn-Yahr重症度分類——姿勢反射障害が出るⅢ度が境目',
            '<table class="tb"><tr><th>度</th><th>状態</th>'
            '<th>制度上の位置づけ</th></tr>'
            '<tr><td>Ⅰ</td><td><span class="kw">一側性のみ。機能障害はないか軽微</span></td>'
            '<td>—</td></tr>'
            '<tr><td>Ⅱ</td><td><span class="kw">両側性だが姿勢反射障害はない</span></td>'
            '<td>—</td></tr>'
            '<tr><td><span class="kw3">Ⅲ</span></td>'
            '<td><span class="kw3">姿勢反射障害が出現。'
            '日常生活に介助を要することがあるが自立可能</span></td>'
            '<td><span class="kw3">難病医療費助成の対象'
            '（生活機能障害度Ⅱ度以上と併せて）</span></td></tr>'
            '<tr><td>Ⅳ</td><td><span class="kw">起立・歩行など'
            '日常生活の一部に介助が必要</span></td><td>同上</td></tr>'
            '<tr><td>Ⅴ</td><td><span class="kw4">車椅子または'
            '寝たきり。全面的な介助が必要</span></td><td>同上</td></tr>'
            '<tr><td colspan="3"><span class="kw3">Parkinson病は'
            '40〜64歳でも介護保険を使える「特定疾病」の1つ</span>。<br>'
            '<span class="kw3">本例は「室内のトイレ歩行などの日常生活動作は自立」'
            'なのでⅢ度に相当する</span>。</td></tr></table>'
            '<span class="kw3">Ⅲ度が境目になるのは、'
            '姿勢反射障害＝転倒＝骨折・頭部外傷という'
            '生命予後に直結する事象が始まるから</span>である。'
            '<span class="kw4">しかもこの症状はL-dopaで改善しにくい</span>——'
            '<span class="kw3">だから薬を増やすのではなく'
            '環境と訓練で対応する（Q.22）</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">Parkinson病の4徴＝安静時振戦・筋強剛・'
             '無動／寡動・姿勢反射障害</span>。<br>'
             '② <span class="kw3">安静時振戦（4〜6Hz・丸薬まるめ様）</span>'
             '——<span class="kw4">姿勢時振戦は本態性振戦</span>。<br>'
             '③ <span class="kw3">筋強剛（速度非依存・歯車様）</span>'
             '——<span class="kw4">痙縮（速度依存）は錐体路障害</span>。<br>'
             '④ <span class="kw3">姿勢反射障害の出現＝Hoehn-Yahr Ⅲ度</span>'
             '（pull testで確認）。<br>'
             '⑤ <span class="kw">非運動症状（嗅覚低下・便秘・REM睡眠行動障害）は'
             '運動症状に先行しうる</span>。')),

    # ── NO.22 (117F-70) 97% ans=a,b,c ──────────────────────────
    Q('117F-70', 97, [],
      '<span class="kw">次の文を読み、Q.20〜Q.22 の問いに答えよ。</span><br>'
      '76 歳の女性。歩行障害を主訴に来院した。<br>'
      '<b>現病歴：</b><span class="kw">6 年前から左上肢の動かしにくさが出現し、'
      '4 年前から歩くのが遅くなった。4 年前から自宅近くの診療所で'
      'レボドパ〈L-dopa〉を処方され症状は改善した。'
      '1 年前から内服薬の効果が持続しなくなり、歩行困難が進行した。'
      '半年前から、歩行中に足が止まってしまうことがあり、'
      '2 回転倒したため専門外来を受診した。</span><br>'
      '<b>既往歴：</b>脂質異常症でスタチンを内服している。<br>'
      '<b>生活歴：</b>喫煙歴、飲酒歴はない。'
      '<span class="kw">転倒しないようにほとんど外出しない。'
      '室内のトイレ歩行などの日常生活動作は自立している。</span><br>'
      '<b>家族歴：</b>特記すべきことはない。<br>'
      '<b>現　症：</b>意識は清明。身長158cm、体重45kg。体温36.2℃。脈拍64/ 分、整。'
      '血圧110/60mmHg。胸腹部に異常を認めない。'
      '<span class="kw">神経診察では仮面様顔貌、小声および摂食時のむせこみを認める。'
      '四肢筋強剛、動作緩慢を認める。筋力低下、感覚低下は認めない。</span><br>'
      '<b>検査所見：</b>血液・血液生化学所見に特記すべき異常を認めない。<br>'
      '<strong>薬物療法で改善しない症状に対して、'
      '在宅生活を継続するために必要なのはどれか。3つ選べ。</strong>',
      [('a', '嚥下訓練', True,
        '<span class="kw3">◯ 「摂食時のむせこみ」＝嚥下障害があり、'
        'これはL-dopaで改善しにくい症状の代表</span>。'
        '<span class="kw3">Parkinson病患者の直接死因の第1位は誤嚥性肺炎</span>で、'
        '<span class="kw3">嚥下機能の評価（嚥下造影・嚥下内視鏡）と'
        '訓練（間接訓練・直接訓練）、食形態の調整（とろみ）、'
        'food test、口腔ケア</span>が生命予後に直結する。'
        '<span class="kw3">在宅生活の継続という観点でも最優先の項目</span>。'),
       ('b', '住宅改修', True,
        '<span class="kw3">◯ すくみ足と姿勢反射障害による転倒を'
        '環境の側から減らす</span>。'
        '<span class="kw3">手すりの設置・段差の解消・滑りにくい床材・'
        '動線の確保・トイレと浴室の改修</span>が典型で、'
        '<span class="kw3">介護保険の住宅改修費（要支援・要介護の認定があれば'
        '原則20万円まで）が使える</span>。'
        '<span class="kw3">Parkinson病は40〜64歳でも介護保険を使える'
        '特定疾病の1つ</span>で、'
        '<span class="kw3">本例（76歳）は当然対象</span>。'
        '<span class="kw">床の目印（テープ）やメトロノーム音などの'
        '外的手がかり〈cue〉ですくみ足が軽減する</span>のも住環境調整の一部。'),
       ('c', '歩行訓練', True,
        '<span class="kw3">◯ Parkinson病のリハビリテーションの中核</span>。'
        '<span class="kw3">とくに外的手がかりを用いた歩行訓練'
        '（床のライン・メトロノーム・号令に合わせて大きく一歩を出す）は'
        'すくみ足に有効</span>で、'
        '<span class="kw3">大きな動作を意識させるLSVT BIGなどの'
        'プログラムも用いられる</span>。'
        '<span class="kw3">本例は「転倒しないようにほとんど外出しない」＝'
        '廃用が進行する悪循環に入っている</span>——'
        '<span class="kw3">安静ではなく、安全に動く方法を教えるのが正しい</span>。'),
       ('d', '失語症訓練', False,
        '<span class="kw4">Parkinson病の「小声」は失語ではなく'
        '構音・発声の障害（運動低下性構音障害）</span>である。'
        '<span class="kw4">失語は言語の理解・表出そのものの障害</span>で、'
        '<span class="kw4">大脳皮質の言語野の病変（脳血管障害など）で起こる</span>——'
        '<span class="kw4">本例には失語を示唆する所見がない</span>。'
        '<span class="kw">必要なのは失語症訓練ではなく'
        '発声・構音訓練（LSVT LOUDなど）</span>。'),
       ('e', '短下肢装具', False,
        '<span class="kw4">短下肢装具の適応は下垂足・内反尖足</span>——'
        '<span class="kw4">総腓骨神経麻痺や脳卒中後の痙性麻痺</span>である。'
        '<span class="kw4">本例は「筋力低下、感覚低下は認めない」と明記されており、'
        '足関節の背屈は保たれている</span>。'
        '<span class="kw3">Parkinson病の歩行障害は麻痺ではなく'
        'すくみ・小刻み・突進</span>なので、'
        '<span class="kw4">足関節を固定しても改善せず、'
        'むしろ動きを制限して転倒を招きうる</span>。')],
      '薬で取れない症状（嚥下・すくみ・転倒）は訓練と環境で支える。失語も麻痺もない。',
      patho=('🔎 「薬物療法で改善しない症状」を数え上げる',
             '<span class="kw3">この設問は'
             '「L-dopaが効く症状／効かない症状」を'
             '分けられるかを問うている</span>。'
             '<table class="tb"><tr><th></th>'
             '<th><span class="kw3">薬物療法で改善する</span></th>'
             '<th><span class="kw3">薬物療法で改善しにくい</span></th></tr>'
             '<tr><td>症　状</td>'
             '<td><span class="kw3">無動・動作緩慢・筋強剛・'
             '安静時振戦</span></td>'
             '<td><span class="kw3">姿勢反射障害・すくみ足・'
             '嚥下障害・構音障害・自律神経症状・認知機能低下</span></td></tr>'
             '<tr><td>機　序</td>'
             '<td><span class="kw3">黒質線条体ドパミン系の障害</span></td>'
             '<td><span class="kw3">ドパミン以外の系'
             '（コリン・ノルアドレナリン・セロトニン）や'
             '皮質・脳幹の広範な変性</span></td></tr>'
             '<tr><td>対　応</td>'
             '<td><span class="kw">L-dopa・ドパミンアゴニスト・'
             'MAO-B阻害薬・COMT阻害薬</span>'
             '（進行例ではデバイス補助療法）</td>'
             '<td><span class="kw3">リハビリテーション'
             '（歩行訓練・嚥下訓練・発声訓練）＋'
             '環境調整（住宅改修・福祉用具）＋介護サービス</span></td></tr>'
             '<tr><td>本例で該当</td>'
             '<td>すでにL-dopaで治療中（wearing offあり）</td>'
             '<td><span class="kw3">すくみ足・転倒（→b・c）、'
             'むせこみ（→a）</span></td></tr></table>'
             '<span class="kw3">設問文が「薬物療法で改善しない症状に対して」と'
             '限定しているのは、'
             '答えを右列に絞らせるため</span>である。'),
      deep=('💡 在宅生活を支える3本柱——医療・リハ・制度',
            '<span class="kw3">「在宅生活を継続するために必要なもの」は'
            '医学的介入だけではない</span>。'
            '<table class="tb"><tr><th>柱</th><th>内容</th>'
            '<th>本例での具体</th></tr>'
            '<tr><td><span class="kw3">医　療</span></td>'
            '<td>薬物調整（wearing offへの対応）・'
            '合併症の管理</td>'
            '<td><span class="kw">L-dopaの分割投与、'
            'ドパミンアゴニスト／MAO-B阻害薬／COMT阻害薬の追加</span></td></tr>'
            '<tr><td><span class="kw3">リハビリテーション</span></td>'
            '<td><span class="kw3">歩行訓練・嚥下訓練・発声訓練・'
            '筋力／柔軟性の維持</span></td>'
            '<td><span class="kw3">外的手がかりを用いた歩行訓練、'
            '嚥下機能評価と食形態の調整、LSVT</span></td></tr>'
            '<tr><td><span class="kw3">制度・環境</span></td>'
            '<td><span class="kw3">介護保険（40〜64歳でも'
            'Parkinson病は特定疾病）・'
            '難病医療費助成（Hoehn-Yahr Ⅲ度以上）・'
            '身体障害者手帳</span></td>'
            '<td><span class="kw3">住宅改修（手すり・段差解消）、'
            '福祉用具貸与、訪問リハ、通所リハ、'
            'ケアマネジャーによる計画</span></td></tr>'
            '<tr><td colspan="3"><span class="kw4">⚠️ 「転倒しないように'
            'ほとんど外出しない」は改善すべき状態であって'
            '望ましい対処ではない</span>——'
            '<span class="kw3">閉じこもりは廃用・筋力低下・'
            '意欲低下・さらなる転倒という悪循環を作る</span>。<br>'
            '<span class="kw3">整形外科ch06（ロコモ・フレイル）の'
            '「高齢者に<u>動かさない</u>指導をしたら、その肢は誤り」と'
            '同じ原則がここでも効く</span>。</td></tr></table>'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">L-dopaで改善しにくい症状＝姿勢反射障害・'
             'すくみ足・嚥下障害・構音障害・自律神経症状</span>。<br>'
             '② <span class="kw3">Parkinson病の直接死因の第1位は誤嚥性肺炎</span>'
             '——嚥下訓練と口腔ケアが予後を左右する。<br>'
             '③ <span class="kw3">すくみ足には外的手がかり（床のライン・'
             'メトロノーム・号令）を用いた歩行訓練</span>。<br>'
             '④ <span class="kw3">Parkinson病は40〜64歳でも介護保険を使える'
             '特定疾病</span>。'
             '<span class="kw">住宅改修・福祉用具・訪問リハが使える</span>。<br>'
             '⑤ <span class="kw4">閉じこもり（外出しない）は是正すべき状態</span>。')),

    # ── NO.23 (112B-5) 必修 98% ans=d ──────────────────────────
    Q('112B-5', 98, [('bh', '必修')],
      '<strong>造影CT を施行するにあたり事前に確認すべきこととして'
      '最も重要なのはどれか。</strong>',
      [('a', '喫煙歴', False,
        '<span class="kw4">喫煙歴は肺癌のリスク評価や'
        '術前評価には重要だが、造影剤の安全性とは無関係</span>。'),
       ('b', '飲酒歴', False,
        '<span class="kw4">飲酒歴も造影剤の禁忌には関係しない</span>。'
        '<span class="kw">肝疾患・膵疾患のリスク評価には必要だが、'
        '「造影CTを施行するにあたり」の確認事項ではない</span>。'),
       ('c', '肝機能', False,
        '<span class="kw4">ヨード造影剤はほぼ全量が腎から排泄され、'
        '肝での代謝を受けない</span>。'
        '<span class="kw4">したがって肝機能は造影剤の安全性に直結しない</span>。'
        '<span class="kw3">「排泄経路がどこか」を考えれば'
        '確認すべき臓器が決まる</span>——'
        '<span class="kw3">ヨード造影剤もガドリニウム造影剤も腎排泄</span>。'),
       ('d', '腎機能', True,
        '<span class="kw3">◯ ヨード造影剤を使う前に最も重要な確認事項は腎機能</span>。'
        '<span class="kw3">理由は2つ</span>——'
        '<span class="kw3">①造影剤腎症（contrast-induced nephropathy）の予防</span>'
        '（<span class="kw">腎髄質の血管収縮による虚血と、'
        '尿細管への直接毒性。投与後48〜72時間で血清Crが上昇する</span>）、'
        '<span class="kw3">②腎機能低下例では排泄が遅れて'
        '副作用が遷延する</span>。'
        '<span class="kw3">eGFRを確認し、低下例では'
        '検査の必要性を再検討したうえで、'
        '生理食塩液による輸液（水分負荷）・造影剤量の減量・'
        '腎毒性薬の中止といった対策をとる</span>。'
        '<span class="kw3">またビグアナイド系薬（メトホルミン）内服中の患者では'
        '乳酸アシドーシスを避けるため検査前後で休薬する</span>——'
        '<span class="kw3">これも腎機能に関わる確認である</span>。'),
       ('e', '認知機能', False,
        '<span class="kw4">認知機能は同意取得や検査中の協力（安静保持）に'
        '関わるが、造影剤そのものの安全性の問題ではない</span>。'
        '<span class="kw">むしろ体動アーチファクトの観点で'
        'CT撮影の質に影響する（NO.2参照）</span>。')],
      'ヨード造影剤もガドリニウム造影剤も腎排泄。まず腎機能を確認する。',
      patho=('🔎 造影剤を使う前の確認事項——「腎・喘息・既往」の3点',
             '<span class="kw3">造影剤の設問は、'
             '確認すべき3項目を持っていればほぼ解ける</span>。' + TBL_CONTRAST),
      deep=('💡 造影剤腎症——「起こる人」と「予防のしかた」',
            '<span class="kw3">造影剤腎症は'
            '「造影剤投与後72時間以内に血清Crが'
            '前値より0.5mg/dL以上または25%以上上昇したもの」</span>と定義される。'
            '<table class="tb"><tr><th></th><th>内容</th></tr>'
            '<tr><td><span class="kw3">リスク因子</span></td>'
            '<td><span class="kw3">慢性腎臓病（eGFR低下）が最大</span>。'
            'ほかに<span class="kw">糖尿病性腎症・脱水・高齢・心不全・'
            '腎毒性薬（NSAID・アミノグリコシド・利尿薬）の併用・'
            '造影剤の大量／反復投与</span></td></tr>'
            '<tr><td><span class="kw3">経　過</span></td>'
            '<td><span class="kw3">投与後24〜48時間でCrが上昇し、'
            '3〜5日でピーク、1〜2週で回復するのが典型</span>。'
            '<span class="kw3">多くは非乏尿性で無症候</span></td></tr>'
            '<tr><td><span class="kw3">予　防</span></td>'
            '<td><span class="kw3">①適応の再検討（本当に造影が要るか、'
            'MRIや超音波で代替できないか）'
            '②生理食塩液による輸液（検査前後）'
            '③造影剤量を最小に ④腎毒性薬の中止 '
            '⑤短期間での反復投与を避ける</span></td></tr>'
            '<tr><td><span class="kw">ビグアナイド薬</span></td>'
            '<td><span class="kw">腎機能低下で蓄積し'
            '乳酸アシドーシスを起こしうるため、'
            '造影剤投与時は検査前後で休薬する</span></td></tr>'
            '<tr><td><span class="kw4">発症したら</span></td>'
            '<td><span class="kw3">経時的な腎機能評価と補液</span>。'
            '<span class="kw4">多くは可逆的なので、'
            'いきなり透析やシャント造設に走らない</span>（NO.24）</td></tr></table>'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">造影CTの前に最も重要な確認事項は腎機能</span>。<br>'
             '② <span class="kw3">ヨード造影剤もガドリニウム造影剤も腎排泄</span>'
             '——だから肝機能ではなく腎機能。<br>'
             '③ <span class="kw3">確認3点セット＝腎機能・気管支喘息・'
             '造影剤副作用の既往</span>。<br>'
             '④ <span class="kw">ヨード特有の禁忌＝甲状腺機能亢進症・'
             '多発性骨髄腫／マクログロブリン血症・褐色細胞腫</span>。<br>'
             '⑤ <span class="kw">ビグアナイド薬は検査前後で休薬（乳酸アシドーシス）</span>。')),

    # ── NO.24 (112A-39) 93% ans=b ──────────────────────────────
    Q('112A-39', 93, [],
      '56 歳の男性。肝臓の腫瘤性病変の精査のため入院中である。'
      'C 型肝炎の経過観察中に行った腹部超音波検査で肝臓に腫瘤性病変が見つかったため入院した。'
      '<span class="kw">入院後に腹部造影CT を施行したところ、入院時1.1mg/dL であった'
      '血清クレアチニン値が造影検査後2 日目に3.0mg/dL に上昇した。</span>'
      '<span class="kw">入院後に新たな薬剤投与はなく、食事は毎日全量摂取できており、'
      '体重は安定していた。体温、脈拍、血圧、呼吸数ともに正常範囲で、'
      '排尿回数も5、6 回/ 日で変わらなかった。</span><br>'
      '造影検査後2 日目の検査所見：尿所見：蛋白（－）、糖（－）、潜血（－）、'
      '沈渣に赤血球1 ～4/1 視野、白血球1 ～4/1 視野。'
      '血液所見：赤血球302 万、Hb 10.4g/dL、Ht 31％、白血球4,600、血小板16 万。'
      '血液生化学所見：総ビリルビン1.4mg/dL、直接ビリルビン0.8mg/dL、'
      'AST 45U/L、ALT 62U/L、LD 360U/L（基準176 ～353）、ALP 380U/L（基準115 ～359）、'
      'γ-GTP 110U/L（基準8 ～50）、尿素窒素43mg/dL、クレアチニン3.0mg/dL、'
      '尿酸8.8mg/dL、Na 136mEq/L、K 5.2mEq/L、Cl 100mEq/L、Ca 8.2mg/dL、P 6.2mg/dL。'
      'CRP 0.3mg/dL。<span class="kw">腹部超音波検査では両腎に水腎症を認めない。</span><br>'
      '<strong>対応として正しいのはどれか。</strong>',
      [('a', '緊急血液透析', False,
        '<span class="kw4">緊急透析の適応（AIUEO）は'
        'Acidosis（重度アシドーシス）・Intoxication（中毒）・'
        'Uremia（尿毒症症状）・Electrolyte（高K血症）・'
        'Overload（体液過剰・肺水腫）</span>。'
        '<span class="kw4">本例はK 5.2mEq/Lと軽度上昇にとどまり、'
        '尿毒症症状も溢水も無く、尿量も保たれている</span>。'
        '<span class="kw4">Crが3.0というだけで透析を始めるのは過剰</span>。'),
       ('b', '経時的な腎機能評価', True,
        '<span class="kw3">◯ 造影剤腎症は多くが可逆的で、'
        '経過をみるうちに回復する</span>。'
        '<span class="kw3">典型的な経過は「投与後24〜48時間でCrが上昇し、'
        '3〜5日でピーク、1〜2週で前値に戻る」</span>で、'
        '<span class="kw3">本例（造影後2日目）はまさに上昇途中</span>。'
        '<span class="kw3">やるべきことは①十分な輸液で腎血流を保つ '
        '②腎毒性薬を避ける ③電解質と尿量を監視しながら'
        '経時的にCrを追う</span>ことである。'
        '<span class="kw3">「多くは自然に回復する」という自然経過を知っていれば、'
        '侵襲的な介入に走らずに済む</span>。'),
       ('c', '尿道カテーテル留置', False,
        '<span class="kw4">尿道カテーテルは尿路の閉塞（腎後性）を'
        '解除する処置</span>だが、'
        '<span class="kw4">本例は「排尿回数も5、6回/日で変わらなかった」'
        '「両腎に水腎症を認めない」と、'
        '腎後性を明確に否定している</span>。'
        '<span class="kw">尿量の正確な測定を目的に留置することはあるが、'
        '「対応として正しい」ものではなく、'
        '尿路感染のリスクを増やす</span>。'),
       ('d', '腹部造影CT の再施行', False,
        '<span class="kw4">造影剤腎症を起こした直後に'
        '同じ造影剤を再投与するのは禁忌に近い</span>。'
        '<span class="kw4">短期間での反復投与は造影剤腎症の'
        '明確なリスク因子</span>である。'
        '<span class="kw3">肝腫瘤の精査を続ける必要があるなら、'
        '造影超音波やEOB造影MRI（腎機能を見て）、'
        '腎機能回復後の再検を検討する</span>。'),
       ('e', '動静脈シャント造設術の準備', False,
        '<span class="kw4">シャント造設は慢性腎不全で'
        '維持透析導入が見込まれる患者に行う準備</span>。'
        '<span class="kw4">本例は入院時Cr 1.1mg/dLと'
        'ほぼ正常だった患者の急性かつ可逆性の変化</span>であり、'
        '<span class="kw4">維持透析を前提とした準備はまったく不要</span>。')],
      '造影剤腎症は多くが可逆的。輸液しながら経時的にCrを追うのが正しい。',
      patho=('🔎 急性腎障害を見たら——腎前性・腎性・腎後性を切り分ける',
             '<span class="kw3">Crが上がったら、'
             'まず3つのどれかを決める</span>。'
             '<span class="kw3">本例は「造影剤投与」という'
             '明確な曝露があり、腎後性（水腎症なし）と'
             '腎前性（脱水なし・体重安定・食事全量・バイタル正常）が'
             '丁寧に否定されている</span>。'
             '<table class="tb"><tr><th></th><th>腎前性</th>'
             '<th><span class="kw3">腎性（本例）</span></th><th>腎後性</th></tr>'
             '<tr><td>原　因</td>'
             '<td><span class="kw">脱水・出血・心不全・敗血症</span></td>'
             '<td><span class="kw3">造影剤腎症・急性尿細管壊死・'
             '薬剤性間質性腎炎・糸球体腎炎</span></td>'
             '<td><span class="kw">尿路閉塞</span></td></tr>'
             '<tr><td>本例での所見</td>'
             '<td><span class="kw4">体重安定・食事全量・'
             'バイタル正常＝否定的</span></td>'
             '<td><span class="kw3">造影剤の曝露あり・'
             '時期が合致（2日目）</span></td>'
             '<td><span class="kw4">水腎症なし・尿量保持＝否定的</span></td></tr>'
             '<tr><td>尿所見</td>'
             '<td>濃縮尿・Na排泄低下</td>'
             '<td><span class="kw3">造影剤腎症では'
             '尿所見に乏しいことが多い（本例も蛋白・潜血陰性）</span></td>'
             '<td>—</td></tr>'
             '<tr><td>対　応</td>'
             '<td><span class="kw">細胞外液の補充</span></td>'
             '<td><span class="kw3">原因の除去＋支持療法＋経過観察</span></td>'
             '<td><span class="kw">閉塞の解除</span></td></tr></table>'
             '<span class="kw3">なお薬剤性間質性腎炎（好酸球増多・'
             '好酸球尿・発疹・発熱を伴う）は'
             '「入院後に新たな薬剤投与はなく」の一文で否定されている</span>。'),
      deep=('💡 「介入しない」が正解になる設問の型',
            '<span class="kw3">国試には'
            '「何もしない（経過をみる）」が正解になる問題が'
            '一定数ある</span>。'
            '<span class="kw3">見分ける手がかりは共通している</span>。'
            '<table class="tb"><tr><th>手がかり</th><th>本例での該当</th></tr>'
            '<tr><td><span class="kw3">病態が自然に回復するものと'
            '分かっている</span></td>'
            '<td><span class="kw3">造影剤腎症は1〜2週で回復するのが典型</span></td></tr>'
            '<tr><td><span class="kw3">緊急介入の適応基準を'
            '満たしていない</span></td>'
            '<td><span class="kw3">透析の適応（高K・アシドーシス・'
            '溢水・尿毒症）をどれも満たさない</span></td></tr>'
            '<tr><td><span class="kw3">症例文が「危険な所見が無いこと」を'
            'わざわざ列挙している</span></td>'
            '<td><span class="kw3">「体温、脈拍、血圧、呼吸数ともに正常範囲」'
            '「排尿回数も変わらなかった」'
            '「水腎症を認めない」</span></td></tr>'
            '<tr><td><span class="kw4">他の肢がすべて侵襲的・不可逆的</span></td>'
            '<td><span class="kw4">緊急透析・カテーテル留置・'
            '造影剤の再投与・シャント造設</span></td></tr></table>'
            '<span class="kw3">同じ型は第4章 NO.57（無症候性の放射線肺炎は'
            '経過観察）にも出てくる</span>——'
            '<span class="kw3">「画像や検査値が動いた」ことと'
            '「治療が要る」ことは別</span>である。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">造影剤腎症は投与後24〜48時間で上昇、'
             '3〜5日でピーク、1〜2週で回復するのが典型（可逆的）</span>。<br>'
             '② <span class="kw3">対応は輸液と経時的な腎機能評価</span>。<br>'
             '③ <span class="kw4">緊急透析の適応＝高K血症・重度アシドーシス・'
             '溢水・尿毒症症状・中毒</span>——Crの値だけでは決めない。<br>'
             '④ <span class="kw4">造影剤腎症の直後に造影剤を再投与しない</span>。<br>'
             '⑤ <span class="kw">急性腎障害はまず腎前性・腎性・腎後性を切り分ける</span>。')),

    # ── NO.25 (101B-92) 83% ans=b,c ────────────────────────────
    Q('101B-92', 83, [],
      '<strong>画像検査でヨード造影剤が用いられるのはどれか。2つ選べ。</strong>',
      [('a', '超音波検査', False,
        '<span class="kw4">超音波の造影剤はマイクロバブル'
        '（微小気泡）製剤</span>で、'
        '<span class="kw4">ヨードもガドリニウムも使わない</span>。'
        '<span class="kw">音響インピーダンスの差を人工的に作って'
        '血流を強調する</span>もので、'
        '<span class="kw3">腎機能障害があっても使えるのが利点</span>'
        '（<span class="kw">肝腫瘤の鑑別などに用いる</span>）。'),
       ('b', '血管造影', True,
        '<span class="kw3">◯ 血管造影は水溶性ヨード造影剤を'
        '動脈内に直接注入して血管の内腔を描出する検査</span>。'
        '<span class="kw3">ヨードは原子番号53と大きく'
        'エックス線をよく吸収するので、'
        '血管が白く浮かび上がる</span>。'
        '<span class="kw">冠動脈造影・脳血管造影・下肢動脈造影など'
        'すべて同じ原理</span>で、'
        '<span class="kw">そのままIVR（塞栓術・拡張術）へ移行できる</span>。'),
       ('c', 'CT', True,
        '<span class="kw3">◯ 造影CTで用いるのも水溶性ヨード造影剤</span>。'
        '<span class="kw3">静脈から注入し、'
        '血流に乗って全身へ行き渡ったところを撮影する</span>。'
        '<span class="kw3">造影のねらいは①血管を描出する '
        '②臓器・病変の血流の違い（造影パターン）を見る '
        '③正常構造と病変のコントラストを付ける</span>ことである。'
        '<span class="kw">肝細胞癌の「動脈相で濃染し門脈相で洗い出される」'
        'という所見も、造影のタイミングを変えて撮る'
        'ダイナミックCTで初めて見える</span>。'),
       ('d', 'MRI', False,
        '<span class="kw4">MRIの造影剤はガドリニウム製剤</span>'
        '（<span class="kw">ほかに肝特異性のEOB・鉄含有製剤・'
        '消化管用の経口製剤</span>）。'
        '<span class="kw4">ヨードは使わない</span>。'
        '<span class="kw3">MRIはエックス線の吸収差ではなく'
        '緩和時間の差で像を作るので、'
        '「エックス線をよく吸収する物質」は造影剤にならない</span>——'
        '<span class="kw3">ガドリニウムは常磁性体で'
        '周囲の水素原子のT<sub>1</sub>緩和時間を短縮させる</span>。'),
       ('e', 'SPECT', False,
        '<span class="kw4">SPECTは核医学検査で、'
        '用いるのは造影剤ではなく放射性医薬品（放射性同位元素で標識した薬剤）</span>。'
        '<span class="kw">体内から放出されるγ線を検出して像を作る</span>ので、'
        '<span class="kw4">外からエックス線を当てるわけではない</span>。'
        '<span class="kw">用いる核種は<sup>99m</sup>Tc・<sup>123</sup>I など</span>。')],
      'ヨード造影剤はエックス線を使う検査（CT・血管造影・消化管／尿路造影）。',
      patho=('🔎 造影剤は「その装置が何で像を作るか」に合わせて選ばれる',
             '<span class="kw3">造影剤の種類は、'
             '装置の原理から必然的に決まる</span>。'
             '<table class="tb"><tr><th>検査</th><th>像を作る原理</th>'
             '<th>造影剤</th><th>なぜそれか</th></tr>'
             '<tr><td><span class="kw3">単純エックス線・CT・'
             '血管造影・透視</span></td>'
             '<td><span class="kw3">エックス線の吸収差</span></td>'
             '<td><span class="kw3">ヨード造影剤・硫酸バリウム</span></td>'
             '<td><span class="kw3">原子番号が大きく'
             'エックス線をよく吸収する</span>'
             '（ヨード53・バリウム56）</td></tr>'
             '<tr><td><span class="kw3">MRI</span></td>'
             '<td><span class="kw3">水素原子の緩和時間の差</span></td>'
             '<td><span class="kw3">ガドリニウム製剤</span>'
             '（ほかにEOB・鉄含有）</td>'
             '<td><span class="kw3">常磁性体で周囲の'
             'T<sub>1</sub>緩和時間を短縮させる</span></td></tr>'
             '<tr><td><span class="kw3">超音波</span></td>'
             '<td><span class="kw3">音響インピーダンスの差</span></td>'
             '<td><span class="kw3">マイクロバブル</span></td>'
             '<td><span class="kw3">気泡が強く反射する。'
             '腎機能障害でも使える</span></td></tr>'
             '<tr><td><span class="kw3">核医学（SPECT・PET）</span></td>'
             '<td><span class="kw3">体内から出る放射線の検出</span></td>'
             '<td><span class="kw4">造影剤ではなく放射性医薬品</span></td>'
             '<td><span class="kw3">薬剤自体が線源になる</span></td></tr></table>'
             + TBL_CONTRAST),
      deep=('💡 ヨード造影剤の使われ方——「血管に入れるか、管腔に入れるか」',
            '<table class="tb"><tr><th>投与経路</th><th>製剤</th>'
            '<th>検査</th></tr>'
            '<tr><td><span class="kw3">静脈内</span></td>'
            '<td><span class="kw">水溶性非イオン性ヨード造影剤</span></td>'
            '<td><span class="kw3">造影CT・静脈性尿路造影〈IVU〉</span></td></tr>'
            '<tr><td><span class="kw3">動脈内</span></td>'
            '<td><span class="kw">水溶性非イオン性ヨード造影剤</span></td>'
            '<td><span class="kw3">血管造影・IVR</span></td></tr>'
            '<tr><td><span class="kw">くも膜下腔</span></td>'
            '<td><span class="kw">水溶性非イオン性ヨード造影剤</span></td>'
            '<td><span class="kw">脊髄造影〈ミエログラフィ〉</span></td></tr>'
            '<tr><td><span class="kw">消化管内</span></td>'
            '<td><span class="kw">硫酸バリウム</span>'
            '（<span class="kw4">穿孔・誤嚥のおそれがあれば'
            'ガストログラフィン</span>）</td>'
            '<td><span class="kw">上部・下部消化管造影</span></td></tr>'
            '<tr><td><span class="kw">子宮腔・リンパ管</span></td>'
            '<td><span class="kw">油性ヨード造影剤（リピオドール）</span></td>'
            '<td><span class="kw">子宮卵管造影・リンパ管造影</span>。'
            '<span class="kw">TACEの塞栓物質としても使う</span></td></tr>'
            '<tr><td colspan="3"><span class="kw4">⚠️ バリウムの禁忌は消化管穿孔'
            '（腹腔内に残って腹膜炎を起こす）</span>、'
            '<span class="kw4">ガストログラフィンの禁忌は誤嚥'
            '（高浸透圧で重症肺炎をきたす）</span>——'
            '<span class="kw3">「穿孔ならガストログラフィン、'
            '誤嚥のおそれならバリウム」と覚えると取り違えない</span>。</td></tr></table>'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">ヨード造影剤＝エックス線を使う検査'
             '（CT・血管造影・消化管造影・尿路造影・脊髄造影）</span>。<br>'
             '② <span class="kw3">MRI＝ガドリニウム／超音波＝マイクロバブル／'
             '核医学＝放射性医薬品（造影剤ではない）</span>。<br>'
             '③ <span class="kw">造影剤がエックス線で効くのは'
             '原子番号が大きいから（ヨード53・バリウム56）</span>。<br>'
             '④ <span class="kw4">バリウムの禁忌＝消化管穿孔／'
             'ガストログラフィンの禁忌＝誤嚥</span>。<br>'
             '⑤ <span class="kw">マイクロバブルは腎機能障害があっても使える</span>。')),

    # ── NO.26 (111E-34) CBT 76% ans=b,e ────────────────────────
    Q('111E-34', 76, [('bc', 'CBT')],
      '腹部超音波検査で肝腫瘤を指摘された患者に対して、'
      '<span class="kw">腹部ガドリニウム造影MRI</span>を行うこととなった。<br>'
      '<strong>検査前に確認すべきなのはどれか。2つ選べ。</strong>',
      [('a', '腹　水', False,
        '<span class="kw4">腹水の有無はガドリニウム造影剤の'
        '安全性とは無関係</span>。'
        '<span class="kw">大量腹水があると仰臥位が保てず'
        '検査が困難になることはあるが、'
        '「検査前に確認すべき」項目として問われているのは'
        '造影剤の禁忌</span>である。'),
       ('b', '腎機能', True,
        '<span class="kw3">◯ ガドリニウム造影剤は腎から排泄されるため、'
        '重度の腎機能低下があると体内に長く留まり、'
        '腎性全身性線維症〈NSF〉を起こしうる</span>。'
        '<span class="kw3">NSFは皮膚・皮下組織から始まり'
        '関節拘縮・内臓の線維化に至る不可逆的な病態で、'
        '有効な治療法がない</span>。'
        '<span class="kw3">eGFRが30mL/分/1.73m<sup>2</sup>未満、'
        '急性腎障害、透析中の患者では原則使用しない</span>。'
        '<span class="kw3">「ヨードでもガドリニウムでも、まず腎機能」</span>。'),
       ('c', '肝機能', False,
        '<span class="kw4">通常のガドリニウム造影剤は肝で代謝されないので、'
        '肝機能は安全性に直結しない</span>。'
        '<span class="kw">ただし肝細胞特異性造影剤（Gd-EOB-DTPA）は'
        '一部が肝細胞に取り込まれて胆汁排泄されるため、'
        '高度の肝機能障害では肝細胞相の造影効果が落ちる</span>——'
        '<span class="kw4">これは「安全性」ではなく「画質」の問題</span>で、'
        '<span class="kw4">禁忌の確認事項ではない</span>。'),
       ('d', '抗血小板薬の内服', False,
        '<span class="kw4">抗血小板薬は出血を伴う手技'
        '（生検・穿刺・手術）で確認すべき事項</span>で、'
        '<span class="kw4">経静脈的な造影MRIとは関係しない</span>。'
        '<span class="kw">末梢静脈路の確保程度で問題になることはない</span>。'),
       ('e', '気管支喘息の既往', True,
        '<span class="kw3">◯ 気管支喘息はヨード造影剤・'
        'ガドリニウム造影剤いずれにおいても'
        'アナフィラキシー様反応のリスク因子</span>である。'
        '<span class="kw3">気道の過敏性が背景にあり、'
        '造影剤による気管支攣縮が重症化しやすい</span>。'
        '<span class="kw3">ガドリニウムの副作用頻度はヨードより低いが、'
        '起こったときの重症度は同等</span>なので、'
        '<span class="kw3">喘息の既往・コントロール状況（活動性）を必ず確認する</span>。'
        '<span class="kw">造影剤副作用の既往があればさらに厳格で、'
        '原則として同系統の造影剤は使わない</span>。')],
      'ガドリニウムでも確認は腎機能と喘息（＋副作用歴）。肝機能・抗血小板薬は無関係。',
      patho=('🔎 造影剤の確認3点セット——ヨードでもガドリニウムでも同じ',
             '<span class="kw3">NO.4・NO.6・NO.23・NO.26 と、'
             '本章には「造影の前に何を確認するか」の設問が4問ある</span>。'
             '<span class="kw3">答えの骨格は共通で、'
             '3つの確認事項＋造影剤ごとの追加項目</span>という構造である。'
             '<table class="tb"><tr><th>確認事項</th>'
             '<th>ヨード造影剤</th><th>ガドリニウム造影剤</th>'
             '<th>何が起こるか</th></tr>'
             '<tr><td><span class="kw3">① 腎機能</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">ヨード＝造影剤腎症（可逆的）／'
             'Gd＝腎性全身性線維症（不可逆）</span></td></tr>'
             '<tr><td><span class="kw3">② 気管支喘息</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">アナフィラキシー様反応・気管支攣縮</span></td></tr>'
             '<tr><td><span class="kw3">③ 造影剤副作用の既往</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">◯</span></td>'
             '<td><span class="kw3">再投与でより重篤化しうる</span></td></tr>'
             '<tr><td>④ 甲状腺機能亢進症</td>'
             '<td><span class="kw">◯</span></td><td>—</td>'
             '<td><span class="kw">ヨードによる甲状腺クリーゼ</span></td></tr>'
             '<tr><td>⑤ 多発性骨髄腫・'
             'マクログロブリン血症・褐色細胞腫</td>'
             '<td><span class="kw">◯</span></td><td>—</td>'
             '<td><span class="kw">腎障害の悪化・カテコラミンクリーゼ</span></td></tr>'
             '<tr><td>⑥ ビグアナイド薬の内服</td>'
             '<td><span class="kw">◯</span></td><td>—</td>'
             '<td><span class="kw">乳酸アシドーシス（検査前後で休薬）</span></td></tr>'
             '<tr><td><span class="kw3">⑦ 体内金属・'
             'ペースメーカの機種</span></td>'
             '<td>—</td><td><span class="kw3">◯（MRI共通）</span></td>'
             '<td><span class="kw3">吸引・発熱・誤作動</span></td></tr>'
             '<tr><td>⑧ 妊娠</td>'
             '<td><span class="kw">◯（被ばく）</span></td>'
             '<td><span class="kw">◯（原則Gdは使わない）</span></td>'
             '<td>—</td></tr></table>'),
      deep=('💡 肝腫瘤を「どの検査でどう詰めるか」',
            '<span class="kw3">本例は超音波で肝腫瘤を指摘され、'
            '造影MRIへ進む場面である</span>。'
            '<span class="kw3">肝腫瘤の診断は'
            '「血流のパターンを時間で追う」ことで進む</span>。'
            '<table class="tb"><tr><th>検査</th><th>役割</th></tr>'
            '<tr><td><span class="kw3">腹部超音波</span></td>'
            '<td><span class="kw3">スクリーニング</span>——'
            '被ばくなし・安価・繰り返せる。'
            '<span class="kw">囊胞（無エコー＋後方エコー増強）と'
            '充実性腫瘤の区別</span></td></tr>'
            '<tr><td><span class="kw3">ダイナミック造影CT</span></td>'
            '<td><span class="kw3">動脈相・門脈相・平衡相を撮って'
            '血流パターンを見る</span>——'
            '<span class="kw3">肝細胞癌は「動脈相で濃染し、'
            '門脈相〜平衡相で洗い出される〈washout〉」</span></td></tr>'
            '<tr><td><span class="kw3">EOB造影MRI</span></td>'
            '<td><span class="kw3">上記に加えて肝細胞相'
            '（投与20分後）が撮れる</span>——'
            '<span class="kw3">Gd-EOB-DTPAは正常肝細胞に取り込まれるので、'
            '取り込まない病変が黒く抜けて見える'
            '＝小さな肝細胞癌の検出に優れる</span></td></tr>'
            '<tr><td><span class="kw">造影超音波（マイクロバブル）</span></td>'
            '<td><span class="kw">腎機能障害でも使える血流評価</span></td></tr>'
            '<tr><td><span class="kw">血管造影・CTAP／CTHA</span></td>'
            '<td><span class="kw">TACEなどの治療とセットで</span></td></tr></table>'
            '<span class="kw3">MRIが選ばれるのは、'
            '被ばくがなく、軟部組織のコントラストに優れ、'
            'EOBという肝細胞特異性造影剤が使えるから</span>——'
            '<span class="kw3">C型肝炎の経過観察のように'
            '繰り返し検査する患者では被ばくの少なさが効いてくる</span>。'),
      point=('🎯 国試ポイント',
             '① <span class="kw3">ガドリニウム造影MRIの前に確認するのは'
             '腎機能と気管支喘息（＋造影剤副作用の既往）</span>。<br>'
             '② <span class="kw3">ガドリニウム＋重度腎機能低下＝'
             '腎性全身性線維症〈NSF〉（不可逆・治療法なし）</span>。<br>'
             '③ <span class="kw4">肝機能・抗血小板薬・腹水は'
             '造影剤の禁忌とは無関係</span>。<br>'
             '④ <span class="kw">MRIそのものの禁忌（体内金属・'
             'ペースメーカ）も別途確認する</span>。<br>'
             '⑤ <span class="kw">肝細胞癌＝ダイナミック造影で'
             '「動脈相で濃染し門脈相でwashout」</span>。')),

]
