"""
Regenerate chapters_meta.js from existing Desktop/MEC chapter HTML files.
Run from the MEC/ directory: python gen_meta.py

Unlike build.py (which copies from OneDrive), this reads the already-built
HTML files and refreshes the metadata (titles, counts, prefixes).
"""
import re, os, json, sys
from collections import Counter
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SUBJECTS = [
    {'id': 'endo',    'name': '内分泌',   'icon': '⚗️',  'color': '#00838F', 'dir': '内分泌'},
    {'id': 'resp',    'name': '呼吸器',   'icon': '🌬️', 'color': '#1565C0', 'dir': '呼吸器'},
    {'id': 'circ',    'name': '循環器',   'icon': '❤️',  'color': '#C62828', 'dir': '循環器'},
    {'id': 'dige',    'name': '消化器',   'icon': '🌿',  'color': '#6A1B9A', 'dir': '消化器'},
    {'id': 'neur',    'name': '神経',     'icon': '🧠',  'color': '#2E7D32', 'dir': '神経'},
    {'id': 'hbp',     'name': '肝胆膵',   'icon': '🧪',  'color': '#E65100', 'dir': '肝胆膵'},
    {'id': 'jinzo_d', 'name': '腎臓',     'icon': '💧',  'color': '#78909C', 'dir': '腎臓'},
    {'id': 'hema',    'name': '血液',     'icon': '🩸',  'color': '#B71C1C', 'dir': '血液'},
    {'id': 'imma',    'name': '免アレ膠', 'icon': '🛡️', 'color': '#AD1457', 'dir': '免アレ膠'},
]

SKIP = {'mindmap.html', 'selfcheck_intro.html'}


def get_title(html, filename):
    m = re.search(r'<title[^>]*>(.*?)</title>', html, re.IGNORECASE | re.DOTALL)
    if m:
        t = re.sub(r'\s*[-|｜].*$', '', m.group(1)).strip()
        t = re.sub(r'^ch\d+[\s_]+', '', t).strip()
        if t:
            return t
    base = os.path.splitext(filename)[0]
    return re.sub(r'^ch\d+[_\s]+', '', base).replace('_', ' ').strip()


def process_file(path, subj_dir):
    with open(path, encoding='utf-8', errors='replace') as f:
        html = f.read()
    q_uids = [u for u in re.findall(r'data-uid="([^"]+)"', html)
              if re.search(r'_q\d+$', u)]
    if not q_uids:
        return None
    prefix = Counter(re.sub(r'_q\d+$', '', u) for u in q_uids).most_common(1)[0][0]
    count = len(set(q_uids))
    title = get_title(html, os.path.basename(path))
    return {'prefix': prefix, 'file': f'{subj_dir}/{os.path.basename(path)}', 'title': title, 'count': count}


mec_chapters = []
flat_meta = {}

for subj in SUBJECTS:
    d = subj['dir']
    if not os.path.isdir(d):
        print(f'WARN: directory not found: {d}')
        continue
    chapters = []
    for fn in sorted(os.listdir(d)):
        if not fn.endswith('.html') or fn in SKIP:
            continue
        ch = process_file(os.path.join(d, fn), d)
        if ch:
            chapters.append(ch)
            flat_meta[ch['prefix']] = {'count': ch['count'], 'title': ch['title'], 'file': ch['file']}
    entry = {k: subj[k] for k in ('id', 'name', 'icon', 'color')}
    entry['chapters'] = chapters
    mec_chapters.append(entry)
    total = sum(c['count'] for c in chapters)
    print(f'{d}: {len(chapters)} chapters, {total} questions')

grand_total = sum(c['count'] for s in mec_chapters for c in s['chapters'])
grand_ch = sum(len(s['chapters']) for s in mec_chapters)
print(f'\nTotal: {len(mec_chapters)} subjects, {grand_ch} chapters, {grand_total} questions')

output = (
    '// Auto-generated by gen_meta.py -- do not edit manually\n'
    'const MEC_CHAPTERS = ' + json.dumps(mec_chapters, ensure_ascii=False, indent=2) + ';\n'
    'const MEC_CHAPTER_META = ' + json.dumps(flat_meta, ensure_ascii=False, indent=2) + ';\n'
)
with open('chapters_meta.js', 'w', encoding='utf-8') as f:
    f.write(output)
print('Written: chapters_meta.js')
