// Auto-generated by build.py -- do not edit manually
const MEC_CHAPTERS = [
  {
    "id": "endo",
    "name": "内分泌",
    "icon": "⚗️",
    "color": "#00838F",
    "chapters": [
      {
        "prefix": "endo_ch01",
        "file": "内分泌/ch01_endo_basics.html",
        "title": "内分泌代謝の基本",
        "count": 16
      },
      {
        "prefix": "endo_ch02",
        "file": "内分泌/ch02_hypothalamus_pituitary_ant.html",
        "title": "視床下部・下垂体前葉",
        "count": 68
      },
      {
        "prefix": "endo_ch03",
        "file": "内分泌/ch03_posterior_pituitary.html",
        "title": "下垂体後葉",
        "count": 28
      },
      {
        "prefix": "endo_ch04",
        "file": "内分泌/ch04_thyroid.html",
        "title": "甲状腺",
        "count": 79
      },
      {
        "prefix": "endo_ch05",
        "file": "内分泌/ch05_parathyroid.html",
        "title": "副甲状腺",
        "count": 16
      },
      {
        "prefix": "endo_ch06",
        "file": "内分泌/ch06_adrenal.html",
        "title": "副腎",
        "count": 89
      },
      {
        "prefix": "endo_ch07",
        "file": "内分泌/ch07_endocrine_tumors.html",
        "title": "内分泌腫瘍とIAS",
        "count": 29
      },
      {
        "prefix": "endo_ch08",
        "file": "内分泌/ch08_diabetes.html",
        "title": "糖尿病",
        "count": 98
      },
      {
        "prefix": "endo_ch09",
        "file": "内分泌/ch09_lipid_metabolism.html",
        "title": "脂質代謝",
        "count": 41
      },
      {
        "prefix": "endo_ch10",
        "file": "内分泌/ch10_other_metabolic.html",
        "title": "その他の代謝疾患",
        "count": 78
      }
    ]
  },
  {
    "id": "resp",
    "name": "呼吸器",
    "icon": "🌬️",
    "color": "#1565C0",
    "chapters": [
      {
        "prefix": "resp_ch01",
        "file": "呼吸器/ch01_呼吸器の基本_解答解説.html",
        "title": "ch01 呼吸器の基本 解答解説",
        "count": 72
      },
      {
        "prefix": "resp_ch02",
        "file": "呼吸器/ch02_呼吸不全_解答解説.html",
        "title": "呼吸不全",
        "count": 33
      },
      {
        "prefix": "resp_ch03",
        "file": "呼吸器/ch03_閉塞性疾患_解答解説.html",
        "title": "閉塞性疾患",
        "count": 65
      },
      {
        "prefix": "resp_ch04",
        "file": "呼吸器/ch04_間質性疾患_解答解説.html",
        "title": "間質性疾患",
        "count": 74
      },
      {
        "prefix": "resp_ch05",
        "file": "呼吸器/ch05_lung_circulation.html",
        "title": "肺循環障害",
        "count": 37
      },
      {
        "prefix": "resp_ch06",
        "file": "呼吸器/ch06_tumor.html",
        "title": "腫瘍",
        "count": 81
      },
      {
        "prefix": "resp_ch07",
        "file": "呼吸器/ch07_other_lung_diseases.html",
        "title": "その他の肺疾患",
        "count": 40
      },
      {
        "prefix": "resp_ch08",
        "file": "呼吸器/ch08_pleura_chest.html",
        "title": "胸膜・胸腔・縦隔",
        "count": 66
      },
      {
        "prefix": "resp_ch09",
        "file": "呼吸器/ch09_breast.html",
        "title": "乳房",
        "count": 38
      }
    ]
  },
  {
    "id": "circ",
    "name": "循環器",
    "icon": "❤️",
    "color": "#C62828",
    "chapters": [
      {
        "prefix": "circ_ch01",
        "file": "循環器/ch01_circulatory_basics.html",
        "title": "循環器の基本",
        "count": 77
      },
      {
        "prefix": "circ_ch02",
        "file": "循環器/ch02_heart_failure.html",
        "title": "心不全",
        "count": 50
      },
      {
        "prefix": "circ_ch03",
        "file": "循環器/ch03_ischemic_heart.html",
        "title": "虚血性心疾患",
        "count": 98
      },
      {
        "prefix": "circ_ch04",
        "file": "循環器/ch04_arrhythmia.html",
        "title": "不整脈",
        "count": 76
      },
      {
        "prefix": "circ_ch05",
        "file": "循環器/ch05_valvular.html",
        "title": "弁膜症",
        "count": 75
      },
      {
        "prefix": "circ_ch06",
        "file": "循環器/ch06_pericardium.html",
        "title": "心膜",
        "count": 65
      },
      {
        "prefix": "circ_ch07",
        "file": "循環器/ch07_myocardium.html",
        "title": "心筋",
        "count": 28
      },
      {
        "prefix": "circ_ch08",
        "file": "循環器/ch08_aorta.html",
        "title": "大動脈",
        "count": 46
      },
      {
        "prefix": "circ_ch09",
        "file": "循環器/ch09_peripheral_vessels.html",
        "title": "末梢動静脈・リンパ",
        "count": 31
      },
      {
        "prefix": "circ_ch10",
        "file": "循環器/ch10_blood_pressure.html",
        "title": "血圧異常",
        "count": 26
      }
    ]
  },
  {
    "id": "dige",
    "name": "消化器",
    "icon": "🌿",
    "color": "#6A1B9A",
    "chapters": [
      {
        "prefix": "dige_ch01",
        "file": "消化器/ch01_shokakan_kihon.html",
        "title": "消化管の基本",
        "count": 51
      },
      {
        "prefix": "dige_ch02",
        "file": "消化器/ch02_eiyou_kanri.html",
        "title": "栄養管理・周術期管理",
        "count": 38
      },
      {
        "prefix": "dige_ch03",
        "file": "消化器/ch03_jyobu_shokakan_shukketsu.html",
        "title": "上部消化管出血",
        "count": 78
      },
      {
        "prefix": "dige_ch04",
        "file": "消化器/ch04_shokudo.html",
        "title": "食道",
        "count": 52
      },
      {
        "prefix": "dige_ch05",
        "file": "消化器/ch05_i.html",
        "title": "胃",
        "count": 55
      },
      {
        "prefix": "dige_ch06",
        "file": "消化器/ch06_kansen_chouen.html",
        "title": "感染性腸炎",
        "count": 53
      },
      {
        "prefix": "dige_ch07",
        "file": "消化器/ch07_enshoseityo_kino.html",
        "title": "炎症性腸疾患と機能性消化管障害",
        "count": 41
      },
      {
        "prefix": "dige_ch08",
        "file": "消化器/ch08_ileus_kyoketsu.html",
        "title": "イレウスと虚血",
        "count": 44
      },
      {
        "prefix": "dige_ch09",
        "file": "消化器/ch09_cho_shuyo.html",
        "title": "腸腫瘍",
        "count": 46
      },
      {
        "prefix": "dige_ch10",
        "file": "消化器/ch10_komonbu.html",
        "title": "肛門",
        "count": 15
      },
      {
        "prefix": "dige_ch11",
        "file": "消化器/ch11_yokakumaku_fukumaku_fukuheki.html",
        "title": "横隔膜・腹膜・腹壁",
        "count": 28
      }
    ]
  },
  {
    "id": "neur",
    "name": "神経",
    "icon": "🧠",
    "color": "#2E7D32",
    "chapters": [
      {
        "prefix": "neur_ch01",
        "file": "神経/ch01_neuro_basics.html",
        "title": "神経の基本",
        "count": 70
      },
      {
        "prefix": "neur_ch02",
        "file": "神経/ch02_cranial_nerves.html",
        "title": "脳神経",
        "count": 67
      },
      {
        "prefix": "neur_ch03",
        "file": "神経/ch03_cerebrovascular.html",
        "title": "脳血管障害",
        "count": 106
      },
      {
        "prefix": "neur_ch04",
        "file": "神経/ch04_higher_brain.html",
        "title": "高次脳機能障害",
        "count": 26
      },
      {
        "prefix": "neur_ch05",
        "file": "神経/ch05_dementia_parkinsonism.html",
        "title": "認知症とParkinsonism",
        "count": 74
      },
      {
        "prefix": "neur_ch06",
        "file": "神経/ch06_motor_neuron_demyelination.html",
        "title": "運動ニューロン障害と脱髄",
        "count": 37
      },
      {
        "prefix": "neur_ch07",
        "file": "神経/ch07_peripheral_nerve_nmj_muscle.html",
        "title": "末梢神経・NMJ・筋",
        "count": 62
      },
      {
        "prefix": "neur_ch08",
        "file": "神経/ch08_neuro_infection.html",
        "title": "神経感染症",
        "count": 47
      },
      {
        "prefix": "neur_ch09",
        "file": "神経/ch09_functional.html",
        "title": "機能性疾患",
        "count": 41
      },
      {
        "prefix": "neur_ch10",
        "file": "神経/ch10_traumatic_intracranial.html",
        "title": "外傷性頭蓋内出血",
        "count": 29
      },
      {
        "prefix": "neur_ch11",
        "file": "神経/ch11_brain_tumor.html",
        "title": "脳腫瘍",
        "count": 35
      }
    ]
  },
  {
    "id": "hbp",
    "name": "肝胆膵",
    "icon": "🧪",
    "color": "#E65100",
    "chapters": [
      {
        "prefix": "hbp_ch01",
        "file": "肝胆膵/ch01_kitan_kihon.html",
        "title": "肝胆膵の基本",
        "count": 68
      },
      {
        "prefix": "hbp_ch02",
        "file": "肝胆膵/ch02_kitan_kanen.html",
        "title": "急性・慢性肝炎",
        "count": 80
      },
      {
        "prefix": "hbp_ch03",
        "file": "肝胆膵/ch03_kitan_kanshorben.html",
        "title": "肝硬変",
        "count": 64
      },
      {
        "prefix": "hbp_ch04",
        "file": "肝胆膵/ch04_kitan_kanshuyo.html",
        "title": "肝腫瘍",
        "count": 56
      },
      {
        "prefix": "hbp_ch05",
        "file": "肝胆膵/ch05_kitan_cholecystitis.html",
        "title": "胆石・胆囊炎・胆管炎",
        "count": 55
      },
      {
        "prefix": "hbp_ch06",
        "file": "肝胆膵/ch06_kitan_biliary_tumor.html",
        "title": "胆腫瘍",
        "count": 21
      },
      {
        "prefix": "hbp_ch07",
        "file": "肝胆膵/ch07_kitan_pancreatitis.html",
        "title": "膵炎",
        "count": 39
      },
      {
        "prefix": "hbp_ch08",
        "file": "肝胆膵/ch08_kitan_pancreatic_tumor.html",
        "title": "膵腫瘍",
        "count": 35
      }
    ]
  },
  {
    "id": "jinzo_d",
    "name": "腎臓",
    "icon": "💧",
    "color": "#78909C",
    "chapters": [
      {
        "prefix": "jinzo_d_ch01",
        "file": "腎臓/ch01_jinzo_腎臓の基本.html",
        "title": "腎臓の基本",
        "count": 48
      },
      {
        "prefix": "jinzo_d_ch02",
        "file": "腎臓/ch02_jinzo_血液浄化療法と移植.html",
        "title": "血液浄化療法と移植",
        "count": 26
      },
      {
        "prefix": "jinzo_d_ch03",
        "file": "腎臓/ch03_jinzo_体液・電解質・酸塩基.html",
        "title": "体液・電解質・酸塩基",
        "count": 75
      },
      {
        "prefix": "jinzo_d_ch04",
        "file": "腎臓/ch04_jinzo_腎不全.html",
        "title": "腎不全",
        "count": 36
      },
      {
        "prefix": "jinzo_d_ch05",
        "file": "腎臓/ch05_jinzo_糸球体腎炎.html",
        "title": "糸球体腎炎",
        "count": 96
      },
      {
        "prefix": "jinzo_d_ch06",
        "file": "腎臓/ch06_jinzo_その他の腎疾患.html",
        "title": "その他の腎疾患",
        "count": 34
      }
    ]
  },
  {
    "id": "hema",
    "name": "血液",
    "icon": "🩸",
    "color": "#B71C1C",
    "chapters": [
      {
        "prefix": "hema_ch01",
        "file": "血液/ch01_blood_basics.html",
        "title": "血液の基本",
        "count": 39
      },
      {
        "prefix": "hema_ch02",
        "file": "血液/ch02_chemo_transfusion.html",
        "title": "化学療法・輸血・移植",
        "count": 33
      },
      {
        "prefix": "hema_ch03",
        "file": "血液/ch03_anemia_general.html",
        "title": "貧血総論",
        "count": 37
      },
      {
        "prefix": "hema_ch04",
        "file": "血液/ch04_hemolytic_anemia.html",
        "title": "溶血性貧血",
        "count": 52
      },
      {
        "prefix": "hema_ch05",
        "file": "血液/ch05_leukemia.html",
        "title": "白血病",
        "count": 53
      },
      {
        "prefix": "hema_ch06",
        "file": "血液/ch06_bone_marrow.html",
        "title": "骨髄の機能亢進と低下",
        "count": 50
      },
      {
        "prefix": "hema_ch07",
        "file": "血液/ch07_lymphoma_myeloma.html",
        "title": "リンパ腫・骨髄腫",
        "count": 55
      },
      {
        "prefix": "hema_ch08",
        "file": "血液/ch08_coagulation.html",
        "title": "血小板・凝固系の異常",
        "count": 59
      }
    ]
  }
];
const MEC_CHAPTER_META = {
  "endo_ch01": {
    "count": 16,
    "title": "内分泌代謝の基本",
    "file": "内分泌/ch01_endo_basics.html"
  },
  "endo_ch02": {
    "count": 68,
    "title": "視床下部・下垂体前葉",
    "file": "内分泌/ch02_hypothalamus_pituitary_ant.html"
  },
  "endo_ch03": {
    "count": 28,
    "title": "下垂体後葉",
    "file": "内分泌/ch03_posterior_pituitary.html"
  },
  "endo_ch04": {
    "count": 79,
    "title": "甲状腺",
    "file": "内分泌/ch04_thyroid.html"
  },
  "endo_ch05": {
    "count": 16,
    "title": "副甲状腺",
    "file": "内分泌/ch05_parathyroid.html"
  },
  "endo_ch06": {
    "count": 89,
    "title": "副腎",
    "file": "内分泌/ch06_adrenal.html"
  },
  "endo_ch07": {
    "count": 29,
    "title": "内分泌腫瘍とIAS",
    "file": "内分泌/ch07_endocrine_tumors.html"
  },
  "endo_ch08": {
    "count": 98,
    "title": "糖尿病",
    "file": "内分泌/ch08_diabetes.html"
  },
  "endo_ch09": {
    "count": 41,
    "title": "脂質代謝",
    "file": "内分泌/ch09_lipid_metabolism.html"
  },
  "endo_ch10": {
    "count": 78,
    "title": "その他の代謝疾患",
    "file": "内分泌/ch10_other_metabolic.html"
  },
  "resp_ch01": {
    "count": 72,
    "title": "ch01 呼吸器の基本 解答解説",
    "file": "呼吸器/ch01_呼吸器の基本_解答解説.html"
  },
  "resp_ch02": {
    "count": 33,
    "title": "呼吸不全",
    "file": "呼吸器/ch02_呼吸不全_解答解説.html"
  },
  "resp_ch03": {
    "count": 65,
    "title": "閉塞性疾患",
    "file": "呼吸器/ch03_閉塞性疾患_解答解説.html"
  },
  "resp_ch04": {
    "count": 74,
    "title": "間質性疾患",
    "file": "呼吸器/ch04_間質性疾患_解答解説.html"
  },
  "resp_ch05": {
    "count": 37,
    "title": "肺循環障害",
    "file": "呼吸器/ch05_lung_circulation.html"
  },
  "resp_ch06": {
    "count": 81,
    "title": "腫瘍",
    "file": "呼吸器/ch06_tumor.html"
  },
  "resp_ch07": {
    "count": 40,
    "title": "その他の肺疾患",
    "file": "呼吸器/ch07_other_lung_diseases.html"
  },
  "resp_ch08": {
    "count": 66,
    "title": "胸膜・胸腔・縦隔",
    "file": "呼吸器/ch08_pleura_chest.html"
  },
  "resp_ch09": {
    "count": 38,
    "title": "乳房",
    "file": "呼吸器/ch09_breast.html"
  },
  "circ_ch01": {
    "count": 77,
    "title": "循環器の基本",
    "file": "循環器/ch01_circulatory_basics.html"
  },
  "circ_ch02": {
    "count": 50,
    "title": "心不全",
    "file": "循環器/ch02_heart_failure.html"
  },
  "circ_ch03": {
    "count": 98,
    "title": "虚血性心疾患",
    "file": "循環器/ch03_ischemic_heart.html"
  },
  "circ_ch04": {
    "count": 76,
    "title": "不整脈",
    "file": "循環器/ch04_arrhythmia.html"
  },
  "circ_ch05": {
    "count": 75,
    "title": "弁膜症",
    "file": "循環器/ch05_valvular.html"
  },
  "circ_ch06": {
    "count": 65,
    "title": "心膜",
    "file": "循環器/ch06_pericardium.html"
  },
  "circ_ch07": {
    "count": 28,
    "title": "心筋",
    "file": "循環器/ch07_myocardium.html"
  },
  "circ_ch08": {
    "count": 46,
    "title": "大動脈",
    "file": "循環器/ch08_aorta.html"
  },
  "circ_ch09": {
    "count": 31,
    "title": "末梢動静脈・リンパ",
    "file": "循環器/ch09_peripheral_vessels.html"
  },
  "circ_ch10": {
    "count": 26,
    "title": "血圧異常",
    "file": "循環器/ch10_blood_pressure.html"
  },
  "dige_ch01": {
    "count": 51,
    "title": "消化管の基本",
    "file": "消化器/ch01_shokakan_kihon.html"
  },
  "dige_ch02": {
    "count": 38,
    "title": "栄養管理・周術期管理",
    "file": "消化器/ch02_eiyou_kanri.html"
  },
  "dige_ch03": {
    "count": 78,
    "title": "上部消化管出血",
    "file": "消化器/ch03_jyobu_shokakan_shukketsu.html"
  },
  "dige_ch04": {
    "count": 52,
    "title": "食道",
    "file": "消化器/ch04_shokudo.html"
  },
  "dige_ch05": {
    "count": 55,
    "title": "胃",
    "file": "消化器/ch05_i.html"
  },
  "dige_ch06": {
    "count": 53,
    "title": "感染性腸炎",
    "file": "消化器/ch06_kansen_chouen.html"
  },
  "dige_ch07": {
    "count": 41,
    "title": "炎症性腸疾患と機能性消化管障害",
    "file": "消化器/ch07_enshoseityo_kino.html"
  },
  "dige_ch08": {
    "count": 44,
    "title": "イレウスと虚血",
    "file": "消化器/ch08_ileus_kyoketsu.html"
  },
  "dige_ch09": {
    "count": 46,
    "title": "腸腫瘍",
    "file": "消化器/ch09_cho_shuyo.html"
  },
  "dige_ch10": {
    "count": 15,
    "title": "肛門",
    "file": "消化器/ch10_komonbu.html"
  },
  "dige_ch11": {
    "count": 28,
    "title": "横隔膜・腹膜・腹壁",
    "file": "消化器/ch11_yokakumaku_fukumaku_fukuheki.html"
  },
  "neur_ch01": {
    "count": 70,
    "title": "神経の基本",
    "file": "神経/ch01_neuro_basics.html"
  },
  "neur_ch02": {
    "count": 67,
    "title": "脳神経",
    "file": "神経/ch02_cranial_nerves.html"
  },
  "neur_ch03": {
    "count": 106,
    "title": "脳血管障害",
    "file": "神経/ch03_cerebrovascular.html"
  },
  "neur_ch04": {
    "count": 26,
    "title": "高次脳機能障害",
    "file": "神経/ch04_higher_brain.html"
  },
  "neur_ch05": {
    "count": 74,
    "title": "認知症とParkinsonism",
    "file": "神経/ch05_dementia_parkinsonism.html"
  },
  "neur_ch06": {
    "count": 37,
    "title": "運動ニューロン障害と脱髄",
    "file": "神経/ch06_motor_neuron_demyelination.html"
  },
  "neur_ch07": {
    "count": 62,
    "title": "末梢神経・NMJ・筋",
    "file": "神経/ch07_peripheral_nerve_nmj_muscle.html"
  },
  "neur_ch08": {
    "count": 47,
    "title": "神経感染症",
    "file": "神経/ch08_neuro_infection.html"
  },
  "neur_ch09": {
    "count": 41,
    "title": "機能性疾患",
    "file": "神経/ch09_functional.html"
  },
  "neur_ch10": {
    "count": 29,
    "title": "外傷性頭蓋内出血",
    "file": "神経/ch10_traumatic_intracranial.html"
  },
  "neur_ch11": {
    "count": 35,
    "title": "脳腫瘍",
    "file": "神経/ch11_brain_tumor.html"
  },
  "hbp_ch01": {
    "count": 68,
    "title": "肝胆膵の基本",
    "file": "肝胆膵/ch01_kitan_kihon.html"
  },
  "hbp_ch02": {
    "count": 80,
    "title": "急性・慢性肝炎",
    "file": "肝胆膵/ch02_kitan_kanen.html"
  },
  "hbp_ch03": {
    "count": 64,
    "title": "肝硬変",
    "file": "肝胆膵/ch03_kitan_kanshorben.html"
  },
  "hbp_ch04": {
    "count": 56,
    "title": "肝腫瘍",
    "file": "肝胆膵/ch04_kitan_kanshuyo.html"
  },
  "hbp_ch05": {
    "count": 55,
    "title": "胆石・胆囊炎・胆管炎",
    "file": "肝胆膵/ch05_kitan_cholecystitis.html"
  },
  "hbp_ch06": {
    "count": 21,
    "title": "胆腫瘍",
    "file": "肝胆膵/ch06_kitan_biliary_tumor.html"
  },
  "hbp_ch07": {
    "count": 39,
    "title": "膵炎",
    "file": "肝胆膵/ch07_kitan_pancreatitis.html"
  },
  "hbp_ch08": {
    "count": 35,
    "title": "膵腫瘍",
    "file": "肝胆膵/ch08_kitan_pancreatic_tumor.html"
  },
  "jinzo_d_ch01": {
    "count": 48,
    "title": "腎臓の基本",
    "file": "腎臓/ch01_jinzo_腎臓の基本.html"
  },
  "jinzo_d_ch02": {
    "count": 26,
    "title": "血液浄化療法と移植",
    "file": "腎臓/ch02_jinzo_血液浄化療法と移植.html"
  },
  "jinzo_d_ch03": {
    "count": 75,
    "title": "体液・電解質・酸塩基",
    "file": "腎臓/ch03_jinzo_体液・電解質・酸塩基.html"
  },
  "jinzo_d_ch04": {
    "count": 36,
    "title": "腎不全",
    "file": "腎臓/ch04_jinzo_腎不全.html"
  },
  "jinzo_d_ch05": {
    "count": 96,
    "title": "糸球体腎炎",
    "file": "腎臓/ch05_jinzo_糸球体腎炎.html"
  },
  "jinzo_d_ch06": {
    "count": 34,
    "title": "その他の腎疾患",
    "file": "腎臓/ch06_jinzo_その他の腎疾患.html"
  },
  "hema_ch01": {
    "count": 39,
    "title": "血液の基本",
    "file": "血液/ch01_blood_basics.html"
  },
  "hema_ch02": {
    "count": 33,
    "title": "化学療法・輸血・移植",
    "file": "血液/ch02_chemo_transfusion.html"
  },
  "hema_ch03": {
    "count": 37,
    "title": "貧血総論",
    "file": "血液/ch03_anemia_general.html"
  },
  "hema_ch04": {
    "count": 52,
    "title": "溶血性貧血",
    "file": "血液/ch04_hemolytic_anemia.html"
  },
  "hema_ch05": {
    "count": 53,
    "title": "白血病",
    "file": "血液/ch05_leukemia.html"
  },
  "hema_ch06": {
    "count": 50,
    "title": "骨髄の機能亢進と低下",
    "file": "血液/ch06_bone_marrow.html"
  },
  "hema_ch07": {
    "count": 55,
    "title": "リンパ腫・骨髄腫",
    "file": "血液/ch07_lymphoma_myeloma.html"
  },
  "hema_ch08": {
    "count": 59,
    "title": "血小板・凝固系の異常",
    "file": "血液/ch08_coagulation.html"
  }
};
