// Auto-generated by build.py + add_peds_to_meta.py + add_obg_to_meta.py -- do not edit manually
const MEC_CHAPTERS = [
  {
    "id": "endo",
    "name": "内分泌",
    "icon": "⚗️",
    "color": "#169E9F",
    "chapters": [
      {
        "prefix": "endo_ch01",
        "file": "_archive/内分泌/ch01_endo_basics.html",
        "title": "MEC内分泌代謝 第1章 内分泌代謝の基本 解答解説",
        "count": 16
      },
      {
        "prefix": "endo_ch02",
        "file": "_archive/内分泌/ch02_hypothalamus_pituitary_ant.html",
        "title": "MEC内分泌代謝 第2章 視床下部・下垂体前葉 解答解説",
        "count": 68
      },
      {
        "prefix": "endo_ch03",
        "file": "_archive/内分泌/ch03_posterior_pituitary.html",
        "title": "MEC内分泌代謝 第3章 下垂体後葉 解答解説",
        "count": 28
      },
      {
        "prefix": "endo_ch04",
        "file": "_archive/内分泌/ch04_thyroid.html",
        "title": "MEC内分泌代謝 第4章 甲状腺 解答解説",
        "count": 79
      },
      {
        "prefix": "endo_ch05",
        "file": "_archive/内分泌/ch05_parathyroid.html",
        "title": "MEC内分泌代謝 第5章 副甲状腺 解答解説",
        "count": 16
      },
      {
        "prefix": "endo_ch06",
        "file": "_archive/内分泌/ch06_adrenal.html",
        "title": "MEC内分泌代謝 第6章 副腎 解答解説",
        "count": 89
      },
      {
        "prefix": "endo_ch07",
        "file": "_archive/内分泌/ch07_endocrine_tumors.html",
        "title": "MEC内分泌代謝 第7章 内分泌腫瘍とIAS 解答解説",
        "count": 29
      },
      {
        "prefix": "endo_ch08",
        "file": "_archive/内分泌/ch08_diabetes.html",
        "title": "MEC内分泌代謝 第8章 糖尿病 解答解説",
        "count": 98
      },
      {
        "prefix": "endo_ch09",
        "file": "_archive/内分泌/ch09_lipid_metabolism.html",
        "title": "MEC内分泌代謝 第9章 脂質代謝 解答解説",
        "count": 41
      },
      {
        "prefix": "endo_ch10",
        "file": "_archive/内分泌/ch10_other_metabolic.html",
        "title": "MEC内分泌代謝 第10章 その他の代謝疾患 解答解説",
        "count": 78
      }
    ]
  },
  {
    "id": "resp",
    "name": "呼吸器",
    "icon": "🌬️",
    "color": "#4390EE",
    "chapters": [
      {
        "prefix": "resp_ch01",
        "file": "_archive/呼吸器/ch01_呼吸器の基本_解答解説.html",
        "title": "MEC呼吸器 第1章 呼吸器の基本 解答解説",
        "count": 72
      },
      {
        "prefix": "resp_ch02",
        "file": "_archive/呼吸器/ch02_呼吸不全_解答解説.html",
        "title": "MEC呼吸器 第2章 呼吸不全 解答解説",
        "count": 33
      },
      {
        "prefix": "resp_ch03",
        "file": "_archive/呼吸器/ch03_閉塞性疾患_解答解説.html",
        "title": "MEC呼吸器 第3章 閉塞性疾患 解答解説",
        "count": 65
      },
      {
        "prefix": "resp_ch04",
        "file": "_archive/呼吸器/ch04_間質性疾患_解答解説.html",
        "title": "MEC呼吸器 第4章 間質性疾患 解答解説",
        "count": 74
      },
      {
        "prefix": "resp_ch05",
        "file": "_archive/呼吸器/ch05_lung_circulation.html",
        "title": "MEC呼吸器 第5章 肺循環障害 解答解説",
        "count": 37
      },
      {
        "prefix": "resp_ch06",
        "file": "_archive/呼吸器/ch06_tumor.html",
        "title": "MEC呼吸器 第6章 腫瘍 解答解説",
        "count": 81
      },
      {
        "prefix": "resp_ch07",
        "file": "_archive/呼吸器/ch07_other_lung_diseases.html",
        "title": "MEC呼吸器 第7章 その他の肺疾患 解答解説",
        "count": 40
      },
      {
        "prefix": "resp_ch08",
        "file": "_archive/呼吸器/ch08_pleura_chest.html",
        "title": "MEC呼吸器 第8章 胸膜・胸腔・縦隔 解答解説",
        "count": 66
      },
      {
        "prefix": "resp_ch09",
        "file": "_archive/呼吸器/ch09_breast.html",
        "title": "MEC呼吸器 第9章 乳房 解答解説",
        "count": 38
      }
    ]
  },
  {
    "id": "circ",
    "name": "循環器",
    "icon": "❤️",
    "color": "#E16E33",
    "chapters": [
      {
        "prefix": "circ_ch01",
        "file": "_archive/循環器/ch01_circulatory_basics.html",
        "title": "MEC循環器 第1章 循環器の基本 解答解説",
        "count": 77
      },
      {
        "prefix": "circ_ch02",
        "file": "_archive/循環器/ch02_heart_failure.html",
        "title": "MEC循環器 第2章 心不全 解答解説",
        "count": 50
      },
      {
        "prefix": "circ_ch03",
        "file": "_archive/循環器/ch03_ischemic_heart.html",
        "title": "MEC循環器 第3章 虚血性心疾患 解答解説",
        "count": 98
      },
      {
        "prefix": "circ_ch04",
        "file": "_archive/循環器/ch04_arrhythmia.html",
        "title": "MEC循環器 第4章 不整脈 解答解説",
        "count": 76
      },
      {
        "prefix": "circ_ch05",
        "file": "_archive/循環器/ch05_valvular.html",
        "title": "MEC循環器 第5章 弁膜症 解答解説",
        "count": 75
      },
      {
        "prefix": "circ_ch06",
        "file": "_archive/循環器/ch06_pericardium.html",
        "title": "MEC循環器 第6章 心膜 解答解説",
        "count": 65
      },
      {
        "prefix": "circ_ch07",
        "file": "_archive/循環器/ch07_myocardium.html",
        "title": "MEC循環器 第7章 心筋 解答解説",
        "count": 28
      },
      {
        "prefix": "circ_ch08",
        "file": "_archive/循環器/ch08_aorta.html",
        "title": "MEC循環器 第8章 大動脈 解答解説",
        "count": 46
      },
      {
        "prefix": "circ_ch09",
        "file": "_archive/循環器/ch09_peripheral_vessels.html",
        "title": "MEC循環器 第9章 末梢動静脈・リンパ 解答解説",
        "count": 31
      },
      {
        "prefix": "circ_ch10",
        "file": "_archive/循環器/ch10_blood_pressure.html",
        "title": "MEC循環器 第10章 血圧異常 解答解説",
        "count": 26
      }
    ]
  },
  {
    "id": "dige",
    "name": "消化器",
    "icon": "🌿",
    "color": "#8A81EF",
    "chapters": [
      {
        "prefix": "dige_ch01",
        "file": "_archive/消化器/ch01_shokakan_kihon.html",
        "title": "MEC消化器 第1章 消化管の基本 解答解説",
        "count": 51
      },
      {
        "prefix": "dige_ch02",
        "file": "_archive/消化器/ch02_eiyou_kanri.html",
        "title": "MEC消化器 第2章 栄養管理・周術期管理 解答解説",
        "count": 38
      },
      {
        "prefix": "dige_ch03",
        "file": "_archive/消化器/ch03_jyobu_shokakan_shukketsu.html",
        "title": "MEC消化器 第3章 上部消化管出血 解答解説",
        "count": 78
      },
      {
        "prefix": "dige_ch04",
        "file": "_archive/消化器/ch04_shokudo.html",
        "title": "MEC消化器 第4章 食道 解答解説",
        "count": 52
      },
      {
        "prefix": "dige_ch05",
        "file": "_archive/消化器/ch05_i.html",
        "title": "MEC消化器 第5章 胃 解答解説",
        "count": 55
      },
      {
        "prefix": "dige_ch06",
        "file": "_archive/消化器/ch06_kansen_chouen.html",
        "title": "MEC消化器 第6章 感染性腸炎 解答解説",
        "count": 53
      },
      {
        "prefix": "dige_ch07",
        "file": "_archive/消化器/ch07_enshoseityo_kino.html",
        "title": "MEC消化器 第7章 炎症性腸疾患と機能性消化管障害 解答解説",
        "count": 41
      },
      {
        "prefix": "dige_ch08",
        "file": "_archive/消化器/ch08_ileus_kyoketsu.html",
        "title": "MEC消化器 第8章 イレウスと虚血 解答解説",
        "count": 44
      },
      {
        "prefix": "dige_ch09",
        "file": "_archive/消化器/ch09_cho_shuyo.html",
        "title": "MEC消化器 第9章 腸腫瘍 解答解説",
        "count": 46
      },
      {
        "prefix": "dige_ch10",
        "file": "_archive/消化器/ch10_komonbu.html",
        "title": "MEC消化器 第10章 肛門 解答解説",
        "count": 15
      },
      {
        "prefix": "dige_ch11",
        "file": "_archive/消化器/ch11_yokakumaku_fukumaku_fukuheki.html",
        "title": "MEC消化器 第11章 横隔膜・腹膜・腹壁 解答解説",
        "count": 28
      }
    ]
  },
  {
    "id": "neur",
    "name": "神経",
    "icon": "🧠",
    "color": "#619E37",
    "chapters": [
      {
        "prefix": "neur_ch01",
        "file": "_archive/神経/ch01_neuro_basics.html",
        "title": "MEC神経 第1章 神経の基本 解答解説",
        "count": 70
      },
      {
        "prefix": "neur_ch02",
        "file": "_archive/神経/ch02_cranial_nerves.html",
        "title": "MEC神経 第2章 脳神経 解答解説",
        "count": 67
      },
      {
        "prefix": "neur_ch03",
        "file": "_archive/神経/ch03_cerebrovascular.html",
        "title": "MEC神経 第3章 脳血管障害 解答解説",
        "count": 106
      },
      {
        "prefix": "neur_ch04",
        "file": "_archive/神経/ch04_higher_brain.html",
        "title": "MEC神経 第4章 高次脳機能障害 解答解説",
        "count": 26
      },
      {
        "prefix": "neur_ch05",
        "file": "_archive/神経/ch05_dementia_parkinsonism.html",
        "title": "MEC神経 第5章 認知症とParkinsonism 解答解説",
        "count": 74
      },
      {
        "prefix": "neur_ch06",
        "file": "_archive/神経/ch06_motor_neuron_demyelination.html",
        "title": "MEC神経 第6章 運動ニューロン障害と脱髄 解答解説",
        "count": 37
      },
      {
        "prefix": "neur_ch07",
        "file": "_archive/神経/ch07_peripheral_nerve_nmj_muscle.html",
        "title": "MEC神経 第7章 末梢神経・NMJ・筋 解答解説",
        "count": 62
      },
      {
        "prefix": "neur_ch08",
        "file": "_archive/神経/ch08_neuro_infection.html",
        "title": "MEC神経 第8章 神経感染症 解答解説",
        "count": 47
      },
      {
        "prefix": "neur_ch09",
        "file": "_archive/神経/ch09_functional.html",
        "title": "MEC神経 第9章 機能性疾患 解答解説",
        "count": 41
      },
      {
        "prefix": "neur_ch10",
        "file": "_archive/神経/ch10_traumatic_intracranial.html",
        "title": "MEC神経 第10章 外傷性頭蓋内出血 解答解説",
        "count": 29
      },
      {
        "prefix": "neur_ch11",
        "file": "_archive/神経/ch11_brain_tumor.html",
        "title": "MEC神経 第11章 脳腫瘍 解答解説",
        "count": 35
      }
    ]
  },
  {
    "id": "hbp",
    "name": "肝胆膵",
    "icon": "🧪",
    "color": "#C0820E",
    "chapters": [
      {
        "prefix": "hbp_ch01",
        "file": "_archive/肝胆膵/ch01_kitan_kihon.html",
        "title": "MEC肝胆膵 第1章 肝胆膵の基本 解答解説",
        "count": 68
      },
      {
        "prefix": "hbp_ch02",
        "file": "_archive/肝胆膵/ch02_kitan_kanen.html",
        "title": "MEC肝胆膵 第2章 急性・慢性肝炎 解答解説",
        "count": 80
      },
      {
        "prefix": "hbp_ch03",
        "file": "_archive/肝胆膵/ch03_kitan_kanshorben.html",
        "title": "MEC肝胆膵 第3章 肝硬変 解答解説",
        "count": 64
      },
      {
        "prefix": "hbp_ch04",
        "file": "_archive/肝胆膵/ch04_kitan_kanshuyo.html",
        "title": "MEC肝胆膵 第4章 肝腫瘍 解答解説",
        "count": 56
      },
      {
        "prefix": "hbp_ch05",
        "file": "_archive/肝胆膵/ch05_kitan_cholecystitis.html",
        "title": "MEC肝胆膵 第5章 胆石・胆囊炎・胆管炎 解答解説",
        "count": 55
      },
      {
        "prefix": "hbp_ch06",
        "file": "_archive/肝胆膵/ch06_kitan_biliary_tumor.html",
        "title": "MEC肝胆膵 第6章 胆腫瘍 解答解説",
        "count": 21
      },
      {
        "prefix": "hbp_ch07",
        "file": "_archive/肝胆膵/ch07_kitan_pancreatitis.html",
        "title": "MEC肝胆膵 第7章 膵炎 解答解説",
        "count": 39
      },
      {
        "prefix": "hbp_ch08",
        "file": "_archive/肝胆膵/ch08_kitan_pancreatic_tumor.html",
        "title": "MEC肝胆膵 第8章 膵腫瘍 解答解説",
        "count": 35
      }
    ]
  },
  {
    "id": "jinzo_d",
    "name": "腎臓",
    "icon": "💧",
    "color": "#7494A1",
    "chapters": [
      {
        "prefix": "jinzo_d_ch01",
        "file": "_archive/腎臓/ch01_jinzo_腎臓の基本.html",
        "title": "MEC腎臓 第1章 腎臓の基本 解答解説",
        "count": 48
      },
      {
        "prefix": "jinzo_d_ch02",
        "file": "_archive/腎臓/ch02_jinzo_血液浄化療法と移植.html",
        "title": "MEC腎臓 第2章 血液浄化療法と移植 解答解説",
        "count": 26
      },
      {
        "prefix": "jinzo_d_ch03",
        "file": "_archive/腎臓/ch03_jinzo_体液・電解質・酸塩基.html",
        "title": "MEC腎臓 第3章 体液・電解質・酸塩基 解答解説",
        "count": 75
      },
      {
        "prefix": "jinzo_d_ch04",
        "file": "_archive/腎臓/ch04_jinzo_腎不全.html",
        "title": "MEC腎臓 第4章 腎不全 解答解説",
        "count": 36
      },
      {
        "prefix": "jinzo_d_ch05",
        "file": "_archive/腎臓/ch05_jinzo_糸球体腎炎.html",
        "title": "MEC腎臓 第5章 糸球体腎炎 解答解説",
        "count": 96
      },
      {
        "prefix": "jinzo_d_ch06",
        "file": "_archive/腎臓/ch06_jinzo_その他の腎疾患.html",
        "title": "MEC腎臓 第6章 その他の腎疾患 解答解説",
        "count": 34
      }
    ]
  },
  {
    "id": "hema",
    "name": "血液",
    "icon": "🩸",
    "color": "#E56574",
    "chapters": [
      {
        "prefix": "hema_ch01",
        "file": "_archive/血液/ch01_blood_basics.html",
        "title": "MEC血液 第1章 血液の基本 解答解説",
        "count": 39
      },
      {
        "prefix": "hema_ch02",
        "file": "_archive/血液/ch02_chemo_transfusion.html",
        "title": "MEC血液 第2章 化学療法・輸血・移植 解答解説",
        "count": 33
      },
      {
        "prefix": "hema_ch03",
        "file": "_archive/血液/ch03_anemia_general.html",
        "title": "MEC血液 第3章 貧血総論 解答解説",
        "count": 37
      },
      {
        "prefix": "hema_ch04",
        "file": "_archive/血液/ch04_hemolytic_anemia.html",
        "title": "MEC血液 第4章 溶血性貧血 解答解説",
        "count": 52
      },
      {
        "prefix": "hema_ch05",
        "file": "_archive/血液/ch05_leukemia.html",
        "title": "MEC血液 第5章 白血病 解答解説",
        "count": 53
      },
      {
        "prefix": "hema_ch06",
        "file": "_archive/血液/ch06_bone_marrow.html",
        "title": "MEC血液 第6章 骨髄の機能亢進と低下 解答解説",
        "count": 50
      },
      {
        "prefix": "hema_ch07",
        "file": "_archive/血液/ch07_lymphoma_myeloma.html",
        "title": "MEC血液 第7章 リンパ腫・骨髄腫 解答解説",
        "count": 55
      },
      {
        "prefix": "hema_ch08",
        "file": "_archive/血液/ch08_coagulation.html",
        "title": "MEC血液 第8章 血小板・凝固系の異常 解答解説",
        "count": 59
      }
    ]
  },
  {
    "id": "imma",
    "name": "免アレ膠",
    "icon": "🛡️",
    "color": "#B973D7",
    "chapters": [
      {
        "prefix": "imma_ch01",
        "file": "_archive/免アレ膠/ch01_immare.html",
        "title": "MEC免アレ膠 第1章 免疫の基本 解答解説",
        "count": 42
      },
      {
        "prefix": "imma_ch02",
        "file": "_archive/免アレ膠/ch02_immare.html",
        "title": "MEC免アレ膠 第2章 アレルギー分類 解答解説",
        "count": 37
      },
      {
        "prefix": "imma_ch03",
        "file": "_archive/免アレ膠/ch03_immare.html",
        "title": "MEC免アレ膠 第3章 リウマチと類縁疾患 解答解説",
        "count": 40
      },
      {
        "prefix": "imma_ch04",
        "file": "_archive/免アレ膠/ch04_immare.html",
        "title": "MEC免アレ膠 第4章 結合組織疾患 解答解説",
        "count": 78
      },
      {
        "prefix": "imma_ch05",
        "file": "_archive/免アレ膠/ch05_immare.html",
        "title": "MEC免アレ膠 第5章 血管炎 解答解説",
        "count": 50
      }
    ]
  },
  {
    "id": "kansen",
    "name": "感染症",
    "icon": "🦠",
    "color": "#9B920A",
    "chapters": [
      {
        "prefix": "kansen_ch01",
        "file": "_archive/感染症/ch01_kansen_basics.html",
        "title": "MEC感染症 第1章 感染症の基本 解答解説",
        "count": 80
      },
      {
        "prefix": "kansen_ch02",
        "file": "_archive/感染症/ch02_kansen_gi.html",
        "title": "MEC感染症 第2章 消化器の感染症 解答解説",
        "count": 18
      },
      {
        "prefix": "kansen_ch03",
        "file": "_archive/感染症/ch03_kansen_skin.html",
        "title": "MEC感染症 第3章 皮膚の感染症 解答解説",
        "count": 45
      },
      {
        "prefix": "kansen_ch04",
        "file": "_archive/感染症/ch04_kansen_resp.html",
        "title": "MEC感染症 第4章 呼吸器の感染症 解答解説",
        "count": 96
      },
      {
        "prefix": "kansen_ch05",
        "file": "_archive/感染症/ch05_kansen_ntm.html",
        "title": "MEC感染症 第5章 抗酸菌感染症 解答解説",
        "count": 40
      },
      {
        "prefix": "kansen_ch06",
        "file": "_archive/感染症/ch06_kansen_hiv.html",
        "title": "MEC感染症 第6章 HIVと日和見感染症 解答解説",
        "count": 53
      },
      {
        "prefix": "kansen_ch07",
        "file": "_archive/感染症/ch07_kansen_other.html",
        "title": "MEC感染症 第7章 その他の感染症 解答解説",
        "count": 24
      }
    ]
  },
  {
    "id": "peds",
    "name": "小児科",
    "icon": "🧸",
    "color": "#10A276",
    "chapters": [
      {
        "prefix": "peds_ch01",
        "file": "_archive/小児科/ch01_seicho_hattatsu.html",
        "title": "第1章 成長と発達",
        "count": 74
      },
      {
        "prefix": "peds_ch02",
        "file": "_archive/小児科/ch02_shinseiji.html",
        "title": "第2章 新生児",
        "count": 32
      },
      {
        "prefix": "peds_ch03",
        "file": "_archive/小児科/ch03_senten_ijou.html",
        "title": "第3章 先天異常",
        "count": 33
      },
      {
        "prefix": "peds_ch04",
        "file": "_archive/小児科/ch04_shonika_shinkei.html",
        "title": "第4章 小児の神経",
        "count": 34
      },
      {
        "prefix": "peds_ch05",
        "file": "_archive/小児科/ch05_shonika_junkanki.html",
        "title": "第5章 小児の循環器",
        "count": 25
      },
      {
        "prefix": "peds_ch06",
        "file": "_archive/小児科/ch06_shonika_kokyuki.html",
        "title": "第6章 小児の呼吸器",
        "count": 22
      },
      {
        "prefix": "peds_ch07",
        "file": "_archive/小児科/ch07_shonika_kansen.html",
        "title": "第7章 小児の感染症",
        "count": 26
      },
      {
        "prefix": "peds_ch08",
        "file": "_archive/小児科/ch08_shonika_shokakan.html",
        "title": "第8章 小児の消化管",
        "count": 29
      },
      {
        "prefix": "peds_ch09",
        "file": "_archive/小児科/ch09_shonika_kantanmi.html",
        "title": "第9章 小児の肝胆膵",
        "count": 8
      },
      {
        "prefix": "peds_ch10",
        "file": "_archive/小児科/ch10_shonika_naibunpitsu.html",
        "title": "第10章 小児の内分泌代謝",
        "count": 32
      },
      {
        "prefix": "peds_ch11",
        "file": "_archive/小児科/ch11_shonika_jinzo.html",
        "title": "第11章 小児の腎・泌尿器",
        "count": 12
      },
      {
        "prefix": "peds_ch12",
        "file": "_archive/小児科/ch12_shonika_immare.html",
        "title": "第12章 小児の免疫・膠原病・アレルギー",
        "count": 21
      },
      {
        "prefix": "peds_ch13",
        "file": "_archive/小児科/ch13_shonika_sonota.html",
        "title": "第13章 その他の重要疾患",
        "count": 25
      }
    ]
  },
  {
    "id": "obg",
    "name": "産婦人科",
    "icon": "🤰",
    "color": "#D36BAA",
    "chapters": [
      {
        "prefix": "obg_ch01",
        "file": "産婦人科/ch01_sanfujinka_soron.html",
        "title": "第1章 産婦人科総論",
        "count": 26
      },
      {
        "prefix": "obg_ch02",
        "file": "産婦人科/ch02_seijou_ninshin.html",
        "title": "第2章 正常妊娠",
        "count": 59
      },
      {
        "prefix": "obg_ch03",
        "file": "産婦人科/ch03_ninshin_shoki.html",
        "title": "第3章 妊娠初期",
        "count": 60
      },
      {
        "prefix": "obg_ch04",
        "file": "産婦人科/ch04_ninshin_chuki.html",
        "title": "第4章 妊娠中期",
        "count": 42
      },
      {
        "prefix": "obg_ch05",
        "file": "産婦人科/ch05_ninshin_kouki.html",
        "title": "第5章 妊娠後期",
        "count": 49
      },
      {
        "prefix": "obg_ch06",
        "file": "産婦人科/ch06_ninshin_gappeishou.html",
        "title": "第6章 妊娠合併症",
        "count": 92
      },
      {
        "prefix": "obg_ch07",
        "file": "産婦人科/ch07_bunben.html",
        "title": "第7章 分娩",
        "count": 67
      },
      {
        "prefix": "obg_ch08",
        "file": "産婦人科/ch08_sanjoku.html",
        "title": "第8章 産褥",
        "count": 54
      },
      {
        "prefix": "obg_ch09",
        "file": "産婦人科/ch09_gekkei_funin.html",
        "title": "第9章 月経異常・不妊・性分化／染色体異常",
        "count": 55
      },
      {
        "prefix": "obg_ch10",
        "file": "産婦人科/ch10_fujinka_shuyou.html",
        "title": "第10章 婦人科腫瘍",
        "count": 107
      },
      {
        "prefix": "obg_ch11",
        "file": "産婦人科/ch11_kansenshou.html",
        "title": "第11章 感染症",
        "count": 26
      },
      {
        "prefix": "obg_ch12",
        "file": "産婦人科/ch12_kounenki.html",
        "title": "第12章 更年期障害",
        "count": 20
      },
      {
        "prefix": "obg_ch13",
        "file": "産婦人科/ch13_120kai.html",
        "title": "第13章 第120回国試問題",
        "count": 28
      }
    ]
  },
  {
    "id": "psy",
    "name": "精神科",
    "icon": "💭",
    "color": "#5E60CE",
    "chapters": [
      {
        "prefix": "psy_ch01",
        "file": "精神科/ch01_seishinka_kihon.html",
        "title": "第1章 精神科の基本",
        "count": 73
      },
      {
        "prefix": "psy_ch02",
        "file": "精神科/ch02_tougoushitchoushou.html",
        "title": "第2章 統合失調症",
        "count": 25
      },
      {
        "prefix": "psy_ch03",
        "file": "精神科/ch03_kibunshougai.html",
        "title": "第3章 気分障害",
        "count": 41
      },
      {
        "prefix": "psy_ch04",
        "file": "精神科/ch04_shinkeishousei.html",
        "title": "第4章 神経症性障害",
        "count": 36
      },
      {
        "prefix": "psy_ch05",
        "file": "精神科/ch05_suiminshougai.html",
        "title": "第5章 睡眠の生理と睡眠障害",
        "count": 18
      },
      {
        "prefix": "psy_ch06",
        "file": "精神科/ch06_yakubutsu.html",
        "title": "第6章 薬物に伴う精神行動障害",
        "count": 25
      },
      {
        "prefix": "psy_ch07",
        "file": "精神科/ch07_hattatsushougai.html",
        "title": "第7章 発達障害と小児の精神障害",
        "count": 24
      },
      {
        "prefix": "psy_ch08",
        "file": "精神科/ch08_sonota.html",
        "title": "第8章 その他の精神疾患",
        "count": 14
      }
    ]
  },
  {
    "id": "derm",
    "name": "皮膚科",
    "icon": "🩹",
    "color": "#B5654A",
    "chapters": [
      {
        "prefix": "derm_ch01",
        "file": "皮膚科/ch01_hifuka_kihon.html",
        "title": "第1章 皮膚科の基本",
        "count": 27
      },
      {
        "prefix": "derm_ch02",
        "file": "皮膚科/ch02_hifuen_jinmashin.html",
        "title": "第2章 皮膚炎と蕁麻疹",
        "count": 27
      },
      {
        "prefix": "derm_ch03",
        "file": "皮膚科/ch03_kouhan.html",
        "title": "第3章 紅斑",
        "count": 27
      },
      {
        "prefix": "derm_ch04",
        "file": "皮膚科/ch04_kakukashou.html",
        "title": "第4章 角化症",
        "count": 17
      },
      {
        "prefix": "derm_ch05",
        "file": "皮膚科/ch05_suihou_nouhou.html",
        "title": "第5章 水疱・膿疱",
        "count": 23
      },
      {
        "prefix": "derm_ch06",
        "file": "皮膚科/ch06_bohan_ryousei_shuyou.html",
        "title": "第6章 母斑と良性腫瘍",
        "count": 29
      },
      {
        "prefix": "derm_ch07",
        "file": "皮膚科/ch07_akusei_shuyou.html",
        "title": "第7章 悪性腫瘍",
        "count": 40
      },
      {
        "prefix": "derm_ch08",
        "file": "皮膚科/ch08_kansenshou.html",
        "title": "第8章 感染症",
        "count": 32
      },
      {
        "prefix": "derm_ch09",
        "file": "皮膚科/ch09_sonota.html",
        "title": "第9章 その他の皮膚疾患",
        "count": 27
      }
    ]
  },
  {
    "id": "oph",
    "name": "眼科",
    "icon": "👁️",
    "color": "#0E7490",
    "chapters": [
      {
        "prefix": "oph_ch01",
        "file": "眼科/ch01_ganka_kihon.html",
        "title": "第1章 眼科の基本",
        "count": 50
      },
      {
        "prefix": "oph_ch02",
        "file": "眼科/ch02_ketsumaku_kakumaku.html",
        "title": "第2章 結膜・角膜疾患",
        "count": 26
      }
    ]
  }
];
const MEC_CHAPTER_META = {
  "peds_ch01": {
    "count": 74,
    "title": "第1章 成長と発達",
    "file": "_archive/小児科/ch01_seicho_hattatsu.html"
  },
  "peds_ch02": {
    "count": 32,
    "title": "第2章 新生児",
    "file": "_archive/小児科/ch02_shinseiji.html"
  },
  "peds_ch03": {
    "count": 33,
    "title": "第3章 先天異常",
    "file": "_archive/小児科/ch03_senten_ijou.html"
  },
  "peds_ch04": {
    "count": 34,
    "title": "第4章 小児の神経",
    "file": "_archive/小児科/ch04_shonika_shinkei.html"
  },
  "peds_ch05": {
    "count": 25,
    "title": "第5章 小児の循環器",
    "file": "_archive/小児科/ch05_shonika_junkanki.html"
  },
  "peds_ch06": {
    "count": 22,
    "title": "第6章 小児の呼吸器",
    "file": "_archive/小児科/ch06_shonika_kokyuki.html"
  },
  "peds_ch07": {
    "count": 26,
    "title": "第7章 小児の感染症",
    "file": "_archive/小児科/ch07_shonika_kansen.html"
  },
  "peds_ch08": {
    "count": 29,
    "title": "第8章 小児の消化管",
    "file": "_archive/小児科/ch08_shonika_shokakan.html"
  },
  "peds_ch09": {
    "count": 8,
    "title": "第9章 小児の肝胆膵",
    "file": "_archive/小児科/ch09_shonika_kantanmi.html"
  },
  "peds_ch10": {
    "count": 32,
    "title": "第10章 小児の内分泌代謝",
    "file": "_archive/小児科/ch10_shonika_naibunpitsu.html"
  },
  "peds_ch11": {
    "count": 12,
    "title": "第11章 小児の腎・泌尿器",
    "file": "_archive/小児科/ch11_shonika_jinzo.html"
  },
  "peds_ch12": {
    "count": 21,
    "title": "第12章 小児の免疫・膠原病・アレルギー",
    "file": "_archive/小児科/ch12_shonika_immare.html"
  },
  "peds_ch13": {
    "count": 25,
    "title": "第13章 その他の重要疾患",
    "file": "_archive/小児科/ch13_shonika_sonota.html"
  },
  "obg_ch01": {
    "count": 26,
    "title": "第1章 産婦人科総論",
    "file": "産婦人科/ch01_sanfujinka_soron.html"
  },
  "obg_ch02": {
    "count": 59,
    "title": "第2章 正常妊娠",
    "file": "産婦人科/ch02_seijou_ninshin.html"
  },
  "obg_ch03": {
    "count": 60,
    "title": "第3章 妊娠初期",
    "file": "産婦人科/ch03_ninshin_shoki.html"
  },
  "obg_ch04": {
    "count": 42,
    "title": "第4章 妊娠中期",
    "file": "産婦人科/ch04_ninshin_chuki.html"
  },
  "obg_ch05": {
    "count": 49,
    "title": "第5章 妊娠後期",
    "file": "産婦人科/ch05_ninshin_kouki.html"
  },
  "obg_ch06": {
    "count": 92,
    "title": "第6章 妊娠合併症",
    "file": "産婦人科/ch06_ninshin_gappeishou.html"
  },
  "obg_ch07": {
    "count": 67,
    "title": "第7章 分娩",
    "file": "産婦人科/ch07_bunben.html"
  },
  "obg_ch08": {
    "count": 54,
    "title": "第8章 産褥",
    "file": "産婦人科/ch08_sanjoku.html"
  },
  "obg_ch09": {
    "count": 55,
    "title": "第9章 月経異常・不妊・性分化／染色体異常",
    "file": "産婦人科/ch09_gekkei_funin.html"
  },
  "obg_ch10": {
    "count": 107,
    "title": "第10章 婦人科腫瘍",
    "file": "産婦人科/ch10_fujinka_shuyou.html"
  },
  "obg_ch11": {
    "count": 26,
    "title": "第11章 感染症",
    "file": "産婦人科/ch11_kansenshou.html"
  },
  "obg_ch12": {
    "count": 20,
    "title": "第12章 更年期障害",
    "file": "産婦人科/ch12_kounenki.html"
  },
  "obg_ch13": {
    "count": 28,
    "title": "第13章 第120回国試問題",
    "file": "産婦人科/ch13_120kai.html"
  }
};
