// 自動生成: node _work/extract_mindmap_data.js — 直接編集してよいが、再生成で消える
// ハブ（全科目マップ）の代表疾患。科目マップとは別に選抜されたもので、射影ではない。
window.MM_HUB = {
  subjects: [
    { sid: "endo", diseases: [
      { id: "endo_dm", label: "糖尿病",
        keys: ["1型/2型；HbA1c≥6.5%で診断","DKA（1型）・HHS（2型）：急性合併症","三大慢性合併症：網膜症・腎症・神経障害","心血管リスク：AMI・脳梗塞・末梢動脈疾患の主要危険因子"] },
      { id: "endo_hyper", label: "甲状腺機能亢進症",
        keys: ["バセドウ病（抗TSHr抗体）；FT4↑・TSH↓","心房細動・骨粗鬆症・心不全誘発","甲状腺クリーゼ：発熱・意識障害→緊急（MMI+ヨード+βB+ステロイド）","抗甲状腺薬（MMI第一選択）・RAI・手術"] },
      { id: "endo_cush", label: "クッシング症候群",
        keys: ["ACTH依存性（下垂体/異所性）vs 非依存性","満月様顔・水牛肩・皮膚線条・高血圧・高血糖・易感染","深夜コルチゾール↑・0.5mg DST非抑制","下垂体腺腫→経蝶形骨洞手術；副腎腫瘍→副腎摘除"] },
      { id: "endo_aldo", label: "原発性アルドステロン症",
        keys: ["アルドステロン過剰（副腺腫/過形成）","高血圧＋低K血症；ARR>200で疑い","副腎静脈サンプリングで側性診断","腺腫→腹腔鏡下摘除；両側過形成→MRA（スピロノラクトン）"] },
      { id: "endo_pheo", label: "褐色細胞腫",
        keys: ["副腎髄質のカテコラミン産生腫瘍（10%悪性・両側・副腎外）","発作性頭痛・発汗・動悸（三徴）","尿中カテコラミン・メタネフリン↑；MIBG/PETシンチ","術前α遮断（フェノキシベンザミン）を十分に行ってから手術"] },
      { id: "endo_hca", label: "高Ca血症",
        keys: ["原発性副甲状腺機能亢進症（最多）・悪性腫瘍（PTHrP）","多尿・便秘・筋力低下・精神症状・腎結石","PTH↑→原発性；PTH↓・PTHrP↑→悪性腫瘍","治療：補液＋ビスホスホネート；重症→透析"] },
      { id: "endo_adrenal", label: "副腎不全",
        keys: ["原発性（Addison）：コルチゾール↓・アルドステロン↓","低血圧・低Na・高K・色素沈着（MSH過剰）","副腎クリーゼ：ヒドロコルチゾン100mg急速静注が最優先","自己免疫（先進国）・転移癌（肺癌が多い）・結核"] },
      { id: "endo_met", label: "代謝症候群",
        keys: ["内臓脂肪型肥満＋血糖・血圧・脂質の3因子","高LDL：スタチン；FH（腱黄色腫）→PCSK9阻害薬","高尿酸血症（>7 mg/dL）→痛風発作・尿路結石","インスリン抵抗性→2型DM・NASH・多嚢胞性卵巣症候群"] },
    ] },
    { sid: "circ", diseases: [
      { id: "circ_ami", label: "急性心筋梗塞",
        keys: ["STEMI：ST上昇→緊急PCI（DTB<90分）","Killip分類；Tn↑・CK-MB↑","合併症：乳頭筋断裂・VSP・自由壁破裂・心室瘤","二次予防：DAPT＋スタチン＋ACE-I＋βB"] },
      { id: "circ_hf", label: "心不全",
        keys: ["HFrEF(EF<40%)：ARNI+βB+MRA+SGLT2（4剤）","HFpEF(EF≥50%)：SGLT2・利尿薬","BNP>100 pg/mL；NYHA分類","心腎症候群：心出力↓→腎灌流↓→AKI→利尿薬抵抗"] },
      { id: "circ_af", label: "心房細動",
        keys: ["f波不整；CHADS₂スコアで脳塞栓リスク評価","CHADS₂≥2：DOAC（抗凝固）必須","レートコントロール vs リズムコントロール","肺静脈隔離術（PVI）：根治的カテーテルアブレーション"] },
      { id: "circ_ie", label: "感染性心内膜炎",
        keys: ["疣贅（vegetation）→塞栓症（脳・腎・脾・冠）","発熱＋新規心雑音；血液培養3セット（抗菌薬前）","TEEで疣贅・弁破壊・膿瘍；Duke基準","長期抗菌薬（4-6週）；手術適応：弁破壊・難治・塞栓反復"] },
      { id: "circ_aod", label: "大動脈解離",
        keys: ["Stanford A型→緊急手術；B型→降圧薬（ICU管理）","突然の引き裂かれる痛み；血圧左右差","A型合併症：AR・心タンポ・冠動脈閉塞・脳虚血","Marfan・二尖弁・高血圧が背景"] },
      { id: "circ_dvt", label: "深部静脈血栓症",
        keys: ["Virchow三徴；下肢腫脹・熱感・Homan徴候","D-dimer↑（感度高）；超音波圧迫試験（特異度高）","DOAC治療（リバーロキサバン等）；予防：早期離床","ネフローゼ・癌・長期臥床・経口避妊薬が危険因子"] },
      { id: "circ_htn", label: "高血圧",
        keys: ["≥140/90 mmHg；家庭血圧≥135/85","ARB/ACE-I・Ca拮抗薬・サイアザイド系","二次性高血圧：原発性アルドステロン症（最多）","高血圧緊急症：臓器障害合併→ニカルジピン静注"] },
      { id: "circ_pah", label: "肺高血圧",
        keys: ["mPAP≥25 mmHg（安静時）；右心カテ確定","PAH：ERA・PDE5阻害薬・プロスタサイクリン","COPD/間質性肺疾患→続発性PH→右心不全","右心不全：頸静脈怒張・肝腫大・下腿浮腫"] },
    ] },
    { sid: "resp", diseases: [
      { id: "resp_copd", label: "COPD",
        keys: ["喫煙→気流制限（FEV1/FVC<0.70）；GOLD分類","LABA/LAMA/ICS；増悪：ステロイド+抗菌薬+NPPV","肺高血圧・右心不全・自然気胸・呼吸不全合併","禁煙が最重要（進行抑制）；肺リハ・在宅酸素"] },
      { id: "resp_lc", label: "肺癌",
        keys: ["腺癌（末梢型）・扁平上皮癌（中枢型）・SCLC","EGFR変異（腺癌）→オシメルチニブ；ALK転座→アレクチニブ","SCLC：EP療法＋PCI；予後不良","副腎転移（最多）・脳転移・骨転移・肝転移"] },
      { id: "resp_tb", label: "肺結核",
        keys: ["M. tuberculosis；飛沫核感染；空洞形成・上葉優位","IGRA（T-SPOT/QFN）；HRZE×2→HR×4か月","粟粒結核・結核性髄膜炎・結核性胸膜炎","DOTS；届出（2類感染症）；潜在性結核→INH予防内服"] },
      { id: "resp_iip", label: "間質性肺炎",
        keys: ["UIP/IPF：蜂巣肺；ピルフェニドン/ニンテダニブ","膠原病関連ILD（RA・SSc・PM/DM；抗Jo-1抗体）","急性増悪：6か月以内の急速悪化→高死亡率","KL-6・SP-D↑；HRCT：蜂巣肺・牽引性気管支拡張"] },
      { id: "resp_pte", label: "肺血栓塞栓症",
        keys: ["DVTからの血栓塞栓；胸痛・呼吸困難・頻脈・SpO₂↓","CT-PA（造影）が標準；D-dimer↑・ECHO：右心負荷","大量PTE（血行不安定）→血栓溶解療法","UFH急性期→DOAC長期；IVCフィルターは限定的"] },
      { id: "resp_ards", label: "ARDS",
        keys: ["急性発症・両側浸潤影・P/F<300・非心原性","原因：敗血症（最多）・誤嚥・膵炎・DIC・輸血","肺保護換気（Vt 6 mL/kg・Pplat<30）・腹臥位","死亡率30-45%；多臓器不全に進展"] },
      { id: "resp_pneu", label: "重症肺炎",
        keys: ["市中：肺炎球菌・レジオネラ；A-DROP/PSIスコア","院内：MRSA・緑膿菌；誤嚥性：嫌気性菌","ICU管理：敗血症・ARDS・膿胸・呼吸不全合併時","菌血症→敗血症性ショック→DIC合併"] },
      { id: "resp_sarc", label: "サルコイドーシス",
        keys: ["非乾酪性肉芽腫；BHL（両側肺門リンパ節腫脹）","高Ca血症（活性型VitD産生↑）・眼病変・皮膚病変・心病変","ACE値↑・sIL-2R↑；ガリウムシンチ/FDG-PET","無症状は経過観察；有症状/重症臓器病変→ステロイド"] },
    ] },
    { sid: "neur", diseases: [
      { id: "neur_stroke", label: "脳梗塞",
        keys: ["心原性（AF）・アテローム血栓性・ラクナ","t-PA（4.5時間）・血栓回収（24時間）；NIHSS","DWI高信号+ADC低下=急性期梗塞","二次予防：AF→DOAC；非心原性→抗血小板薬"] },
      { id: "neur_ich", label: "脳出血・SAH",
        keys: ["高血圧性：被殻（最多）・視床・橋・小脳","SAH：今まで最悪の頭痛；CT→腰椎穿刺；動脈瘤クリッピング/コイル","脳血管攣縮（SAH4-14日）：Nimodipine","ICP管理：頭部挙上30°・マンニトール・過換気"] },
      { id: "neur_pd", label: "パーキンソン病",
        keys: ["安静時振戦・筋強剛・動作緩慢・姿勢反射障害","Lewy小体（α-syn）；黒質線条体ドパミン欠乏","L-dopa（第一選択）；wearing off/on-off→MAO-B阻害薬","誤嚥性肺炎・起立性低血圧・認知症（DLBへの連続性）"] },
      { id: "neur_ad", label: "Alzheimer病",
        keys: ["Aβ老人斑＋タウ；海馬から発症","記憶障害→見当識→BPSD→全介護","ChEI（ドネペジル）・レカネマブ（抗Aβ抗体）","誤嚥性肺炎・感染症が最終的な死因"] },
      { id: "neur_ep", label: "てんかん",
        keys: ["焦点性（focal）vs 全般性；脳腫瘍・脳梗塞後・代謝異常が二次性原因","重積状態：5分以上→ジアゼパム→ホスフェニトイン","CBZ→低Na血症（SIADH）；VPA→催奇形性","脳波（EEG）：棘波・鋭徐波複合で診断"] },
      { id: "neur_gbs", label: "ギラン・バレー症候群",
        keys: ["上行性弛緩性麻痺；先行感染（カンピロ等）後1-3週","髄液：細胞蛋白解離；NCS：脱髄","IVIG（0.4g/kg×5日）or 血漿交換；ステロイド無効","自律神経障害・呼吸筋麻痺→ICU（人工呼吸）"] },
      { id: "neur_mg", label: "重症筋無力症",
        keys: ["抗AChR抗体（85%）or 抗MuSK抗体；NMJ障害","易疲労性（夕方増悪）；Edrophonium test","胸腺腫合併（15%）→胸腺摘除","MGクリーゼ：呼吸筋麻痺→血漿交換/IVIG＋ICU挿管"] },
      { id: "neur_ms", label: "多発性硬化症",
        keys: ["時間的・空間的多発；白質脱髄病変","視神経炎・横断性脊髄炎・INO（核間性眼筋麻痺）","急性期：ステロイドパルス；DMT：オクレリズマブ等","視神経脊髄炎（NMOSD）：抗AQP4抗体；β-IFN悪化"] },
    ] },
    { sid: "dige", diseases: [
      { id: "gi_uc", label: "潰瘍性大腸炎",
        keys: ["直腸から連続性；びらん・浅潰瘍；粘血便","5-ASA→ステロイド→タクロリムス→抗TNF-α","中毒性巨大結腸症（緊急手術）；長期→大腸癌","PSC合併（UC患者の5%）：黄疸・肝酵素上昇"] },
      { id: "gi_cd", label: "クローン病",
        keys: ["非連続性・全層性；縦走潰瘍・敷石像・狭窄・瘻孔","回盲部好発；抗TNF-α（infliximab等）第一選択","腸管外合併症：関節炎・虹彩炎・壊疽性膿皮症","栄養療法（成分栄養）；短腸症候群・膿瘍・癌化"] },
      { id: "gi_crc", label: "大腸癌",
        keys: ["S状結腸・直腸が最多；Dukes/TNM；腺癌","EMR/ESD（T1a）；D3郭清付き外科切除","化学療法：FOLFOX/FOLFIRI＋Bev or Cet（RAS野生型）","同時性肝転移（20-30%）；腹膜播種；肺転移"] },
      { id: "gi_gc", label: "胃癌",
        keys: ["H. pylori・塩分；スキルス（4型）予後不良","EMR/ESD（T1a）；D2郭清付き胃切除","S-1±CDDP；HER2+→トラスツズマブ","腹膜播種（Krukenberg腫瘍）・Virchow転移"] },
      { id: "gi_bleed", label: "消化管出血",
        keys: ["上部（吐血/タール便）：消化性潰瘍・食道静脈瘤","下部（鮮血便）：大腸憩室・癌・痔核","緊急内視鏡（24時間）；Forrest分類","慢性出血→鉄欠乏性貧血；大量出血→ショック"] },
      { id: "gi_ulcer", label: "消化性潰瘍",
        keys: ["H. pylori（70-90%）・NSAIDs；胃/十二指腸潰瘍","UBT/便中抗原；3剤除菌（PPI+AMPC+CAM）","合併症：出血（Forrest Ia→緊急止血）・穿孔","ストレス潰瘍（ICU）：PPI/H₂B予防的投与"] },
      { id: "gi_ileus", label: "腸閉塞・急性腹症",
        keys: ["癒着（術後最多）・腫瘍・Meckel・ヘルニア嵌頓","腹部X線：ニボー；CT：拡張腸管・閉塞点","絞扼（血流障害）→緊急手術","急性虫垂炎：McBurney圧痛→腹腔鏡下切除"] },
      { id: "gi_ap", label: "急性膵炎",
        keys: ["アルコール・胆石（2大原因）；Ranson/CT重症度","絶食・大量補液・鎮痛；感染性壊死→抗菌薬+ドレナージ","重篤合併症：ARDS・AKI・DIC・敗血症","慢性膵炎：石灰化・嚢胞；膵癌リスク↑"] },
    ] },
    { sid: "hbp", diseases: [
      { id: "hbp_cirr", label: "肝硬変",
        keys: ["線維化→門脈圧亢進；Child-Pugh/MELD","四大合併症：食道静脈瘤・腹水（SBP）・肝性脳症・HCC","肝腎症候群：乏尿＋腎不全（予後不良）→肝移植","ナドロール（門脈圧降下）；アルブミン補液（SBP予防）"] },
      { id: "hbp_hcc", label: "肝細胞癌",
        keys: ["HBV/HCV→肝硬変→HCC（surveillance）","AFP・PIVKA-II↑；動脈相濃染＋門脈相washout","肝切除（Child A）・RFA（小病変）・TACE","Atezolizumab+Bevacizumab（進行期一次治療）"] },
      { id: "hbp_hbv", label: "B型肝炎",
        keys: ["HBs抗原・HBe抗原；垂直/水平感染","慢性化→肝硬変→HCC；テノホビル/エンテカビル","ワクチンで予防；垂直感染予防：HBIG+ワクチン","劇症肝炎（HBV）：PT<40%→肝移植検討"] },
      { id: "hbp_hcv", label: "C型肝炎",
        keys: ["輸血・注射針；慢性化率70-80%","DAA（直接作用型：SOF/VEL等）：SVR>95%","肝硬変・HCC進展リスク；除菌後も6か月毎監視","クリオグロブリン血症・膜性増殖性GN（MPGN）合併"] },
      { id: "hbp_pbc", label: "原発性胆汁性胆管炎",
        keys: ["中年女性；抗ミトコンドリア抗体（AMA）陽性","ALK-P↑・γ-GTP↑；掻痒感・黄疸（進行期）","UDCA（第一選択）；ベザフィブラート（UDCA不応）","骨粗鬆症・脂溶性Vit欠乏；末期→肝移植"] },
      { id: "hbp_psc", label: "原発性硬化性胆管炎",
        keys: ["UC合併（70-80%）；胆管の多発狭窄・数珠状変化","MRCP：診断；肝移植が唯一の根治治療","胆管癌リスク↑（年1-1.5%）；年1回サーベイランス","UDCA・バルーン拡張；胆道感染→抗菌薬"] },
      { id: "hbp_pc", label: "膵癌",
        keys: ["膵管癌（95%）；K-RAS変異；喫煙・慢性膵炎","体尾部は無症状期長い；頭部→閉塞性黄疸","FOLFIRINOX / GnP（Gem+nab-PTX）","切除可能→膵頭十二指腸切除；5年生存率<10%"] },
      { id: "hbp_panc", label: "急性・慢性膵炎",
        keys: ["重症急性膵炎：ARDS・AKI・DIC合併→ICU管理","CT重症度分類；感染性壊死→ネクロソーミー","慢性膵炎：アルコール性（最多）；石灰化・嚢胞","慢性膵炎は膵癌の独立した高危険因子"] },
    ] },
    { sid: "jinzo_d", diseases: [
      { id: "jinzo_ckd", label: "CKD",
        keys: ["eGFR<60 or 蛋白尿>3か月；G/Aステージ分類","高血圧・腎性貧血・CKD-MBD・高K・アシドーシス","ARB/ACE-I：蛋白尿軽減；SGLT2：CKD進行抑制","透析（HD/PD）・腎移植；心血管死が最多死因"] },
      { id: "jinzo_dn", label: "糖尿病性腎症",
        keys: ["透析導入原因の第1位（日本）","マイクロアルブミン尿→顕性蛋白尿→腎不全","HbA1c<7%・BP<130/80；ARB/ACE-I＋SGLT2","Kimmelstiel-Wilson結節（糸球体病変）"] },
      { id: "jinzo_ns", label: "ネフローゼ症候群",
        keys: ["蛋白尿>3.5g/日・低蛋白血症・浮腫","血栓症（DVT/PTE）・感染症（莢膜菌）・脂質異常","MCNS（小児）：ステロイド高反応；膜性腎症（成人最多）","FGS：ステロイド抵抗；IgA腎症・糖尿病・SLE合併も"] },
      { id: "jinzo_aki", label: "AKI",
        keys: ["KDIGO基準；前腎性（最多）・腎性・後腎性","ATN：虚血・造影剤・アミノグリコシド・ミオグロビン","横紋筋融解（CPK↑・ミオグロビン尿）・MMキャスト腎症","補液・電解質補正；重症→透析（緊急：高K・肺水腫）"] },
      { id: "jinzo_iga", label: "IgA腎症",
        keys: ["最多の原発性GN；IgA免疫複合体沈着","肉眼的血尿（感染後）；蛋白尿＋血尿","扁桃摘出＋ステロイドパルス；ACE-I/ARB","RPGN型：免疫抑制＋ステロイド→CKD進展リスク高"] },
      { id: "jinzo_pkd", label: "多発性嚢胞腎",
        keys: ["ADPKD（PKD1/PKD2変異）；常染色体優性","嚢胞増大→腎不全；高血圧・血尿・腰痛","トルバプタン（V2受容体拮抗）：嚢胞増大抑制","脳動脈瘤（10-40%）→SAHリスク；肝嚢胞合併"] },
      { id: "jinzo_lupus", label: "ループス腎炎",
        keys: ["SLE患者の50-70%；WHO分類（I-VI型）","ANA/抗dsDNA↑・C3/C4↓；血尿・蛋白尿","ステロイド＋MMF or シクロホスファミド（IV型）","活動性：抗dsDNA↑・補体↓；増悪しやすい"] },
      { id: "jinzo_rht", label: "腎血管性高血圧",
        keys: ["腎動脈狭窄（FMD・動脈硬化）→RAA系亢進","若年女性：FMD；高齢動脈硬化患者","腎動脈エコー・MRA・造影CT","PTA（FMD優先）；粥状硬化→降圧薬（ARB注意）"] },
    ] },
    { sid: "imma", diseases: [
      { id: "immare_sle", label: "SLE",
        keys: ["抗dsDNA・抗Sm抗体（特異的）；ANA陽性；補体↓（C3・C4）","蝶形紅斑・光線過敏・口腔潰瘍・関節炎・漿膜炎・血液異常","ループス腎炎（50-70%）・NPSLE；抗リン脂質抗体→血栓・流産","PSL＋HCQ；重症→シクロホスファミド・ベリムマブ"] },
      { id: "immare_ra", label: "RA",
        keys: ["RF・抗CCP抗体；対称性MCP/PIP小関節炎；朝のこわばり","パンヌス→骨・軟骨破壊；DAS28で活動性評価","MTX第一選択→抗TNF-α・抗IL-6（トシリズマブ）・JAK阻害薬","間質性肺炎・血管炎・アミロイドーシスが関節外合併症"] },
      { id: "immare_pm", label: "PM/DM",
        keys: ["対称性近位筋力低下；CK↑；筋電図・筋生検で確定","DM：Gottron丘疹・ヘリオトロープ疹（特異的皮膚症状）","抗Jo-1抗体（抗ARS抗体）：間質性肺炎合併（注意）","悪性腫瘍合併（DM>PM）；PSL±免疫抑制薬"] },
      { id: "immare_ssc", label: "強皮症",
        keys: ["Raynaud現象（初発が多い）；手指から体幹方向の皮膚硬化","びまん型：Scl-70（抗トポイソメラーゼI）→肺線維症","限局型：抗セントロメア抗体；CREST症候群；PAH","腎クリーゼ（高血圧・AKI）→ACE-I；肺線維症→ニンテダニブ"] },
      { id: "immare_sje", label: "シェーグレン",
        keys: ["抗SS-A（Ro）・抗SS-B（La）抗体；外分泌腺障害","乾燥眼（シルマーテスト）・乾燥口（唾液腺生検）","腺外：間質性肺炎・末梢神経炎・腎尿細管性アシドーシス","悪性リンパ腫（MALT型）リスク↑；人工涙液・ピロカルピン"] },
      { id: "immare_anca", label: "ANCA血管炎",
        keys: ["GPA：PR3-ANCA（c-ANCA）；鞍鼻・肺出血・半月体形成GN","MPA：MPO-ANCA（p-ANCA）；急速進行性GN・間質性肺炎","EGPA：喘息＋末梢神経炎＋好酸球著増（500/μL以上）","PSL＋シクロホスファミド or RTX；再発多く維持療法必要"] },
      { id: "immare_ana", label: "アナフィラキシー",
        keys: ["全身性I型アレルギー；ハチ毒・食物・βラクタム系薬","蕁麻疹・喉頭浮腫・喘鳴・低血圧・意識障害","第一選択：アドレナリン筋注（0.3mg大腿外側）が絶対優先","抗ヒスタミン・ステロイドは補助（遅効性）；自己注射（エピペン）"] },
      { id: "immare_bec", label: "ベーチェット",
        keys: ["口腔アフタ（必発）＋外陰部潰瘍・眼病変・皮膚症状","HLA-B51陽性；針反応（Pathergy test）陽性","眼ベーチェット（ぶどう膜炎）→失明リスク；神経ベーチェット","コルヒチン（粘膜）；眼→シクロスポリン・抗TNF-α"] },
    ] },
    { sid: "hema", diseases: [
      { id: "hema_ife", label: "鉄欠乏性貧血",
        keys: ["消化管出血・月経過多・吸収障害が原因","小球性低色素性貧血；血清鉄↓・TIBC↑・フェリチン↓","鉄剤補充（経口/静注）；必ず原因検索","慢性疾患性貧血との鑑別：フェリチン正常〜↑"] },
      { id: "hema_mds", label: "MDS",
        keys: ["無効造血→汎血球減少；骨髄異形成","IPSS-R低リスク：輸血＋ESA；高リスク：アザシチジン→移植","AML転化リスク：高リスクMDSで30-40%","del(5q)：レナリドミドが有効；5番染色体異常"] },
      { id: "hema_aml", label: "AML/APL",
        keys: ["汎血球減少；Auer小体（AML）","APL（M3/t(15;17)）：ATRA＋As₂O₃；DIC合併（緊急）","7+3療法（Ara-C+アントラサイクリン）→地固め→移植","FLT3変異→ミドスタウリン；IDH1/2変異→阻害薬"] },
      { id: "hema_mm", label: "多発性骨髄腫",
        keys: ["形質細胞腫瘍；M蛋白（IgG最多）","CRAB：高Ca・腎不全・貧血・骨病変（溶骨性）","VRd（ボルテゾミブ＋Len＋Dex）→ASCT","ダラツムマブ（抗CD38）；Bisphos（骨病変）"] },
      { id: "hema_lym", label: "悪性リンパ腫",
        keys: ["NHL（最多；DLBCL/FL）vs HL（若年・縦隔）","DLBCL：R-CHOP；HL：ABVD/BEACOPP","腫瘍崩壊症候群（TLS）：高K・高P・高尿酸・AKI","縦隔腫瘍（HL）→上大静脈症候群；神経圧迫"] },
      { id: "hema_dic", label: "DIC",
        keys: ["消費性凝固障害；基礎疾患（敗血症・APL・産科）","PT/APTT延長・Fb↓・FDP↑・D-dimer↑・血小板↓","APL：ATRA（DIC急速改善）；敗血症性DIC：AT補充","ARDS・腎不全・多臓器不全に合併・進展"] },
      { id: "hema_itp", label: "ITP/TTP",
        keys: ["ITP：抗血小板抗体→血小板破壊；<10万/μL","ステロイド→IVIG→リツキシマブ→脾摘","TTP：ADAMTS13欠乏→MAHA＋血小板減少＋AKI","TTP五徴：MAHA・血小板↓・AKI・発熱・神経症状"] },
      { id: "hema_ha", label: "溶血性貧血",
        keys: ["AIHA（温式：抗IgG；寒冷凝集素：抗IgM）；DAT陽性","PNH：CD55/CD59欠損→補体溶血；血栓症（特に静脈系）","SLE/CLL合併AIHA；黄疸・脾腫・胆石合併","G6PD欠乏：薬剤/感染誘発性溶血（ハインツ小体）"] },
    ] },
  ],
  relations: [
    {"from":"endo_dm","to":"jinzo_dn","label":"DM→腎症","explain":"持続的高血糖→糸球体内高血圧→基底膜肥厚・Kimmelstiel-Wilson結節形成。マイクロアルブミン尿→顕性蛋白尿→末期腎不全へ進行。日本の透析導入原因第1位。ARB+SGLT2阻害薬で腎保護・進行抑制。"},
    {"from":"endo_dm","to":"neur_stroke","label":"DM→脳梗塞","explain":"高血糖→酸化ストレス・炎症→大血管症（アテローム硬化）によるアテローム血栓性梗塞、かつ小血管症→ラクナ梗塞。脳梗塞の独立した危険因子。血糖・血圧・脂質の包括管理が必須。"},
    {"from":"endo_dm","to":"circ_ami","label":"DM→AMI","explain":"高血糖→酸化ストレス・炎症→冠動脈アテローム硬化促進。DM患者はAMIリスク2〜4倍。自律神経障害による痛覚低下で「無痛性心筋梗塞」を見逃しやすい点に注意。"},
    {"from":"endo_aldo","to":"circ_htn","label":"原アルド→高血圧","explain":"副腎腫瘍/過形成→アルドステロン過剰→Na貯留・K喪失→血圧上昇。二次性高血圧の最多原因（10〜20%）。ARR>200で疑い、副腎静脈サンプリングで側性を確定して手術/MRAを選択。"},
    {"from":"endo_cush","to":"circ_htn","label":"クッシング→高血圧","explain":"コルチゾール過剰→ミネラルコルチコイド様作用・RAA系亢進・交感神経活性化→高血圧。満月様顔・皮膚線条・骨粗鬆症を伴う。原因除去（下垂体/副腎手術）が根本治療。"},
    {"from":"circ_htn","to":"neur_ich","label":"高血圧→脳出血","explain":"慢性高血圧→細動脈の脂質硝子変性→小動脈瘤（Charcot-Bouchard動脈瘤）形成→破裂。被殻（最多）・視床・橋・小脳に好発。収縮期血圧<140 mmHg管理が一次予防の要。"},
    {"from":"circ_htn","to":"jinzo_ckd","label":"高血圧→CKD","explain":"高血圧→腎細動脈硬化→糸球体硬化→腎機能低下（高血圧腎硬化症）。逆にCKD→体液貯留・RAA系亢進→高血圧悪化（心腎連関）。ARB/ACE-I+SGLT2阻害薬で双方を保護。"},
    {"from":"circ_af","to":"neur_stroke","label":"AF→脳塞栓","explain":"心房細動→左心耳内血栓形成→塞栓性脳梗塞（心原性脳塞栓）。CHADS₂スコア≥2でDOAC必須。広範梗塞になりやすく重篤。発症6時間以内の機械的血栓回収術（MCA閉塞等）が有効。"},
    {"from":"circ_ie","to":"neur_stroke","label":"IE→脳塞栓","explain":"感染性心内膜炎の疣贅→剥離→脳塞栓が最多の全身塞栓合併症。抗凝固は推奨されない（出血性梗塞リスク）。疣贅>10 mm・塞栓反復は外科的手術適応。"},
    {"from":"circ_hf","to":"jinzo_ckd","label":"心腎症候群","explain":"心不全→心拍出量低下・腎静脈うっ血→腎血流減少→AKI/CKD進行（I型・II型心腎症候群）。逆にCKD→体液過剰・心負荷増大。SGLT2阻害薬が心腎両保護効果を示す。"},
    {"from":"circ_dvt","to":"resp_pte","label":"DVT→肺塞栓","explain":"下肢深部静脈血栓が剥離→右心→肺動脈閉塞→右室後負荷急増。突然の呼吸困難・胸痛・頻脈・SpO₂低下。血行動態不安定の大量PTEでは血栓溶解療法（tPA）が適応。"},
    {"from":"jinzo_ns","to":"circ_dvt","label":"ネフローゼ→DVT","explain":"低アルブミン→肝でFb・凝固因子代償産生増加＋抗トロンビンIII・プロテインC/S尿中喪失→過凝固状態。腎静脈血栓を含むDVT・PTEリスクが著明に上昇する。"},
    {"from":"resp_copd","to":"circ_pah","label":"COPD→肺高血圧","explain":"慢性低酸素血症→肺血管収縮・血管壁リモデリング→肺動脈圧上昇→右室肥大・右心不全（肺性心）。mPAP≥25 mmHgで確定。在宅酸素療法が肺高血圧進行を抑制する。"},
    {"from":"resp_lc","to":"endo_adrenal","label":"肺癌→副腎転移","explain":"肺癌は副腎転移が最多（剖検の40〜70%）。両側副腎の広範破壊→副腎不全（倦怠感・低血圧・低Na・高K・低血糖）。ACTH・コルチゾール評価と補充が必要。"},
    {"from":"resp_sarc","to":"endo_hca","label":"サルコイド→高Ca","explain":"肉芽腫内活性化マクロファージが1α-水酸化酵素を発現→活性型VitD（1,25(OH)₂D）産生過剰→腸管Ca吸収↑→高Ca血症。ステロイドで活性型VitD産生を抑制し改善。"},
    {"from":"resp_pneu","to":"hema_dic","label":"敗血症→DIC","explain":"重症肺炎→敗血症→内毒素・サイトカイン放出→血管内皮障害・組織因子大量発現→凝固連鎖亢進→DIC。AT補充・rTM（トロンボモジュリン）で凝固制御。APLでは逆にDICが先行する。"},
    {"from":"hbp_cirr","to":"gi_bleed","label":"肝硬変→静脈瘤出血","explain":"門脈圧亢進→食道・胃静脈瘤形成→破裂出血（大量吐血/タール便）。急性期は内視鏡的結紮術（EVL）/硬化療法。二次予防はナドロール＋EVL。出血死亡率20〜30%。"},
    {"from":"gi_uc","to":"hbp_psc","label":"UC→PSC","explain":"潰瘍性大腸炎患者の5〜10%に原発性硬化性胆管炎（PSC）合併。胆管周囲の線維性炎症→多発狭窄・数珠状変化。胆管癌リスク年1〜1.5%。根治は肝移植のみ。"},
    {"from":"gi_crc","to":"hbp_hcc","label":"大腸癌→肝転移","explain":"大腸癌は門脈経由で肝転移（同時性20〜30%）。切除可能な孤立性肝転移では原発巣切除＋肝切除で根治を狙う。FOLFOX/FOLFIRI+Bevacizumabで化学療法。"},
    {"from":"jinzo_ckd","to":"hema_ife","label":"腎性貧血","explain":"CKD→エリスロポエチン（EPO）産生低下→赤血球造血抑制→正球性正色素性貧血。eGFR<30で顕著。ESA（ダルベポエチン等）またはHIF-PH阻害薬（ロキサデュスタット）で治療。"},
    {"from":"hema_mm","to":"jinzo_aki","label":"MM→cast腎症","explain":"骨髄腫軽鎖（Bence Jones蛋白）→尿細管でTamm-Horsfall蛋白と結合→管型形成→尿細管閉塞・壊死→AKI（骨髄腫腎）。大量補液+VRd化学療法が基本。"},
    {"from":"hema_dic","to":"resp_ards","label":"DIC→ARDS","explain":"DIC→肺微小血管内血栓→肺内皮障害・透過性亢進→両側浸潤影・P/F<300→ARDS。敗血症性DICに合併しやすく多臓器不全へ進展。死亡率30〜45%。"},
    {"from":"jinzo_lupus","to":"hema_itp","label":"SLE→ITP","explain":"SLE関連ITP：抗血小板抗体（IgG型）産生→RESによる血小板破壊。SLEの活動性と相関。ステロイド→IVIG→リツキシマブで治療。TTPとの鑑別（ADAMTS13測定）も重要。"},
    {"from":"gi_ap","to":"resp_ards","label":"膵炎→ARDS","explain":"重症急性膵炎→膵消化酵素・炎症性サイトカイン（IL-6・TNF-α）大量放出→SIRS→肺微小血管透過性亢進→ARDS。膵炎合併ARDSの死亡率は30〜50%に達する。"},
    {"from":"hbp_hcv","to":"jinzo_ns","label":"HCV→GN","explain":"HCV→クリオグロブリン産生（II型混合型）→免疫複合体腎沈着→MPGN（膜性増殖性GN）型腎炎。蛋白尿・血尿・腎機能低下。DAA（SOF/VEL等）によるHCV排除が根本治療。"},
    {"from":"endo_hca","to":"jinzo_aki","label":"高Ca→AKI","explain":"高Ca血症→腎血管収縮・尿濃縮力低下（多尿・脱水）→腎前性AKI。さらに腎石灰化（ネフロカルシノーシス）→腎性AKI。大量補液＋ビスホスホネート（ゾレドロン酸）が治療。"},
    {"from":"neur_gbs","to":"resp_ards","label":"GBS→呼吸不全","explain":"ギラン・バレー症候群→上行性脱髄→呼吸筋（横隔膜・肋間筋）麻痺→呼吸不全。努力肺活量<20 mL/kgで人工呼吸器適応。ICU管理＋IVIG/血漿交換が治療の柱。"},
    {"from":"immare_sle","to":"jinzo_lupus","label":"SLE→ループス腎炎","explain":"SLEの50〜70%にループス腎炎合併。抗dsDNA抗体・補体（C3↓・C4↓）→免疫複合体腎炎（WHO分類III/IV型が重症）。半月体形成性GNは急速進行性→緊急ステロイドパルス＋シクロホスファミド（またはMMF）。"},
    {"from":"immare_sle","to":"hema_itp","label":"SLE→ITP","explain":"SLE関連ITP：抗血小板抗体（IgG型）産生→血小板破壊。SLE活動性マーカー（抗dsDNA↑・補体↓）と相関。ステロイド→IVIG→リツキシマブで治療。TTP（ADAMTS13測定）との鑑別が必要。"},
    {"from":"immare_ra","to":"resp_iip","label":"RA→間質性肺炎","explain":"RA関連間質性肺炎（RA-ILD）：UIPパターンが最多（IPFと類似）。MTX誘発性肺炎との鑑別が重要（薬剤性はびまん性陰影＋KL-6↑）。RA-ILDはMTX継続困難となりレフルノミド・アバタセプト等へ変更。"},
    {"from":"immare_pm","to":"resp_iip","label":"PM/DM→ILD","explain":"多発性筋炎・皮膚筋炎の30〜40%にILD合併。抗Jo-1抗体（抗ARS抗体症候群）では特に頻度が高い。急性進行性ILDは死亡率が高く早期ステロイドパルス＋タクロリムス/シクロスポリンが必要。"},
    {"from":"immare_ssc","to":"circ_pah","label":"強皮症→PAH","explain":"限局型強皮症（抗セントロメア抗体）では肺動脈性肺高血圧（PAH）が高率に合併。右心カテーテル（mPAP≥25）で確定診断。ERA（ボセンタン）・PDE5阻害薬・プロスタサイクリン製剤の3系統を病態に応じ使用。"},
    {"from":"immare_anca","to":"jinzo_aki","label":"ANCA血管炎→AKI","explain":"ANCA関連血管炎→腎微小血管炎→壊死性半月体形成性GN→急速進行性腎不全（RPGN）。MPO-ANCA（MPA）に多い。血清Cr急上昇＋血尿・蛋白尿。緊急PSLパルス＋RTX（またはCPA）＋血漿交換（抗GBM合併例）。"},
    {"from":"immare_sje","to":"hbp_pbc","label":"SS→PBC","explain":"シェーグレン症候群と原発性胆汁性胆管炎（PBC）はしばしば合併（SS患者の約10%にPBC）。どちらも自己免疫性の外分泌腺・胆管障害。AMA陽性・ALK-P↑・掻痒感。UDCA（ウルソデオキシコール酸）が第一選択。"},
    {"from":"immare_bec","to":"neur_stroke","label":"ベーチェット→神経","explain":"神経ベーチェット（約5〜10%）：中枢神経病変（脳幹病変が多い）・静脈洞血栓症・無菌性髄膜炎。PSL＋CPA・MTXで治療。静脈洞血栓は抗凝固（ヘパリン→ワルファリン）。神経型は予後不良。"},
    {"from":"hema_mds","to":"hema_aml","label":"AML転化"},
    {"from":"hbp_hbv","to":"hbp_cirr","label":"→肝硬変"},
    {"from":"hbp_hcv","to":"hbp_cirr","label":"→肝硬変"},
    {"from":"hbp_cirr","to":"hbp_hcc","label":"→HCC"},
    {"from":"circ_ami","to":"circ_hf","label":"AMI→心不全"},
    {"from":"gi_uc","to":"gi_crc","label":"UC→大腸癌"},
    {"from":"jinzo_dn","to":"jinzo_ckd","label":"腎症→CKD"},
    {"from":"endo_dm","to":"endo_met"},
    {"from":"immare_sle","to":"immare_ra","label":"CTD合併"},
    {"from":"immare_ra","to":"immare_sje","label":"RA+SS"},
  ],
};
